import sys
from pathlib import Path

PROJECT_ROOT = Path("/home/lukasz/PycharmProjects/Magisterka").resolve()
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "nanoGPT"))

import import_ipynb
from praca_core import *


import os
import gc
import time
import pickle
import signal
import psutil
import multiprocessing as mp
from queue import Empty
from tqdm.auto import tqdm





TIMEOUT_SECONDS = 300
RAM_LIMIT_GB = 20
SAVE_EVERY = 1
ANSWERS_PATH = "answers_gpt.pkl"


def worker(i, q):
    try:
        proc = psutil.Process(os.getpid())
        ram_limit = RAM_LIMIT_GB * 1024**3

        bundle_proving = load_nanogpt_bundle("out-NEW_CORPUS_PROVING")

        start = time.monotonic()

        def check_limits():
            if time.monotonic() - start > TIMEOUT_SECONDS:
                raise TimeoutError("timeout")
            if proc.memory_info().rss > ram_limit:
                raise MemoryError("RAM limit exceeded")

        # jeśli procedure nie przyjmuje check_limits, to tego nie przekażesz
        # ale worker i tak jest zabijany z zewnątrz po timeout
        result = procedure(
            i,
            bundle_proving,
            bundle_smashing,
            temperature=1.0,
            max_iter=50,
            deg=5,
            max_failed_attempts=2,
            tries_number=10
        )

        q.put(("ok", result))

    except Exception as e:
        q.put(("err", f"{type(e).__name__}: {e}"))

    finally:
        gc.collect()


def run_one(i):
    ctx = mp.get_context("spawn")
    q = ctx.Queue()
    p = ctx.Process(target=worker, args=(i, q))
    p.start()

    proc = psutil.Process(p.pid)
    deadline = time.monotonic() + TIMEOUT_SECONDS
    ram_limit = RAM_LIMIT_GB * 1024**3

    while p.is_alive():
        if time.monotonic() > deadline:
            p.terminate()
            p.join()
            return None, "timeout"

        try:
            if proc.memory_info().rss > ram_limit:
                p.terminate()
                p.join()
                return None, "ram"
        except psutil.NoSuchProcess:
            break

        time.sleep(0.5)

    p.join()

    try:
        status, result = q.get_nowait()
    except Empty:
        return None, "no_result"

    if status == "ok":
        return result, None
    else:
        return None, result


def save_answers():
    with open(ANSWERS_PATH, "wb") as f:
        pickle.dump(answers, f)

tests = '''((a ∧ b) ∧ c ∧ d ∧ e) → ((a ∧ d) ∧ e)
(a ∧ b) → (¬a → c)
p → p
¬p → ¬p
p ∨ ¬p
¬(p ∧ ¬p)
¬¬p → p
p → ¬¬p
p ↔ p
¬p ↔ ¬p
(p ∧ q) → p
(p ∧ q) → q
p → (p ∨ q)
q → (p ∨ q)
p → (q → p)
¬p → (p → q)
(p ∧ q) → (q ∧ p)
((p ∧ q) ∧ r) → (p ∧ (q ∧ r))
(p ∧ p) ↔ p
(p ∨ p) ↔ p
(p ∨ q) → (q ∨ p)
(p ∧ (q ∧ r)) → ((p ∧ q) ∧ r)
(p ∨ (q ∨ r)) → ((p ∨ q) ∨ r)
((p ∨ q) ∨ r) → (p ∨ (q ∨ r))
(p ∧ (q ∨ r)) → ((p ∧ q) ∨ (p ∧ r))
((p ∧ q) ∨ (p ∧ r)) → (p ∧ (q ∨ r))
(p ∨ (q ∧ r)) → ((p ∨ q) ∧ (p ∨ r))
((p ∨ q) ∧ (p ∨ r)) → (p ∨ (q ∧ r))
(p ∧ (p ∨ q)) ↔ p
(p ∨ (p ∧ q)) ↔ p
(p ∧ q) → (p ∨ q)
p → ((p → q) → q)
(p ∧ (p → q)) → q
(¬q ∧ (p → q)) → ¬p
(p → q) → (¬q → ¬p)
(¬q → ¬p) → (p → q)
((p → q) ∧ (q → r)) → (p → r)
(p → (q → r)) → ((p ∧ q) → r)
((p ∧ q) → r) → (p → (q → r))
(p → (q → r)) → (q → (p → r))
(p → q) → ((r → p) → (r → q))
((p → r) ∧ (q → r)) → ((p ∨ q) → r)
((p → q) ∧ (p → r)) → (p → (q ∧ r))
((p → r) ∧ (q → s)) → ((p ∧ q) → (r ∧ s))
((p → r) ∧ (q → r)) → ((p ∨ q) → r)
((p → q) ∧ (r → s)) → ((p ∨ r) → (q ∨ s))
((p → q) ∧ (r → s)) → ((p ∧ r) → (q ∧ s))
p → (q → (p ∧ q))
p → (p ∨ (q ∧ r))
(p ∧ q) → ((p → r) → r)
(p ∧ q) → ¬(p → ¬q)
(p ∧ ¬q) → ¬(p → q)
¬(p → q) → p
¬(p → q) → ¬q
¬(p → q) ↔ (p ∧ ¬q)
(p → q) ↔ (¬p ∨ q)
¬(p ∧ q) ↔ (¬p ∨ ¬q)
¬(p ∨ q) ↔ (¬p ∧ ¬q)
(p ↔ q) → (p → q)
(p ↔ q) → (q → p)
((p → q) ∧ (q → p)) → (p ↔ q)
(p ↔ q) ↔ ((p → q) ∧ (q → p))
(p ↔ q) ↔ ((p ∧ q) ∨ (¬p ∧ ¬q))
¬(p ↔ q) ↔ ((p ∧ ¬q) ∨ (¬p ∧ q))
(p ↔ q) → (¬p ↔ ¬q)
(p ↔ q) → ((p ∧ r) ↔ (q ∧ r))
(p ↔ q) → ((p ∨ r) ↔ (q ∨ r))
(p ↔ q) → ((r → p) ↔ (r → q))
(p ↔ q) → ((p → r) ↔ (q → r))
(p ↔ q) → ((p ↔ r) → (q ↔ r))
((p ↔ q) ∧ (q ↔ r)) → (p ↔ r)
(p ↔ q) → ((q ↔ r) → (p ↔ r))
p ∨ ¬¬¬p
¬¬¬p ↔ ¬p
¬¬(p ∧ q) ↔ (p ∧ q)
¬¬(p ∨ q) ↔ (p ∨ q)
¬¬(p → q) ↔ (p → q)
((p → q) → p) → p
(¬p → p) → p
p → (q ∨ ¬q)
(p → q) ∨ (q → p)
(p → q) ∨ (p → ¬q)
((p → q) ∧ p) → q
((p → q) ∧ ¬q) → ¬p
((p ∨ q) ∧ ¬p) → q
((p ∨ q) ∧ ¬q) → p
((p ↔ q) ∧ p) → q
((p ↔ q) ∧ q) → p
((p ↔ q) ∧ ¬p) → ¬q
((p ↔ q) ∧ ¬q) → ¬p
((p → q) ∧ (¬p → q)) → q
((p → r) ∧ (q → r) ∧ (p ∨ q)) → r
(((p → r) ∧ (q → r)) ∧ (p ∨ q)) → r
((p → q) ∧ (q → r) ∧ p) → r
(((p → q) ∧ (q → r)) ∧ p) → r
((p → r) ∧ (q → s) ∧ (p ∨ q)) → (r ∨ s)
(((p → r) ∧ (q → s)) ∧ (p ∨ q)) → (r ∨ s)
((p → q) ∧ (r → s) ∧ (p ∧ r)) → (q ∧ s)
(((p → q) ∧ (r → s)) ∧ (p ∧ r)) → (q ∧ s)
((p → q) ∧ (q → r) ∧ (r → s)) → (p → s)
(((p → q) ∧ (q → r)) ∧ (r → s)) → (p → s)
p → (q → (r → p))
(p ∧ q ∧ r) → p
(p ∧ q ∧ r) → q
(p ∧ q ∧ r) → r
p → (q → (r → (p ∨ q)))
p → (q → (r → (p ∨ q ∨ r)))
(p ∧ q) → ¬(¬p ∧ q)
(p ∧ q) → ¬(p ∧ ¬q)
(p ∧ q) → ¬(¬p ∨ ¬q)
(p → q) → ((p ∧ r) → (q ∧ r))
(p → q) → ((r ∧ p) → (r ∧ q))
(p → q) → ((p ∨ r) → (q ∨ r))
(p → q) → ((r ∨ p) → (r ∨ q))
(p ↔ q) → ((p ∧ r) ↔ (q ∧ r))
(p ↔ q) → ((p ∨ r) ↔ (q ∨ r))
((p ∧ q) → r) ↔ (p → (q → r))
((p ∨ q) → r) ↔ ((p → r) ∧ (q → r))
(p → (q ∧ r)) ↔ ((p → q) ∧ (p → r))
(p ∧ (q → r)) → ((p ∧ q) → r)
(p → q) → ((p → ¬q) → ¬p)
(¬p → q) → ((¬p → ¬q) → p)
(p → q) → ((¬p → q) → q)
(p → q) → ((q → r) → (¬r → ¬p))
(p → q) → ((¬q ∨ r) → (¬p ∨ r))
(p → q) → ((q ↔ r) → (p → r))
(p ↔ q) → ((q ↔ r) → (p ↔ r))
((p → q) ∧ (r → s) ∧ (p ∨ r)) → (q ∨ s)
((p → q) ∧ (q → r) ∧ p) → r
((p ↔ q) ∧ (q ↔ r)) → (p ↔ r)
(p → (q → r)) → ((p → q) → (p → r))
(p → q) → ((p → (q → r)) → (p → r))
(p → q) → ((r → p) → (r → q))
(p → q) → ((q → r) → (p → r))
(p → q) → ((q → r) → ((p ∨ s) → (r ∨ s)))
(p → r) → ((q → s) → ((p ∨ q) → (r ∨ s)))
(p → r) → ((q → r) → ((p ∨ q) → r))
(p → q) → ((p → r) → (p → (q ∧ r)))
(p → r) → ((q → s) → ((p ∧ q) → (r ∧ s)))
(p → q) → ((¬p → q) → q)
(p → q) → ((p → ¬q) → ¬p)
(¬q → ¬p) → ((p ∨ r) → (q ∨ r))
(p ↔ q) → ((¬p ∨ r) ↔ (¬q ∨ r))
(p ↔ q) → ((p ∧ ¬r) ↔ (q ∧ ¬r))
(p ↔ q) → ((p ∨ ¬r) ↔ (q ∨ ¬r))
(p ↔ q) → ((r → p) ↔ (r → q))
(p ↔ q) → ((p → r) ↔ (q → r))
(p ↔ q) → ((r ↔ p) ↔ (r ↔ q))
((p ↔ q) ∧ p) → q
((p ↔ q) ∧ ¬p) → ¬q
((p ↔ q) ∧ q) → p
((p ↔ q) ∧ ¬q) → ¬p
(p ∨ (¬p ∧ q)) ↔ (p ∨ q)
(p ∧ (¬p ∨ q)) ↔ (p ∧ q)
((p ∧ q) ∨ (p ∧ ¬q)) ↔ p
((p ∨ q) ∧ (p ∨ ¬q)) ↔ p
((p ∧ q) ∨ (¬p ∧ q)) ↔ q
((p ∨ q) ∧ (¬p ∨ q)) ↔ q
((p ∧ q) ∨ (¬p ∧ ¬q) ∨ (p ∧ ¬q) ∨ (¬p ∧ q))
¬((p ∧ q) ∧ ¬(p ∧ q))
((p → q) ∧ (p → ¬q)) → ¬p
((p → r) ∧ (q → r)) → ((p ∨ q) → r)
((p → r) ∧ (¬p → r)) → r
((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → s)) → s
(((p → q) ∧ (¬p → r)) ∧ ((q → s) ∧ (r → s))) → s
((p → q) ∧ (¬p → q)) → q
((p → r) ∧ (¬p → r)) → r
((p → q) ∧ (q → r) ∧ ¬r) → ¬p
(((p → q) ∧ (q → r)) ∧ ¬r) → ¬p
((p → q) ∧ ¬q) → ¬p
((p ↔ q) ∧ (q ↔ r) ∧ p) → r
(((p ↔ q) ∧ (q ↔ r)) ∧ ¬r) → ¬p
((p → q) ∧ (q → r) ∧ (r → s) ∧ p) → s
((((p → q) ∧ (q → r)) ∧ (r → s)) ∧ p) → s
(p ↔ q) → ((p ∨ r) ↔ (q ∨ r))
(p ↔ q) → ((p ∧ r) ↔ (q ∧ r))
(p ↔ q) → ((¬p ∨ r) ↔ (¬q ∨ r))
(p ↔ q) → ((¬p ∧ r) ↔ (¬q ∧ r))
(p ↔ q) → ((r → ¬p) ↔ (r → ¬q))
(p ↔ q) → ((¬p → r) ↔ (¬q → r))
(((p → r) ∧ (q → r)) ∧ ((r → s) ∧ (p ∨ q))) → s
((((p → r) ∧ (q → r)) ∧ (r → s)) ∧ (p ∨ q)) → s
(((p → q) ∧ (r → s)) ∧ ((q → t) ∧ (s → t))) → ((p ∨ r) → t)
((((p → q) ∧ (r → s)) ∧ ((q → t) ∧ (s → t))) ∧ (p ∨ r)) → t
(((p → q) ∧ (q → r)) ∧ ((s → t) ∧ (t → u))) → ((p ∧ s) → (r ∧ u))
((((p → q) ∧ (q → r)) ∧ ((s → t) ∧ (t → u))) ∧ (p ∧ s)) → (r ∧ u)
(((p → r) ∧ (q → s)) ∧ (p ∨ q)) → (r ∨ s)
(((p → r) ∧ (q → s)) ∧ ((r → t) ∧ (s → t))) → ((p ∨ q) → t)
((((p → r) ∧ (q → s)) ∧ ((r → t) ∧ (s → t))) ∧ (p ∨ q)) → t
(((p → q) ∧ (¬p → r)) ∧ ((q → s) ∧ (r → s))) → s
((((p → q) ∧ (¬p → r)) ∧ ((q → s) ∧ (r → s))) ∧ p) → s
((((p → q) ∧ (¬p → r)) ∧ ((q → s) ∧ (r → s))) ∧ ¬p) → s
(((p ↔ q) ∧ (q ↔ r)) ∧ (r ↔ s)) → (p ↔ s)
((((p ↔ q) ∧ (q ↔ r)) ∧ (r ↔ s)) ∧ p) → s
((((p ↔ q) ∧ (q ↔ r)) ∧ (r ↔ s)) ∧ ¬s) → ¬p
(((p → q) ∧ (¬p → q)) ∧ ((q → r) ∧ (¬r → s))) → (r ∨ s)
((((p → q) ∧ (¬p → q)) ∧ ((q → r) ∧ (¬r → s))) ∧ p) → (r ∨ s)
((((p → q) ∧ (¬p → q)) ∧ ((q → r) ∧ (¬r → s))) ∧ ¬p) → (r ∨ s)
(((p → q) ∧ (q → r)) ∧ ((r → s) ∧ (s → t))) → (p → t)
((((p → q) ∧ (q → r)) ∧ ((r → s) ∧ (s → t))) ∧ p) → t
(((p → r) ∧ (q → r)) ∧ ((¬p → s) ∧ (¬q → s))) → (r ∨ s)
((((p → r) ∧ (q → r)) ∧ ((¬p → s) ∧ (¬q → s))) ∧ ¬p) → (r ∨ s)
((((p → r) ∧ (q → r)) ∧ ((¬p → s) ∧ (¬q → s))) ∧ ¬q) → (r ∨ s)
((((p → r) ∧ (q → r)) ∧ ((¬p → s) ∧ (¬q → s))) ∧ (p ∨ q)) → r
((((p → r) ∧ (q → r)) ∧ ((¬p → s) ∧ (¬q → s))) ∧ (¬p ∧ ¬q)) → s
(p → q) → (((q → r) ∧ (r → s)) → (p → s))
(p → q) → (((q → r) ∧ (r → s)) → ((p ∨ t) → (s ∨ t)))
(p → q) → (((q → r) ∧ (r → s)) → ((t ∧ p) → (t ∧ s)))
(p ↔ q) → (((q ↔ r) ∧ (r ↔ s)) → (p ↔ s))
((p ↔ q) ∧ (q ↔ r)) → ((p ∨ s) ↔ (r ∨ s))
((p ↔ q) ∧ (q ↔ r)) → ((p ∧ s) ↔ (r ∧ s))
((p ↔ q) ∧ (q ↔ r)) → ((s → p) ↔ (s → r))
((p ↔ q) ∧ (q ↔ r)) → ((p → s) ↔ (r → s))
((p ∨ q ∨ r) ∧ ¬p ∧ ¬q) → r
(((p ∨ q) ∨ r) ∧ ¬p ∧ ¬q) → r
((p ∨ q ∨ r) ∧ ¬p ∧ ¬r) → q
((p ∨ q ∨ r) ∧ ¬q ∧ ¬r) → p
((p → r) ∧ (q → r) ∧ (s → r)) → ((p ∨ q ∨ s) → r)
(((p → r) ∧ (q → r) ∧ (s → r)) ∧ (p ∨ q ∨ s)) → r
((p → q) ∧ (r → s) ∧ (t → u)) → ((p ∧ r ∧ t) → (q ∧ s ∧ u))
(((p → q) ∧ (r → s) ∧ (t → u)) ∧ (p ∧ r ∧ t)) → (q ∧ s ∧ u)
((p → q) ∧ (q → r) ∧ (r → s) ∧ (s → t)) → (p → t)
(((p → q) ∧ (q → r) ∧ (r → s) ∧ (s → t)) ∧ p) → t
((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) → (p ↔ t)
(((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) ∧ p) → t
(((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) ∧ ¬t) → ¬p
((p → r) ∧ (q → s) ∧ (r → t) ∧ (s → u)) → ((p ∧ q) → (t ∧ u))
(((p → r) ∧ (q → s) ∧ (r → t) ∧ (s → u)) ∧ (p ∧ q)) → (t ∧ u)
((p → r) ∧ (q → s) ∧ (r → t) ∧ (s → t)) → ((p ∨ q) → t)
(((p → r) ∧ (q → s) ∧ (r → t) ∧ (s → t)) ∧ (p ∨ q)) → t
((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ (s → u) ∧ (t → u)) → u
(((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ (s → u) ∧ (t → u)) ∧ p) → u
(((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ (s → u) ∧ (t → u)) ∧ ¬p) → u
((p ∨ q) ∧ (p → r) ∧ (q → s) ∧ (r → t) ∧ (s → t)) → t
((p ∨ q ∨ r) ∧ (p → s) ∧ (q → s) ∧ (r → s)) → s
((p ∨ q ∨ r ∨ s) ∧ (p → t) ∧ (q → t) ∧ (r → t) ∧ (s → t)) → t
((p → q) ∧ (r → s) ∧ ((q ∧ s) → t)) → ((p ∧ r) → t)
(((p → q) ∧ (r → s) ∧ ((q ∧ s) → t)) ∧ (p ∧ r)) → t
((p → q) ∧ (r → s) ∧ ((q ∨ s) → t) ∧ (p ∨ r)) → t
((p → q) ∧ (r → s) ∧ (t → u) ∧ ((q ∧ s ∧ u) → v)) → ((p ∧ r ∧ t) → v)
(((p → q) ∧ (r → s) ∧ (t → u) ∧ ((q ∧ s ∧ u) → v)) ∧ (p ∧ r ∧ t)) → v
((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∧ u) → v)) → ((p ∧ s) → v)
(((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∧ u) → v)) ∧ (p ∧ s)) → v
((p → r) ∧ (q → s) ∧ ((r ∨ s) → t) ∧ (p ∨ q)) → t
((p → r) ∧ (q → s) ∧ ((r ∧ s) → t)) → ((p ∧ q) → t)
(((p → r) ∧ (q → s) ∧ ((r ∧ s) → t)) ∧ (p ∧ q)) → t
((p ↔ q) ∧ (r ↔ s) ∧ ((q ∧ s) → t)) → ((p ∧ r) → t)
(((p ↔ q) ∧ (r ↔ s) ∧ ((q ∧ s) → t)) ∧ (p ∧ r)) → t
((p ↔ q) ∧ (r ↔ s) ∧ ((q ∨ s) → t) ∧ (p ∨ r)) → t
((p → q) ∧ (¬p → r) ∧ ((q ∨ r) → s)) → s
(((p → q) ∧ (¬p → r) ∧ ((q ∨ r) → s)) ∧ p) → s
(((p → q) ∧ (¬p → r) ∧ ((q ∨ r) → s)) ∧ ¬p) → s
((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s)) → s
(((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s)) ∧ p) → s
(((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s)) ∧ ¬p) → s
((p ↔ q) ∧ (¬q ↔ r) ∧ ((p ∨ r) → s)) → s
((p ↔ q) ∧ (¬q ↔ r)) → (p ∨ r)
(((p ↔ q) ∧ (¬q ↔ r)) ∧ (p → s) ∧ (r → s)) → s
((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t)) → t
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t)) ∧ p) → t
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t)) ∧ ¬p) → t
((p → q) ∧ (q → r) ∧ (¬p → s) ∧ (r → t) ∧ (s → t)) → t
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ (r → t) ∧ (s → t)) ∧ p) → t
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ (r → t) ∧ (s → t)) ∧ ¬p) → t
((p ↔ q) ∧ (r ↔ s) ∧ ((q ∨ s) → t)) → ((p ∨ r) → t)
((p ↔ q) ∧ (r ↔ s) ∧ (q → s) ∧ (s → t)) → (p → t)
((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) → ((p ∨ u) ↔ (t ∨ u))
((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) → ((p ∧ u) ↔ (t ∧ u))
((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) → ((u → p) ↔ (u → t))
((p ↔ q) ∧ (q ↔ r) ∧ (r ↔ s) ∧ (s ↔ t)) → ((p → u) ↔ (t → u))
((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∨ u) → v)) → ((p ∨ s) → v)
(((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∨ u) → v)) ∧ (p ∨ s)) → v
((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∧ u) → v)) → ((p ∧ s) → v)
(((p → q) ∧ (q → r) ∧ (s → t) ∧ (t → u) ∧ ((r ∧ u) → v)) ∧ (p ∧ s)) → v
((p → r) ∧ (q → s) ∧ (t → u) ∧ ((r ∨ s ∨ u) → v) ∧ (p ∨ q ∨ t)) → v
((p → r) ∧ (q → s) ∧ (t → u) ∧ ((r ∧ s ∧ u) → v)) → ((p ∧ q ∧ t) → v)
(((p → r) ∧ (q → s) ∧ (t → u) ∧ ((r ∧ s ∧ u) → v)) ∧ (p ∧ q ∧ t)) → v
((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ ((s ∨ t) → u)) → u
(((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ ((s ∨ t) → u)) ∧ p) → u
(((p → q) ∧ (¬p → r) ∧ (q → s) ∧ (r → t) ∧ ((s ∨ t) → u)) ∧ ¬p) → u
((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s) ∧ (s → t)) → t
(((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s) ∧ (s → t)) ∧ p) → t
(((p ↔ q) ∧ (¬p ↔ r) ∧ ((q ∨ r) → s) ∧ (s → t)) ∧ ¬p) → t
((p ↔ q) ∧ (¬q ↔ r) ∧ ((p ∨ r) → s) ∧ (s → t)) → t
(((p ↔ q) ∧ (¬q ↔ r) ∧ ((p ∨ r) → s) ∧ (s → t)) ∧ p) → t
(((p ↔ q) ∧ (¬q ↔ r) ∧ ((p ∨ r) → s) ∧ (s → t)) ∧ ¬p) → t
((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t) ∧ (t → u)) → u
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t) ∧ (t → u)) ∧ p) → u
(((p → q) ∧ (q → r) ∧ (¬p → s) ∧ ((r ∨ s) → t) ∧ (t → u)) ∧ ¬p) → u
((p ↔ q) ∧ (q ↔ r) ∧ (s ↔ t) ∧ ((r ∨ t) → u)) → ((p ∨ s) → u)
((p ↔ q) ∧ (q ↔ r) ∧ (s ↔ t) ∧ ((r ∧ t) → u)) → ((p ∧ s) → u)
(((p ↔ q) ∧ (q ↔ r) ∧ (s ↔ t) ∧ ((r ∧ t) → u)) ∧ (p ∧ s)) → u
((p → q) ∧ (q → r) ∧ (r → s) ∧ (¬p → t) ∧ ((s ∨ t) → u)) → u
(((p → q) ∧ (q → r) ∧ (r → s) ∧ (¬p → t) ∧ ((s ∨ t) → u)) ∧ p) → u
(((p → q) ∧ (q → r) ∧ (r → s) ∧ (¬p → t) ∧ ((s ∨ t) → u)) ∧ ¬p) → u
((p → q) ∧ (r → s) ∧ (t → u) ∧ ((q ∨ s ∨ u) → v) ∧ (p ∨ r ∨ t)) → v
((p → q) ∧ (r → s) ∧ (t → u) ∧ ((q ∧ s ∧ u) → v)) → ((p ∧ r ∧ t) → v)
((p ↔ q) ∧ (r ↔ s) ∧ (t ↔ u) ∧ ((q ∨ s ∨ u) → v)) → ((p ∨ r ∨ t) → v)
((p ↔ q) ∧ (r ↔ s) ∧ (t ↔ u) ∧ ((q ∧ s ∧ u) → v)) → ((p ∧ r ∧ t) → v)
((p ↔ q) ∧ (r ↔ s) ∧ (t ↔ u) ∧ ((q → v) ∧ (s → v) ∧ (u → v))) → ((p ∨ r ∨ t) → v)'''.splitlines()


tests = '''¬(((t ∨ v) ∧ ¬((t ∨ v))))
¬(((p ∧ r) ∧ ¬((p ∧ r))))
¬(((u ∨ q) ∧ ¬((u ∨ q))))
((p ∧ ¬t) → ¬¬((p ∧ ¬t)))
¬(((¬u ∨ q) ∧ ¬((¬u ∨ q))))
((((t ∨ v) ∨ p) ∧ ¬p) → ¬p)
(((t ∧ p) ∧ (t ∧ p)) ↔ (t ∧ p))
(((u ↔ r) ∧ (u ↔ r)) ↔ (u ↔ r))
(((s ∧ p) ∨ (s ∧ p)) ↔ (s ∧ p))
((((s ↔ t) → ¬v) ∧ (s ↔ t)) → ¬v)
((t ∧ ¬q) → ((¬s ∨ q) → (t ∧ ¬q)))
((v → (t ∨ p)) → ¬¬((v → (t ∨ p))))
((p → (s ∨ r)) → ¬¬((p → (s ∨ r))))
(((t ∧ q) ∧ u) → ¬¬(((t ∧ q) ∧ u)))
(((u ∨ t) ∨ p) → ¬¬(((u ∨ t) ∨ p)))
(((u ∧ t) → p) → ¬¬(((u ∧ t) → p)))
(((u ∨ t) ∨ s) → ¬¬(((u ∨ t) ∨ s)))
¬(((s ∨ (v ∧ q)) ∧ ¬((s ∨ (v ∧ q)))))
¬(((q → (t ∨ s)) ∧ ¬((q → (t ∨ s)))))
¬((((p ∧ v) → u) ∧ ¬(((p ∧ v) → u))))
¬(((p → (q ∨ u)) ∧ ¬((p → (q ∨ u)))))
¬(((v ∨ (s ∧ u)) ∧ ¬((v ∨ (s ∧ u)))))
¬((((p ∧ t) ∧ u) ∧ ¬(((p ∧ t) ∧ u))))
¬(((p → (v ∨ q)) ∧ ¬((p → (v ∨ q)))))
¬((((u ∨ v) ∨ q) ∧ ¬(((u ∨ v) ∨ q))))
¬(((q ∧ (t ∨ p)) ∧ ¬((q ∧ (t ∨ p)))))
¬((((v ∧ s) ∧ q) ∧ ¬(((v ∧ s) ∧ q))))
¬(((q → (p ∨ r)) ∧ ¬((q → (p ∨ r)))))
¬((((t ∧ s) → r) ∧ ¬(((t ∧ s) → r))))
¬(((t ∧ (s ∨ v)) ∧ ¬((t ∧ (s ∨ v)))))
((¬((v ∧ ¬t)) → (v ∧ ¬t)) → (v ∧ ¬t))
((¬((¬u ∨ q)) → (¬u ∨ q)) → (¬u ∨ q))
¬((((u ∨ p) ∨ s) ∧ ¬(((u ∨ p) ∨ s))))
((p ↔ t) → (((p ∨ u) ∨ r) → (p ↔ t)))
(((v ↔ s) ∧ ((q ∨ p) ∨ s)) → (v ↔ s))
(((q → (u ∨ v)) ∧ (r ∧ u)) → (r ∧ u))
((¬s ∨ v) → ((¬s ∨ v) ∨ ((r ∧ u) ∧ s)))
((((s ∨ q) ∨ v) ∧ (¬u ∨ t)) → (¬u ∨ t))
((p ∧ ¬t) → ((r → (v ∨ t)) ∨ (p ∧ ¬t)))
(((v ∧ ¬r) ∧ (u ∧ (p ∨ r))) → (v ∧ ¬r))
(((v ∨ s) ∧ ((s ∧ u) ∧ r)) → ((s ∧ u) ∧ r))
((q → (r ∨ t)) → (t → ((q → (r ∨ t)) ∧ t)))
(((q ∨ r) ∨ p) → ((u ↔ r) ∨ ((q ∨ r) ∨ p)))
(((q ∧ p) → s) → ((p → u) → ((q ∧ p) → s)))
(((s ∨ r) ↔ (s → u)) → ((s ∨ r) → (s → u)))
((q → (r ∨ v)) → ((v ↔ q) ∨ (q → (r ∨ v))))
(((t ∧ v) ∧ q) → ((r ∨ q) → ((t ∧ v) ∧ q)))
(((q ∧ ¬u) ∧ (r ∧ (v ∨ p))) → (r ∧ (v ∨ p)))
(((v ∧ t) → s) → ((¬t ∨ q) → ((v ∧ t) → s)))
(((¬q ∨ p) ∧ ((s ∧ t) → r)) → ((s ∧ t) → r))
(((¬t ∨ v) ∧ ((q ∨ v) ∨ t)) → ((q ∨ v) ∨ t))
(((¬p ∨ t) ∧ (t → (q ∨ p))) → (t → (q ∨ p)))
(((v ↔ s) ∨ ((v ↔ s) ∧ (v ∧ ¬t))) ↔ (v ↔ s))
((q ∨ (s ∧ p)) → ((q ∨ (s ∧ p)) ∨ (t ∧ ¬r)))
((r → (q ∨ p)) → ((¬r ∨ q) → (r → (q ∨ p))))
(((u ∨ v) ∧ ((u ∨ v) ∨ (¬v ∨ q))) ↔ (u ∨ v))
((((u ↔ t) → (¬r ∨ p)) ∧ (u ↔ t)) → (¬r ∨ p))
(((¬t ∨ s) ↔ (¬t ∨ q)) → ((¬t ∨ q) → (¬t ∨ s)))
((r ∧ ¬q) → ((¬v ∨ q) → ((r ∧ ¬q) ∧ (¬v ∨ q))))
((((u ∧ s) ∨ (¬p ∨ q)) ∧ ¬((u ∧ s))) → (¬p ∨ q))
(¬(((u ∧ s) → (t → s))) ↔ ((u ∧ s) ∧ ¬((t → s))))
((((s ∧ p) ∧ v) ∧ (q → (t ∨ r))) → ((s ∧ p) ∧ v))
(((p ∧ q) ∧ s) → (((r ∧ s) ∧ p) ∨ ((p ∧ q) ∧ s)))
((p ∧ (r ∨ u)) → (((t ∧ s) ∧ u) ∨ (p ∧ (r ∨ u))))
(((s ∧ u) → q) → (((s ∧ u) → q) ∨ (p → (u ∨ r))))
(((t ∨ (s ∧ u)) ∧ ((r ∨ s) ∨ p)) → ((r ∨ s) ∨ p))
(((s ∨ u) ∨ p) → (((s ∨ u) ∨ p) ∨ ((v ∧ p) ∧ t)))
(((t → v) ∨ ((t → v) ∧ ((q ∧ t) → u))) ↔ (t → v))
((((p ∨ u) ∨ s) ∧ (t ∧ (q ∨ u))) → ((p ∨ u) ∨ s))
((((s ∨ u) ∨ r) ∨ ((s ∨ u) ∨ r)) ↔ ((s ∨ u) ∨ r))
(((v ∧ (p ∨ u)) ∨ (v ∧ (p ∨ u))) ↔ (v ∧ (p ∨ u)))
(((r ∨ s) ∨ ((r ∨ s) ∧ ((p ∨ t) ∨ s))) ↔ (r ∨ s))
(((s → (v ∨ t)) ∧ (t ∨ (s ∧ u))) → (t ∨ (s ∧ u)))
((p ∧ (u ∨ s)) → ((p ∧ (u ∨ s)) ∨ ((p ∨ v) ∨ s)))
((((v ∨ p) ∨ t) ∧ ((p ∨ v) ∨ q)) → ((v ∨ p) ∨ t))
((((s ∨ v) ∨ r) ∧ (p → (q ∨ u))) → (p → (q ∨ u)))
(((q ∧ p) → r) → (((q ∧ p) → r) ∨ ((s ∨ u) ∨ q)))
((((r ∨ u) ∨ v) ∧ (v ∨ (t ∧ q))) → ((r ∨ u) ∨ v))
(((u ∨ r) ∨ t) → (((r ∧ q) ∧ s) → ((u ∨ r) ∨ t)))
(((p ∧ v) ∧ q) → ((v ∨ (t ∧ r)) → ((p ∧ v) ∧ q)))
(((s → (r ∨ q)) ∧ (s → (r ∨ q))) ↔ (s → (r ∨ q)))
((((p ∧ t) → u) ∨ ((p ∧ t) → u)) ↔ ((p ∧ t) → u))
(((p ∨ (q ∧ t)) ∧ (v → (s ∨ u))) → (p ∨ (q ∧ t)))
(((r ∨ (q ∧ u)) ∧ (q → (u ∨ t))) → (q → (u ∨ t)))
(((s ∨ (t ∧ q)) ∧ (r ∨ (v ∧ t))) → (s ∨ (t ∧ q)))
(((p ∧ q) ∧ r) → (((r ∨ v) ∨ s) → ((p ∧ q) ∧ r)))
((r → (p ∨ s)) → (((r ∨ p) ∨ s) → (r → (p ∨ s))))
(((r ∨ p) ∨ q) → (((r ∨ p) ∨ q) ∨ ((q ∨ u) ∨ s)))
(((s ∧ p) → t) → ((u ∧ (p ∨ q)) → ((s ∧ p) → t)))
((u ∧ (v ∨ p)) → ((v ∨ (p ∧ q)) → (u ∧ (v ∨ p))))
(((u ∧ v) ∧ t) → (((u ∧ v) ∧ t) ∨ ((u ∧ v) → p)))
((v → (s ∨ q)) → ((v → (s ∨ q)) ∨ ((v ∧ p) → r)))
(((t ∨ (p ∧ u)) ∧ ((r ∧ u) ∧ s)) → (t ∨ (p ∧ u)))
(((v ∧ (p ∨ q)) ∧ (u → (s ∨ q))) → (u → (s ∨ q)))
((((q ∧ p) ∧ v) ∧ (u → (p ∨ r))) → ((q ∧ p) ∧ v))
((u ∨ (v ∧ r)) → ((u ∨ (v ∧ r)) ∨ ((p ∧ s) ∧ t)))
((q ∧ (u ∨ p)) → ((q ∧ (u ∨ p)) ∨ (r ∨ (t ∧ p))))
(((r ∨ (u ∧ p)) ∧ (r ∨ (u ∧ p))) ↔ (r ∨ (u ∧ p)))
((((u ∧ v) ∧ s) ∧ ((s ∨ t) ∨ u)) → ((s ∨ t) ∨ u))
(((v ∧ q) ∧ r) → (((s ∧ v) ∧ p) → ((v ∧ q) ∧ r)))
(((t → (q ∨ v)) ∧ (t → (q ∨ v))) ↔ (t → (q ∨ v)))
((((r ∧ u) → q) ∧ ((p ∧ t) → q)) → ((p ∧ t) → q))
(((u ∧ (r ∨ v)) ∧ (r → (q ∨ p))) → (u ∧ (r ∨ v)))
((t ∨ (r ∧ u)) → (((q ∧ r) ∧ s) ∨ (t ∨ (r ∧ u))))
((((u ∧ p) ∧ v) ∧ (r ∨ (v ∧ s))) → ((u ∧ p) ∧ v))
((((p ∧ q) → u) ∧ (q → (v ∨ u))) → (q → (v ∨ u)))
((u ∧ (p ∨ q)) → (((p ∧ q) ∧ v) ∨ (u ∧ (p ∨ q))))
(((q ∧ p) ∧ u) → (((q ∨ v) ∨ s) → ((q ∧ p) ∧ u)))
((v → (q ∨ s)) → ((v → (q ∨ s)) ∨ (u ∨ (q ∧ r))))
(((s → (t ∨ v)) ∧ (u ∧ (t ∨ s))) → (s → (t ∨ v)))
((((v ∧ r) → t) ∧ (t → (p ∨ v))) → (t → (p ∨ v)))
((u ∧ (r ∨ p)) → ((u ∧ (r ∨ p)) ∨ (r ∧ (s ∨ u))))
((q ∧ (t ∨ u)) → ((q ∧ (t ∨ u)) ∨ ((p ∨ t) ∨ s)))
((q ∨ (r ∧ u)) → (((t ∧ s) ∧ q) ∨ (q ∨ (r ∧ u))))
((((p ∧ s) ∧ v) ∧ (u → (v ∨ p))) → (u → (v ∨ p)))
((((p ∨ s) ∨ t) ∨ ((p ∨ s) ∨ t)) ↔ ((p ∨ s) ∨ t))
((s ∧ (u ∨ v)) → ((s ∧ (u ∨ v)) ∨ ((s ∧ r) ∧ q)))
(((r ∧ q) → s) → ((r → (v ∨ u)) → ((r ∧ q) → s)))
(((t ∨ r) ∨ q) → ((u ∧ (s ∨ t)) → ((t ∨ r) ∨ q)))
(((u ∨ (s ∧ q)) ∧ (s ∨ (t ∧ p))) → (s ∨ (t ∧ p)))
((((p ∧ r) ∧ v) ∨ ((p ∧ r) ∧ v)) ↔ ((p ∧ r) ∧ v))
((((r ∨ v) ∨ u) ∨ ((r ∨ v) ∨ u)) ↔ ((r ∨ v) ∨ u))
((u ∨ (p ∧ s)) → ((s ∨ (r ∧ p)) → (u ∨ (p ∧ s))))
(((r ∧ q) → t) → ((q → (p ∨ t)) ∨ ((r ∧ q) → t)))
((((t ∧ s) → u) ∧ ((t ∧ s) → u)) ↔ ((t ∧ s) → u))
((s → (t ∨ v)) → ((s → (t ∨ v)) ∨ (u ∧ (q ∨ p))))
((((q ∧ t) → r) ∧ ((u ∧ s) ∧ t)) → ((q ∧ t) → r))
(((v → (p ∨ u)) ∧ ((v ∧ r) ∧ q)) → (v → (p ∨ u)))
(((s ∨ (v ∧ r)) ∧ (r ∧ (v ∨ u))) → (s ∨ (v ∧ r)))
((t ∨ (r ∧ v)) → (((v ∧ r) → u) → (t ∨ (r ∧ v))))
(((v ∧ (r ∨ u)) ∧ (t ∨ (v ∧ u))) → (t ∨ (v ∧ u)))
((u ∨ (s ∧ t)) → (((u ∧ p) → t) ∨ (u ∨ (s ∧ t))))
((s → (v ∨ u)) → ((s → (v ∨ u)) ∨ ((s ∨ r) ∨ q)))
(((u → (r ∨ v)) ∧ (u ∧ (q ∨ p))) → (u → (r ∨ v)))
((((q ∨ r) ∨ v) ∧ (t ∨ (v ∧ u))) → ((q ∨ r) ∨ v))
(((q ∧ v) ∧ r) → ((r ∨ (p ∧ t)) ∨ ((q ∧ v) ∧ r)))
((((q ∧ v) ∧ p) ∨ ((q ∧ v) ∧ p)) ↔ ((q ∧ v) ∧ p))
((s → (u ∨ r)) → ((p ∧ (s ∨ u)) → (s → (u ∨ r))))
((t → (u ∨ v)) → (((t ∧ u) ∧ r) ∨ (t → (u ∨ v))))
((((p ∧ t) ∧ s) ∧ ((p ∧ t) ∧ s)) ↔ ((p ∧ t) ∧ s))
(((p ∨ u) ∨ t) → (((q ∧ v) → p) ∨ ((p ∨ u) ∨ t)))
((((t ∧ v) → u) ∧ ((t ∨ u) ∨ s)) → ((t ∨ u) ∨ s))
(((q ∧ s) ∧ u) → (((s ∧ q) → r) ∨ ((q ∧ s) ∧ u)))
(((p ∨ (v ∧ r)) ∨ (p ∨ (v ∧ r))) ↔ (p ∨ (v ∧ r)))
((((t ∧ u) → p) ∧ ((p ∨ v) ∨ u)) → ((t ∧ u) → p))
((p ∧ (v ∨ u)) → (((u ∨ p) ∨ s) → (p ∧ (v ∨ u))))
(((q ∨ t) ∨ s) → (((s ∧ q) → t) ∨ ((q ∨ t) ∨ s)))
(((s ∧ v) ∧ u) → ((p → (q ∨ s)) → ((s ∧ v) ∧ u)))
(((r ∨ (u ∧ s)) ∧ (r ∨ (u ∧ s))) ↔ (r ∨ (u ∧ s)))
((t → (r ∨ p)) → ((v ∨ (s ∧ p)) → (t → (r ∨ p))))
((t → (r ∨ q)) → ((q ∨ (r ∧ t)) ∨ (t → (r ∨ q))))
((s ∧ (r ∨ t)) → ((s ∧ (r ∨ t)) ∨ ((q ∧ r) → s)))
((v ∧ (q ∨ s)) → ((v ∧ (q ∨ s)) ∨ (v → (s ∨ r))))
((r → (v ∨ p)) → ((r ∨ (q ∧ t)) → (r → (v ∨ p))))
(((p ∨ (q ∧ s)) ∧ (p ∨ (q ∧ s))) ↔ (p ∨ (q ∧ s)))
((((t ∨ u) ∨ v) ∧ ((r ∨ s) ∨ t)) → ((t ∨ u) ∨ v))
((((r ∧ t) → u) ∧ (r → (q ∨ u))) → ((r ∧ t) → u))
(((r ∨ (v ∧ p)) ∧ ((u ∨ v) ∨ r)) → ((u ∨ v) ∨ r))
((r → (s ∨ q)) → ((r → (s ∨ t)) ∨ (r → (s ∨ q))))
((u ∨ (s ∧ q)) → (((r ∧ s) ∧ q) ∨ (u ∨ (s ∧ q))))
(((s ∧ (p ∨ q)) ∧ ((v ∧ q) ∧ t)) → ((v ∧ q) ∧ t))
((((q ∧ r) ∧ t) ∨ ((q ∧ r) ∧ t)) ↔ ((q ∧ r) ∧ t))
((v ∧ (q ∨ t)) → (((r ∧ p) → v) → (v ∧ (q ∨ t))))
((s ∨ (q ∧ p)) → ((s ∨ (q ∧ p)) ∨ ((v ∧ u) ∧ q)))
(((u ∧ p) → r) → (((u ∧ p) → r) ∨ (p ∧ (v ∨ q))))
((t → (p ∨ q)) → ((t → (p ∨ q)) ∨ (v ∨ (r ∧ u))))
(((q ∨ (v ∧ t)) ∧ ((p ∨ q) ∨ v)) → (q ∨ (v ∧ t)))
((((u ∧ v) → p) ∧ (v ∧ (t ∨ q))) → ((u ∧ v) → p))
((u ∨ (r ∧ t)) → ((u ∨ (r ∧ t)) ∨ ((t ∧ q) ∧ s)))
(((r → v) ∧ ((r → v) ∨ (r ∨ (v ∧ u)))) ↔ (r → v))
((v ∧ (p ∨ t)) → ((v ∧ (p ∨ t)) ∨ ((v ∧ t) → r)))
((p ∨ (q ∧ v)) → ((p ∨ (q ∧ v)) ∨ ((q ∧ s) → t)))
((((u ∧ t) → v) ∧ (p → (t ∨ q))) → ((u ∧ t) → v))
(((p ∨ (v ∧ t)) ∧ (p ∨ (v ∧ t))) ↔ (p ∨ (v ∧ t)))
((((v ∧ p) ∧ r) ∧ ((t ∧ p) ∧ s)) → ((t ∧ p) ∧ s))
((((t ∧ q) → s) ∧ (p → (r ∨ s))) → (p → (r ∨ s)))
(((v ∧ s) ∧ u) → (((v ∧ s) ∧ u) ∨ (u ∨ (q ∧ s))))
(¬((((v ∨ r) ∨ p) ∨ t)) ↔ (¬(((v ∨ r) ∨ p)) ∧ ¬t))
((((s ∧ p) → (¬r ∨ u)) ∧ ¬((¬r ∨ u))) → ¬((s ∧ p)))
((¬(((u ∨ v) ∨ p)) → ((u ∨ v) ∨ p)) → ((u ∨ v) ∨ p))
((¬(((s ∨ q) ∨ t)) → ((s ∨ q) ∨ t)) → ((s ∨ q) ∨ t))
((¬(((q ∨ v) ∨ t)) → ((q ∨ v) ∨ t)) → ((q ∨ v) ∨ t))
(((v ∧ ¬t) ∧ ((v ∧ ¬t) ∨ (q ∧ (s ∨ p)))) ↔ (v ∧ ¬t))
((¬((p ∨ (q ∧ u))) → (p ∨ (q ∧ u))) → (p ∨ (q ∧ u)))
((¬((t → (v ∨ u))) → (t → (v ∨ u))) → (t → (v ∨ u)))
(((((t ∧ q) ∧ v) → (q ↔ s)) ∧ ((t ∧ q) ∧ v)) → (q ↔ s))
(((v → (u ∨ t)) ∧ (t → p)) → ((t → p) ∧ (v → (u ∨ t))))
(((((r ∧ u) → q) → (s ∨ t)) ∧ ((r ∧ u) → q)) → (s ∨ t))
((((q → (v ∨ s)) → (u → t)) ∧ (q → (v ∨ s))) → (u → t))
(((s ∧ q) ↔ (q ∧ (s ∨ t))) → ((s ∧ q) → (q ∧ (s ∨ t))))
(((q → u) ∧ (q ∧ (r ∨ v))) → ((q ∧ (r ∨ v)) ∧ (q → u)))
(((t → u) ↔ (p → (q ∨ s))) → ((t → u) → (p → (q ∨ s))))
((((s ∨ q) ∨ p) ∨ (t ∨ v)) → ((t ∨ v) ∨ ((s ∨ q) ∨ p)))
(((t ∨ (q ∧ r)) ↔ (s ↔ q)) → ((s ↔ q) → (t ∨ (q ∧ r))))
((((u ↔ r) → (p → (u ∨ s))) ∧ (u ↔ r)) → (p → (u ∨ s)))
(((t ∨ u) ∨ (v ∧ (r ∨ s))) → ((v ∧ (r ∨ s)) ∨ (t ∨ u)))
(((q → v) ↔ (s ∨ (q ∧ t))) → ((s ∨ (q ∧ t)) → (q → v)))
(((((r ∨ s) ∨ v) → (s ∨ q)) ∧ ((r ∨ s) ∨ v)) → (s ∨ q))
((t ∧ (s ∨ u)) → ((q → t) → ((t ∧ (s ∨ u)) ∧ (q → t))))
((t ∨ r) → ((p ∨ (t ∧ q)) → ((t ∨ r) ∧ (p ∨ (t ∧ q)))))
(((u ∧ (v ∨ t)) ∧ (u → r)) → ((u → r) ∧ (u ∧ (v ∨ t))))
(((p ∧ u) → r) → ((q ↔ t) → (((p ∧ u) → r) ∧ (q ↔ t))))
(((r ∧ v) ↔ ((s ∧ p) ∧ t)) → ((r ∧ v) → ((s ∧ p) ∧ t)))
(((u ∨ p) ↔ ((p ∨ q) ∨ r)) → (((p ∨ q) ∨ r) → (u ∨ p)))
((((r ∧ q) ∧ s) ↔ (s → v)) → (((r ∧ q) ∧ s) → (s → v)))
(((v ∧ (r ∨ t)) ↔ (t ↔ v)) → ((t ↔ v) → (v ∧ (r ∨ t))))
((((s ∧ v) ∧ r) ∨ (t ∧ r)) → ((t ∧ r) ∨ ((s ∧ v) ∧ r)))
((((r ∧ t) ∧ s) ↔ (p ↔ t)) → (((r ∧ t) ∧ s) → (p ↔ t)))
(((u → v) ↔ (r ∧ (p ∨ s))) → ((u → v) → (r ∧ (p ∨ s))))
((((q ∧ u) ∧ s) ∧ (s ∨ v)) → ((s ∨ v) ∧ ((q ∧ u) ∧ s)))
(((r → s) ∧ (u → (p ∨ t))) → ((u → (p ∨ t)) ∧ (r → s)))
(((t → (u ∨ q)) ∨ (r ↔ s)) → ((r ↔ s) ∨ (t → (u ∨ q))))
(((((s ∧ v) ∧ u) → (s ↔ r)) ∧ ((s ∧ v) ∧ u)) → (s ↔ r))
((((v ∧ s) → t) ∧ (((v ∧ s) → t) ∨ ¬s)) ↔ ((v ∧ s) → t))
((((s ∧ ¬u) → ((v ∧ t) → r)) ∧ (s ∧ ¬u)) → ((v ∧ t) → r))
((((s ∧ ¬u) → (t ∨ (u ∧ r))) ∧ (s ∧ ¬u)) → (t ∨ (u ∧ r)))
(((t ∧ q) ∧ r) → ((v ∧ ¬t) → (((t ∧ q) ∧ r) ∧ (v ∧ ¬t))))
((((¬s ∨ p) → (s ∨ (q ∧ t))) ∧ (¬s ∨ p)) → (s ∨ (q ∧ t)))
((s ∧ ¬u) → (((s ∧ p) → u) → ((s ∧ ¬u) ∧ ((s ∧ p) → u))))
(((r ∨ v) ∨ t) → ((r ∧ ¬q) → (((r ∨ v) ∨ t) ∧ (r ∧ ¬q))))
(((¬r ∨ s) ↔ (s ∨ (q ∧ r))) → ((s ∨ (q ∧ r)) → (¬r ∨ s)))
(((q ∧ ¬v) ∨ (r ∨ (s ∧ v))) → ((r ∨ (s ∧ v)) ∨ (q ∧ ¬v)))
(((u ∧ ¬r) ∧ ((t ∧ r) → s)) → (((t ∧ r) → s) ∧ (u ∧ ¬r)))
(((t ∨ s) ∨ u) → ((¬t ∨ r) → (((t ∨ s) ∨ u) ∧ (¬t ∨ r))))
(((p ∧ ¬u) ↔ (p ∧ (t ∨ q))) → ((p ∧ (t ∨ q)) → (p ∧ ¬u)))
((r ∨ (p ∧ v)) → ((¬t ∨ r) → ((r ∨ (p ∧ v)) ∧ (¬t ∨ r))))
((((p ∧ ¬r) → ((s ∨ r) ∨ q)) ∧ (p ∧ ¬r)) → ((s ∨ r) ∨ q))
((¬v ∨ s) → ((s → (p ∨ u)) → ((¬v ∨ s) ∧ (s → (p ∨ u)))))
((((t ↔ s) ∨ (u → (q ∨ v))) ∧ ¬((t ↔ s))) → (u → (q ∨ v)))
(((((s ∧ t) ∧ u) ∨ (u ↔ v)) ∧ ¬((u ↔ v))) → ((s ∧ t) ∧ u))
((((p ∧ q) → v) → (t ∨ u)) ↔ (¬(((p ∧ q) → v)) ∨ (t ∨ u)))
((((t ∨ r) ∨ (p ∨ (t ∧ q))) ∧ ¬((p ∨ (t ∧ q)))) → (t ∨ r))
((((r ∨ v) ∨ (p → (s ∨ q))) ∧ ¬((r ∨ v))) → (p → (s ∨ q)))
(((v → (s ∨ t)) → (t ↔ u)) ↔ (¬((v → (s ∨ t))) ∨ (t ↔ u)))
((((s ∨ q) ∨ ((v ∧ s) → p)) ∧ ¬(((v ∧ s) → p))) → (s ∨ q))
((((r ∧ u) → v) → (t ∨ q)) ↔ (¬(((r ∧ u) → v)) ∨ (t ∨ q)))
(((((s ∧ u) → q) ∨ (r ↔ p)) ∧ ¬((r ↔ p))) → ((s ∧ u) → q))
(((t ∧ s) → ((t ∨ s) ∨ p)) ↔ (¬((t ∧ s)) ∨ ((t ∨ s) ∨ p)))
((((t ∨ (v ∧ u)) ∨ (u ∨ v)) ∧ ¬((u ∨ v))) → (t ∨ (v ∧ u)))
(((p ∨ (q ∧ v)) → (v ∧ ¬t)) ↔ (¬((p ∨ (q ∧ v))) ∨ (v ∧ ¬t)))
((((¬p ∨ u) ∨ (q ∨ (v ∧ p))) ∧ ¬((¬p ∨ u))) → (q ∨ (v ∧ p)))
(((q ∧ ¬v) → (r ∨ (t ∧ u))) ↔ (¬((q ∧ ¬v)) ∨ (r ∨ (t ∧ u))))
((((s ∧ (q ∨ u)) ∨ (¬v ∨ u)) ∧ ¬((¬v ∨ u))) → (s ∧ (q ∨ u)))
((((¬u ∨ v) ∨ ((q ∧ p) ∧ t)) ∧ ¬(((q ∧ p) ∧ t))) → (¬u ∨ v))
((((¬u ∨ p) ∨ ((u ∧ s) ∧ p)) ∧ ¬(((u ∧ s) ∧ p))) → (¬u ∨ p))
((((u → (p ∨ r)) ∨ (¬u ∨ r)) ∧ ¬((u → (p ∨ r)))) → (¬u ∨ r))
(((p ↔ q) → (t → (s ∨ u))) → (¬((t → (s ∨ u))) → ¬((p ↔ q))))
(((r → p) → ((u ∨ r) ∨ s)) → (¬(((u ∨ r) ∨ s)) → ¬((r → p))))
((¬((u → s)) → ¬((v ∧ (u ∨ q)))) → ((v ∧ (u ∨ q)) → (u → s)))
(((s ∧ r) → (p ∨ (r ∧ u))) → (¬((p ∨ (r ∧ u))) → ¬((s ∧ r))))
((¬((r ∨ p)) → ¬((t ∨ (s ∧ u)))) → ((t ∨ (s ∧ u)) → (r ∨ p)))
(¬((((v ∨ s) ∨ t) → (u ↔ q))) ↔ (((v ∨ s) ∨ t) ∧ ¬((u ↔ q))))
((¬(((q ∧ p) → t)) → ¬((s → r))) → ((s → r) → ((q ∧ p) → t)))
((((u ∨ t) ∨ s) → (p ↔ s)) → (¬((p ↔ s)) → ¬(((u ∨ t) ∨ s))))
(¬(((s ∧ u) → ((r ∧ s) ∧ u))) ↔ ((s ∧ u) ∧ ¬(((r ∧ s) ∧ u))))
(((s ∧ (p ∨ t)) ↔ (p → v)) → (¬((s ∧ (p ∨ t))) ↔ ¬((p → v))))
((((v ∧ t) ∧ p) → (t ∨ p)) → (¬((t ∨ p)) → ¬(((v ∧ t) ∧ p))))
(¬(((q → u) → ((p ∨ t) ∨ u))) ↔ ((q → u) ∧ ¬(((p ∨ t) ∨ u))))
((¬(((v ∧ q) ∧ t)) → ¬((v ∧ u))) → ((v ∧ u) → ((v ∧ q) ∧ t)))
((((p ∧ t) → s) ↔ (t ∨ v)) → (¬(((p ∧ t) → s)) ↔ ¬((t ∨ v))))
(((v ∧ (q ∨ p)) → (t → s)) → (¬((t → s)) → ¬((v ∧ (q ∨ p)))))
(((u → v) → (v ∧ (p ∨ t))) → (¬((v ∧ (p ∨ t))) → ¬((u → v))))
((((t ↔ p) → ((t ∧ p) ∧ s)) ∧ ¬(((t ∧ p) ∧ s))) → ¬((t ↔ p)))
((((s ∨ v) ∨ t) → (s ∧ v)) → (¬((s ∧ v)) → ¬(((s ∨ v) ∨ t))))
((¬((s → v)) → ¬((v ∨ (p ∧ q)))) → ((v ∨ (p ∧ q)) → (s → v)))
((((q ∧ p) ∧ u) ∨ (((q ∧ p) ∧ u) ∧ (s → p))) ↔ ((q ∧ p) ∧ u))
(((u ∨ (v ∧ r)) ∨ ((u ∨ (v ∧ r)) ∧ (v → t))) ↔ (u ∨ (v ∧ r)))
((((t ∨ q) ∨ s) ∧ (((t ∨ q) ∨ s) ∨ (s ∨ u))) ↔ ((t ∨ q) ∨ s))
((((p ∧ q) ∧ s) ∧ (((p ∧ q) ∧ s) ∨ (s ∨ v))) ↔ ((p ∧ q) ∧ s))
(((v ∨ (p ∧ r)) ∨ ((v ∨ (p ∧ r)) ∧ (s → u))) ↔ (v ∨ (p ∧ r)))
(((u → (r ∨ v)) ∨ ((u → (r ∨ v)) ∧ (q → u))) ↔ (u → (r ∨ v)))
((((s ∧ u) ∧ p) ∨ (((s ∧ u) ∧ p) ∧ (u ∨ q))) ↔ ((s ∧ u) ∧ p))
((((r ∧ u) → v) ∧ (((r ∧ u) → v) ∨ (s ∧ ¬t))) ↔ ((r ∧ u) → v))
((((t ∧ s) ∧ q) ∧ (((t ∧ s) ∧ q) ∨ (s ∧ ¬r))) ↔ ((t ∧ s) ∧ q))
(((¬s ∨ p) → ((v ∧ u) ∧ s)) → (¬(((v ∧ u) ∧ s)) → ¬((¬s ∨ p))))
(¬(((¬p ∨ q) → (q ∨ (v ∧ p)))) ↔ ((¬p ∨ q) ∧ ¬((q ∨ (v ∧ p)))))
(¬(((q ∧ ¬t) → ((p ∨ r) ∨ u))) ↔ ((q ∧ ¬t) ∧ ¬(((p ∨ r) ∨ u))))
((((t ∧ p) → r) → (¬q ∨ u)) → (¬((¬q ∨ u)) → ¬(((t ∧ p) → r))))
(¬((((q ∧ v) ∧ t) ∨ (t ∧ v))) ↔ (¬(((q ∧ v) ∧ t)) ∧ ¬((t ∧ v))))
(¬(((s ↔ q) ∨ (t ∧ (u ∨ p)))) ↔ (¬((s ↔ q)) ∧ ¬((t ∧ (u ∨ p)))))
(¬(((s ∧ (r ∨ u)) ∨ (r ∨ u))) ↔ (¬((s ∧ (r ∨ u))) ∧ ¬((r ∨ u))))
(¬(((v ∨ (q ∧ s)) ∧ (s ∧ ¬t))) ↔ (¬((v ∨ (q ∧ s))) ∨ ¬((s ∧ ¬t))))
(¬(((¬u ∨ s) ∨ (p ∧ (s ∨ v)))) ↔ (¬((¬u ∨ s)) ∧ ¬((p ∧ (s ∨ v)))))
(¬(((s ∧ ¬p) ∧ ((r ∨ v) ∨ p))) ↔ (¬((s ∧ ¬p)) ∨ ¬(((r ∨ v) ∨ p))))
(¬((((u ∧ s) ∧ q) ∨ (s ∧ ¬q))) ↔ (¬(((u ∧ s) ∧ q)) ∧ ¬((s ∧ ¬q))))
(¬(((¬p ∨ r) ∨ ((v ∨ q) ∨ s))) ↔ (¬((¬p ∨ r)) ∧ ¬(((v ∨ q) ∨ s))))
(¬((((q ∧ u) ∧ v) ∨ (¬r ∨ s))) ↔ (¬(((q ∧ u) ∧ v)) ∧ ¬((¬r ∨ s))))
((((t ∧ r) ∧ u) ∨ (((t ∧ r) ∧ u) ∧ (t → (p ∨ q)))) ↔ ((t ∧ r) ∧ u))
((u → (r ∨ t)) → (((u ∧ t) ∧ s) → ((u → (r ∨ t)) ∧ ((u ∧ t) ∧ s))))
((((r ∧ s) ∧ p) ∧ (((r ∧ s) ∧ p) ∨ ((t ∨ u) ∨ v))) ↔ ((r ∧ s) ∧ p))
(((s ∧ (p ∨ v)) ∧ (t ∨ (s ∧ r))) → ((t ∨ (s ∧ r)) ∧ (s ∧ (p ∨ v))))
((((t ∧ u) → q) ∧ ((t ∧ p) ∧ q)) → (((t ∧ p) ∧ q) ∧ ((t ∧ u) → q)))
((((u ∧ t) → r) ↔ (s → (p ∨ u))) → (((u ∧ t) → r) → (s → (p ∨ u))))
(((s ∧ (q ∨ t)) ∧ ((s ∧ (q ∨ t)) ∨ (r → (s ∨ v)))) ↔ (s ∧ (q ∨ t)))
((((v ∨ p) ∨ t) ↔ (s → (t ∨ v))) → ((s → (t ∨ v)) → ((v ∨ p) ∨ t)))
(((v ∨ (s ∧ u)) ∨ ((u ∨ p) ∨ s)) → (((u ∨ p) ∨ s) ∨ (v ∨ (s ∧ u))))
(((s ∨ t) ∨ u) → (((r ∧ s) ∧ t) → (((s ∨ t) ∨ u) ∧ ((r ∧ s) ∧ t))))
(((((t ∧ q) → r) → (q ∨ (t ∧ r))) ∧ ((t ∧ q) → r)) → (q ∨ (t ∧ r)))
((((u ∧ v) → q) ∨ ((s ∧ t) ∧ r)) → (((s ∧ t) ∧ r) ∨ ((u ∧ v) → q)))
((((q ∧ s) → p) ∨ (((q ∧ s) → p) ∧ ((v ∧ r) → q))) ↔ ((q ∧ s) → p))
((((p ∧ (t ∨ s)) → (s → (q ∨ u))) ∧ (p ∧ (t ∨ s))) → (s → (q ∨ u)))
((((s ∨ r) ∨ t) ∧ (r ∨ (s ∧ t))) → ((r ∨ (s ∧ t)) ∧ ((s ∨ r) ∨ t)))
(((v ∧ (p ∨ u)) ∧ ((v ∧ (p ∨ u)) ∨ ((s ∧ p) → t))) ↔ (v ∧ (p ∨ u)))
((((q ∨ u) ∨ t) ∨ ((q ∧ r) ∧ p)) → (((q ∧ r) ∧ p) ∨ ((q ∨ u) ∨ t)))
((((r ∨ t) ∨ u) ∨ (p ∧ (q ∨ r))) → ((p ∧ (q ∨ r)) ∨ ((r ∨ t) ∨ u)))
((((s ∧ r) ∧ u) ↔ ((v ∧ s) → t)) → (((v ∧ s) → t) → ((s ∧ r) ∧ u)))
(((u → (s ∨ v)) ∨ ((t ∧ u) ∧ s)) → (((t ∧ u) ∧ s) ∨ (u → (s ∨ v))))
((((p ∧ (q ∨ t)) → (t → (q ∨ u))) ∧ (p ∧ (q ∨ t))) → (t → (q ∨ u)))
((((t ∧ r) ∧ q) ↔ ((v ∧ s) → t)) → (((t ∧ r) ∧ q) → ((v ∧ s) → t)))
(((s ∧ (t ∨ r)) ∧ ((s ∧ (t ∨ r)) ∨ ((s ∨ u) ∨ t))) ↔ (s ∧ (t ∨ r)))
(((q ∧ (r ∨ t)) ∧ ((q ∧ (r ∨ t)) ∨ ((v ∧ r) ∧ u))) ↔ (q ∧ (r ∨ t)))
((((v ∨ p) ∨ s) ∨ (((v ∨ p) ∨ s) ∧ ((q ∧ r) → p))) ↔ ((v ∨ p) ∨ s))
((((q ∧ p) ∧ u) ∨ (((q ∧ p) ∧ u) ∧ ((r ∨ q) ∨ t))) ↔ ((q ∧ p) ∧ u))
(((s ∨ (q ∧ t)) ↔ (v ∨ (u ∧ r))) → ((s ∨ (q ∧ t)) → (v ∨ (u ∧ r))))
((((u ∧ r) → s) ∧ (((u ∧ r) → s) ∨ ((p ∨ t) ∨ u))) ↔ ((u ∧ r) → s))
(((((t ∧ q) → r) → ((r ∧ q) → p)) ∧ ((t ∧ q) → r)) → ((r ∧ q) → p))
(((q → (u ∨ t)) ↔ ((p ∧ r) → t)) → ((q → (u ∨ t)) → ((p ∧ r) → t)))
((((q ∨ r) ∨ t) ∧ (((q ∨ r) ∨ t) ∨ ((v ∧ r) ∧ u))) ↔ ((q ∨ r) ∨ t))
(((((t ∨ v) ∨ s) → (t ∧ (v ∨ s))) ∧ ((t ∨ v) ∨ s)) → (t ∧ (v ∨ s)))
((((s ∧ q) ∧ t) ↔ ((t ∧ q) → v)) → (((s ∧ q) ∧ t) → ((t ∧ q) → v)))
(((s ∧ (q ∨ u)) ↔ (v ∧ (u ∨ r))) → ((s ∧ (q ∨ u)) → (v ∧ (u ∨ r))))
((((v ∧ r) → u) ∨ (((v ∧ r) → u) ∧ ((u ∧ q) → r))) ↔ ((v ∧ r) → u))
(((p ∧ (u ∨ t)) ↔ ((p ∨ r) ∨ v)) → ((p ∧ (u ∨ t)) → ((p ∨ r) ∨ v)))
(((r ∧ (t ∨ u)) ∧ ((v ∧ s) → p)) → (((v ∧ s) → p) ∧ (r ∧ (t ∨ u))))
((((q ∨ t) ∨ r) ∨ (u → (p ∨ r))) → ((u → (p ∨ r)) ∨ ((q ∨ t) ∨ r)))
(((r ∧ (s ∨ v)) ↔ ((r ∧ u) → t)) → (((r ∧ u) → t) → (r ∧ (s ∨ v))))
((((p ∧ (r ∨ t)) → (p → (t ∨ r))) ∧ (p ∧ (r ∨ t))) → (p → (t ∨ r)))
((((p ∨ t) ∨ r) ∧ (u ∧ (v ∨ r))) → ((u ∧ (v ∨ r)) ∧ ((p ∨ t) ∨ r)))
(((v ∧ (u ∨ r)) ∨ ((s ∨ r) ∨ q)) → (((s ∨ r) ∨ q) ∨ (v ∧ (u ∨ r))))
((((r → (u ∨ v)) → (p → (s ∨ q))) ∧ (r → (u ∨ v))) → (p → (s ∨ q)))
((((s ∧ v) ∧ r) ∧ (q → (p ∨ t))) → ((q → (p ∨ t)) ∧ ((s ∧ v) ∧ r)))
((((v ∧ u) → s) ∧ (s ∨ (t ∧ p))) → ((s ∨ (t ∧ p)) ∧ ((v ∧ u) → s)))
((((u ∨ (s ∧ p)) → ((t ∧ v) → s)) ∧ (u ∨ (s ∧ p))) → ((t ∧ v) → s))
((p ∧ (v ∨ s)) → (((r ∧ q) ∧ t) → ((p ∧ (v ∨ s)) ∧ ((r ∧ q) ∧ t))))
(((u → (r ∨ s)) ↔ (q ∧ (p ∨ u))) → ((q ∧ (p ∨ u)) → (u → (r ∨ s))))
((((r ∨ s) ∨ p) ∨ (((r ∨ s) ∨ p) ∧ (p ∨ (v ∧ q)))) ↔ ((r ∨ s) ∨ p))
(((u → (v ∨ q)) ∧ ((u → (v ∨ q)) ∨ (p → (u ∨ q)))) ↔ (u → (v ∨ q)))
(((s ∧ v) → t) → ((r ∧ (q ∨ u)) → (((s ∧ v) → t) ∧ (r ∧ (q ∨ u)))))
(((q ∧ r) → v) → (((p ∧ s) ∧ r) → (((q ∧ r) → v) ∧ ((p ∧ s) ∧ r))))
((((r ∨ u) ∨ s) ∨ (r → (t ∨ v))) → ((r → (t ∨ v)) ∨ ((r ∨ u) ∨ s)))
(((r ∨ (u ∧ q)) ∨ ((r ∧ q) ∧ v)) → (((r ∧ q) ∧ v) ∨ (r ∨ (u ∧ q))))
(((v ∧ (t ∨ u)) ∨ ((v ∧ (t ∨ u)) ∧ ((p ∧ r) ∧ t))) ↔ (v ∧ (t ∨ u)))
((((r ∨ (p ∧ s)) → ((r ∧ q) ∧ p)) ∧ (r ∨ (p ∧ s))) → ((r ∧ q) ∧ p))
(((((s ∨ r) ∨ p) → (u ∧ (t ∨ q))) ∧ ((s ∨ r) ∨ p)) → (u ∧ (t ∨ q)))
((s ∨ (t ∧ p)) → (((s ∧ r) → v) → ((s ∨ (t ∧ p)) ∧ ((s ∧ r) → v))))
((((p ∨ (q ∧ v)) → (s ∧ (r ∨ p))) → (p ∨ (q ∧ v))) → (p ∨ (q ∧ v)))
((((s ∧ u) → v) ∨ (s ∨ (v ∧ u))) → ((s ∨ (v ∧ u)) ∨ ((s ∧ u) → v)))
(((s → (q ∨ v)) ↔ ((t ∧ p) ∧ r)) → ((s → (q ∨ v)) → ((t ∧ p) ∧ r)))
((((u → (r ∨ p)) → (u ∨ (t ∧ q))) ∧ (u → (r ∨ p))) → (u ∨ (t ∧ q)))
((((v ∧ u) → t) ∨ (((v ∧ u) → t) ∧ ((t ∧ q) ∧ s))) ↔ ((v ∧ u) → t))
((((t ∧ u) → s) ∧ (((t ∧ u) → s) ∨ ((r ∨ t) ∨ v))) ↔ ((t ∧ u) → s))
(((v ∨ (p ∧ t)) ∧ ((v ∨ (p ∧ t)) ∨ (v ∧ (u ∨ q)))) ↔ (v ∨ (p ∧ t)))
((((s ∧ t) ∧ p) ↔ ((v ∧ r) → u)) → (((v ∧ r) → u) → ((s ∧ t) ∧ p)))
(((((t ∨ r) ∨ q) → (p ∧ (q ∨ t))) ∧ ((t ∨ r) ∨ q)) → (p ∧ (q ∨ t)))
(((p → (t ∨ u)) ∧ ((p → (t ∨ u)) ∨ (q ∨ (u ∧ r)))) ↔ (p → (t ∨ u)))
((((t ∧ (p ∨ v)) → (r ∧ (p ∨ s))) ∧ (t ∧ (p ∨ v))) → (r ∧ (p ∨ s)))
(((((p ∧ q) ∧ r) → (p ∨ (q ∧ u))) ∧ ((p ∧ q) ∧ r)) → (p ∨ (q ∧ u)))
(((q ∨ p) ∨ s) → (((v ∨ s) ∨ u) → (((q ∨ p) ∨ s) ∧ ((v ∨ s) ∨ u))))
(((u ∧ (r ∨ p)) ↔ (t ∨ (s ∧ r))) → ((u ∧ (r ∨ p)) → (t ∨ (s ∧ r))))
(((v ∧ (r ∨ p)) ∧ ((v ∧ (r ∨ p)) ∨ (r ∧ (v ∨ q)))) ↔ (v ∧ (r ∨ p)))
((((u ∨ r) ∨ v) ↔ (q ∧ (v ∨ r))) → ((q ∧ (v ∨ r)) → ((u ∨ r) ∨ v)))
(((q → (r ∨ t)) ∧ ((q → (r ∨ t)) ∨ ((r ∧ q) ∧ t))) ↔ (q → (r ∨ t)))
((((t ∧ (q ∨ s)) → ((q ∧ t) → r)) ∧ (t ∧ (q ∨ s))) → ((q ∧ t) → r))
((((p ∧ u) ∧ v) ∨ ((t ∧ s) → r)) → (((t ∧ s) → r) ∨ ((p ∧ u) ∧ v)))
((((s ∧ (t ∨ q)) → ((p ∨ s) ∨ v)) ∧ (s ∧ (t ∨ q))) → ((p ∨ s) ∨ v))
(((v ∧ (u ∨ t)) ∨ ((v ∧ (u ∨ t)) ∧ ((p ∨ s) ∨ u))) ↔ (v ∧ (u ∨ t)))
(((u ↔ (q → (t ∨ s))) ∧ ((q → (t ∨ s)) ↔ (v ↔ q))) → (u ↔ (v ↔ q)))
((v ∧ (p ∨ u)) → (((u ∧ r) → q) → ((v ∧ (p ∨ u)) ∧ ((u ∧ r) → q))))
((((s ∧ p) ∧ q) ∧ (((s ∧ p) ∧ q) ∨ ((s ∧ u) ∧ t))) ↔ ((s ∧ p) ∧ q))
((((r ∧ q) ∧ t) ↔ ((r ∧ t) → q)) → (((r ∧ t) → q) → ((r ∧ q) ∧ t)))
(((r ∧ (q ∨ s)) ∨ ((v ∨ s) ∨ p)) → (((v ∨ s) ∨ p) ∨ (r ∧ (q ∨ s))))
(((u ∧ (t ∨ q)) ∨ ((q ∨ t) ∨ v)) → (((q ∨ t) ∨ v) ∨ (u ∧ (t ∨ q))))
(((((p ∧ v) ∧ u) → (t ∨ (q ∧ p))) ∧ ((p ∧ v) ∧ u)) → (t ∨ (q ∧ p)))
(((((q ∧ p) → u) → (u ∨ (t ∧ v))) → ((q ∧ p) → u)) → ((q ∧ p) → u))
(((s → (v ∨ r)) ↔ (u ∨ (r ∧ t))) → ((u ∨ (r ∧ t)) → (s → (v ∨ r))))
(((q ∧ (t ∨ u)) ∨ ((u ∧ t) → r)) → (((u ∧ t) → r) ∨ (q ∧ (t ∨ u))))
(((v ∨ (t ∧ p)) ∧ ((v ∨ (t ∧ p)) ∨ (t → (s ∨ v)))) ↔ (v ∨ (t ∧ p)))
((((v → (t ∨ q)) → ((u ∨ v) ∨ p)) ∧ (v → (t ∨ q))) → ((u ∨ v) ∨ p))
((((s ∨ r) ∨ t) ∧ (((s ∨ r) ∨ t) ∨ (p ∨ (u ∧ r)))) ↔ ((s ∨ r) ∨ t))
(((q ∧ p) ∧ t) → ((p ∧ (q ∨ r)) → (((q ∧ p) ∧ t) ∧ (p ∧ (q ∨ r)))))
(((r ∧ (u ∨ s)) ↔ (u ∧ (p ∨ t))) → ((r ∧ (u ∨ s)) → (u ∧ (p ∨ t))))
(((v ∧ (s ∨ q)) ∨ ((t ∧ r) → p)) → (((t ∧ r) → p) ∨ (v ∧ (s ∨ q))))
(((u → (p ∨ t)) ∨ ((p ∨ r) ∨ u)) → (((p ∨ r) ∨ u) ∨ (u → (p ∨ t))))
(((q ∧ (v ∨ r)) ↔ (r ∧ (s ∨ v))) → ((r ∧ (s ∨ v)) → (q ∧ (v ∨ r))))
(((q ∨ u) ∨ t) → (((r ∧ p) ∧ v) → (((q ∨ u) ∨ t) ∧ ((r ∧ p) ∧ v))))
(((((q ∨ u) ∨ s) → (s ∧ (t ∨ u))) → ((q ∨ u) ∨ s)) → ((q ∨ u) ∨ s))
(((t ∨ (q ∧ u)) ∧ ((p ∨ s) ∨ u)) → (((p ∨ s) ∨ u) ∧ (t ∨ (q ∧ u))))
((r ∧ (q ∨ p)) → (((v ∨ p) ∨ u) → ((r ∧ (q ∨ p)) ∧ ((v ∨ p) ∨ u))))
(((s ∨ (q ∧ r)) ∧ ((t ∧ q) ∧ v)) → (((t ∧ q) ∧ v) ∧ (s ∨ (q ∧ r))))
(((¬u ∨ r) → (u → (r ∧ (p ∨ t)))) → (((¬u ∨ r) ∧ u) → (r ∧ (p ∨ t))))
((((v ∨ (p ∧ t)) ∨ (u ∨ (q ∧ v))) ∧ ¬((v ∨ (p ∧ t)))) → (u ∨ (q ∧ v)))
(((((r ∧ t) ∧ p) ∨ ((v ∧ q) → u)) ∧ ¬(((v ∧ q) → u))) → ((r ∧ t) ∧ p))
(((((u ∨ s) ∨ v) → (r ∨ v)) ∧ (¬(((u ∨ s) ∨ v)) → (r ∨ v))) → (r ∨ v))
((((r → (v ∨ t)) ∨ ((r ∧ u) → q)) ∧ ¬((r → (v ∨ t)))) → ((r ∧ u) → q))
(((((u ∧ q) ∧ r) ∨ (r → (v ∨ s))) ∧ ¬((r → (v ∨ s)))) → ((u ∧ q) ∧ r))
(((((t ∨ p) ∨ q) ∨ ((t ∧ p) ∧ u)) ∧ ¬(((t ∨ p) ∨ q))) → ((t ∧ p) ∧ u))
(((((p ∧ u) → r) ∨ ((p ∧ t) → s)) ∧ ¬(((p ∧ t) → s))) → ((p ∧ u) → r))
((((u ∨ (r ∧ s)) ∨ (r → (q ∨ p))) ∧ ¬((r → (q ∨ p)))) → (u ∨ (r ∧ s)))
(((t ∧ (q ∨ p)) → (v ∧ (u ∨ q))) ↔ (¬((t ∧ (q ∨ p))) ∨ (v ∧ (u ∨ q))))
((((u ∧ (r ∨ s)) ∨ ((u ∧ t) → v)) ∧ ¬((u ∧ (r ∨ s)))) → ((u ∧ t) → v))
(((((s ∧ v) ∧ u) ∨ ((q ∧ u) → s)) ∧ ¬(((s ∧ v) ∧ u))) → ((q ∧ u) → s))
(((((u ∧ t) → s) ∨ (v ∨ (p ∧ q))) ∧ ¬((v ∨ (p ∧ q)))) → ((u ∧ t) → s))
((((r ∧ (t ∨ u)) ∨ ((v ∧ q) ∧ p)) ∧ ¬(((v ∧ q) ∧ p))) → (r ∧ (t ∨ u)))
((((v ∨ (u ∧ p)) ∨ ((s ∨ v) ∨ q)) ∧ ¬(((s ∨ v) ∨ q))) → (v ∨ (u ∧ p)))
((((s → (u ∨ v)) ∨ (r ∧ (u ∨ t))) ∧ ¬((r ∧ (u ∨ t)))) → (s → (u ∨ v)))
(((((p ∧ q) ∧ v) ∨ (r → (u ∨ q))) ∧ ¬(((p ∧ q) ∧ v))) → (r → (u ∨ q)))
(((((p ∨ t) ∨ v) ∨ (p ∨ (t ∧ u))) ∧ ¬((p ∨ (t ∧ u)))) → ((p ∨ t) ∨ v))
((((q → (u ∨ t)) ∨ (r → (p ∨ u))) ∧ ¬((r → (p ∨ u)))) → (q → (u ∨ t)))
((((p ∨ (s ∧ r)) ∨ ((p ∨ u) ∨ s)) ∧ ¬((p ∨ (s ∧ r)))) → ((p ∨ u) ∨ s))
(((((q ∧ t) ∧ s) ∨ (s → (r ∨ v))) ∧ ¬((s → (r ∨ v)))) → ((q ∧ t) ∧ s))
((((p ∧ s) ∧ q) → ((r ∨ q) ∨ s)) ↔ (¬(((p ∧ s) ∧ q)) ∨ ((r ∨ q) ∨ s)))
((((q ∨ (t ∧ s)) ∨ (q → (s ∨ r))) ∧ ¬((q ∨ (t ∧ s)))) → (q → (s ∨ r)))
((((v → (u ∨ p)) ∨ (s ∨ (v ∧ p))) ∧ ¬((s ∨ (v ∧ p)))) → (v → (u ∨ p)))
((((v ∧ (q ∨ r)) ∨ ((t ∨ u) ∨ r)) ∧ ¬(((t ∨ u) ∨ r))) → (v ∧ (q ∨ r)))
((((r ∧ (u ∨ t)) ∨ ((p ∧ q) → r)) ∧ ¬((r ∧ (u ∨ t)))) → ((p ∧ q) → r))
(((((u ∨ s) ∨ v) ∨ (u ∧ (v ∨ r))) ∧ ¬((u ∧ (v ∨ r)))) → ((u ∨ s) ∨ v))
((((v ∨ q) ∨ r) → (t ∧ (r ∨ s))) ↔ (¬(((v ∨ q) ∨ r)) ∨ (t ∧ (r ∨ s))))
(((p ∨ (s ∧ q)) → ((q ∨ r) ∨ v)) ↔ (¬((p ∨ (s ∧ q))) ∨ ((q ∨ r) ∨ v)))
(((((r ∧ v) → p) ∨ (v ∨ (r ∧ s))) ∧ ¬(((r ∧ v) → p))) → (v ∨ (r ∧ s)))
((((s ∧ (u ∨ r)) ∨ ((v ∨ s) ∨ u)) ∧ ¬((s ∧ (u ∨ r)))) → ((v ∨ s) ∨ u))
((((u ∨ s) ∨ r) → ((q ∨ r) ∨ s)) ↔ (¬(((u ∨ s) ∨ r)) ∨ ((q ∨ r) ∨ s)))
((((v ∧ (p ∨ t)) ∨ ((s ∧ u) ∧ t)) ∧ ¬(((s ∧ u) ∧ t))) → (v ∧ (p ∨ t)))
(((((u ∨ v) ∨ q) ∨ ((s ∨ u) ∨ p)) ∧ ¬(((u ∨ v) ∨ q))) → ((s ∨ u) ∨ p))
((((t ∧ u) → p) → (p ∧ (v ∨ u))) ↔ (¬(((t ∧ u) → p)) ∨ (p ∧ (v ∨ u))))
((((t ∧ s) → p) → ((t ∧ r) → p)) ↔ (¬(((t ∧ s) → p)) ∨ ((t ∧ r) → p)))
(((((p ∧ t) → r) ∨ (t ∨ (q ∧ r))) ∧ ¬(((p ∧ t) → r))) → (t ∨ (q ∧ r)))
((((u ∨ (q ∧ p)) ∨ ((s ∧ v) ∧ q)) ∧ ¬(((s ∧ v) ∧ q))) → (u ∨ (q ∧ p)))
((((r ∧ v) → u) → (s → (p ∨ v))) ↔ (¬(((r ∧ v) → u)) ∨ (s → (p ∨ v))))
((((u → (v ∨ r)) ∨ ((u ∧ p) ∧ r)) ∧ ¬(((u ∧ p) ∧ r))) → (u → (v ∨ r)))
((((q ∨ s) ∨ p) → ((s ∨ v) ∨ q)) ↔ (¬(((q ∨ s) ∨ p)) ∨ ((s ∨ v) ∨ q)))
(((((v ∧ p) → s) ∨ ((p ∨ v) ∨ t)) ∧ ¬(((v ∧ p) → s))) → ((p ∨ v) ∨ t))
(((((r ∧ v) ∧ p) ∨ ((r ∧ s) → u)) ∧ ¬(((r ∧ s) → u))) → ((r ∧ v) ∧ p))
(((((r ∨ p) ∨ v) ∨ ((s ∧ r) ∧ q)) ∧ ¬(((s ∧ r) ∧ q))) → ((r ∨ p) ∨ v))
((((q ∧ (s ∨ t)) ∨ ((s ∧ q) → v)) ∧ ¬(((s ∧ q) → v))) → (q ∧ (s ∨ t)))
(((((r ∧ u) → t) ∨ ((v ∧ q) → r)) ∧ ¬(((r ∧ u) → t))) → ((v ∧ q) → r))
(((t ∧ (v ∨ s)) → ((r ∨ v) ∨ p)) ↔ (¬((t ∧ (v ∨ s))) ∨ ((r ∨ v) ∨ p)))
(((((r ∨ q) ∨ v) ∨ ((r ∨ u) ∨ s)) ∧ ¬(((r ∨ q) ∨ v))) → ((r ∨ u) ∨ s))
(((((s ∧ v) → t) ∨ ((v ∧ s) ∧ r)) ∧ ¬(((s ∧ v) → t))) → ((v ∧ s) ∧ r))
((((p ∧ (v ∨ q)) ∨ (v ∧ (u ∨ q))) ∧ ¬((p ∧ (v ∨ q)))) → (v ∧ (u ∨ q)))
((((s → (r ∨ p)) ∨ ((p ∨ r) ∨ s)) ∧ ¬((s → (r ∨ p)))) → ((p ∨ r) ∨ s))
(((((s ∧ t) ∧ u) ∨ ((r ∧ s) ∧ p)) ∧ ¬(((s ∧ t) ∧ u))) → ((r ∧ s) ∧ p))
(((((t ∨ s) ∨ v) ∨ (t ∨ (s ∧ v))) ∧ ¬((t ∨ (s ∧ v)))) → ((t ∨ s) ∨ v))
((((t ∧ u) → r) → ((r ∧ q) → s)) ↔ (¬(((t ∧ u) → r)) ∨ ((r ∧ q) → s)))
((((v ∧ p) → s) → (s → (p ∨ r))) ↔ (¬(((v ∧ p) → s)) ∨ (s → (p ∨ r))))
((((q → (p ∨ r)) ∨ (q → (u ∨ v))) ∧ ¬((q → (p ∨ r)))) → (q → (u ∨ v)))
((((r → (v ∨ q)) ∨ (v ∨ (t ∧ u))) ∧ ¬((v ∨ (t ∧ u)))) → (r → (v ∨ q)))
(((((r ∧ q) ∧ s) ∨ (u ∨ (t ∧ s))) ∧ ¬((u ∨ (t ∧ s)))) → ((r ∧ q) ∧ s))
((((r → (p ∨ q)) ∨ ((t ∨ r) ∨ v)) ∧ ¬((r → (p ∨ q)))) → ((t ∨ r) ∨ v))
(((((s ∧ q) ∧ p) ∨ ((u ∧ q) ∧ s)) ∧ ¬(((s ∧ q) ∧ p))) → ((u ∧ q) ∧ s))
((((p → (s ∨ t)) ∨ ((p ∧ q) → r)) ∧ ¬((p → (s ∨ t)))) → ((p ∧ q) → r))
((((q ∧ (v ∨ s)) ∨ (u ∧ (q ∨ r))) ∧ ¬((q ∧ (v ∨ s)))) → (u ∧ (q ∨ r)))
((((u ∧ p) → r) → ((s ∧ v) → t)) → (¬(((s ∧ v) → t)) → ¬(((u ∧ p) → r))))
(¬((((t ∧ s) → v) → (u → (t ∨ s)))) ↔ (((t ∧ s) → v) ∧ ¬((u → (t ∨ s)))))
((¬(((r ∨ u) ∨ v)) → ¬((s ∧ (u ∨ t)))) → ((s ∧ (u ∨ t)) → ((r ∨ u) ∨ v)))
(¬((((p ∨ s) ∨ r) → (p ∨ (u ∧ t)))) ↔ (((p ∨ s) ∨ r) ∧ ¬((p ∨ (u ∧ t)))))
((¬(((u ∨ r) ∨ v)) → ¬(((t ∧ u) ∧ q))) → (((t ∧ u) ∧ q) → ((u ∨ r) ∨ v)))
((((u ∨ v) ∨ s) → ((s ∧ r) → v)) → (¬(((s ∧ r) → v)) → ¬(((u ∨ v) ∨ s))))
((((u → (v ∨ t)) → (r → (q ∨ p))) ∧ ¬((r → (q ∨ p)))) → ¬((u → (v ∨ t))))
(((p ∨ (u ∧ v)) → ((v ∧ p) → r)) → (¬(((v ∧ p) → r)) → ¬((p ∨ (u ∧ v)))))
((¬((p ∧ (v ∨ r))) → ¬((q ∨ (r ∧ t)))) → ((q ∨ (r ∧ t)) → (p ∧ (v ∨ r))))
(¬((((p ∧ s) ∧ q) → ((p ∧ u) → r))) ↔ (((p ∧ s) ∧ q) ∧ ¬(((p ∧ u) → r))))
(((((q ∨ v) ∨ u) → (s ∧ ¬q)) ∧ (¬(((q ∨ v) ∨ u)) → (s ∧ ¬q))) → (s ∧ ¬q))
(¬(((t ∨ (u ∧ q)) → ((v ∧ s) → u))) ↔ ((t ∨ (u ∧ q)) ∧ ¬(((v ∧ s) → u))))
(((((s ∨ r) ∨ q) → (v ∨ (p ∧ q))) ∧ ¬((v ∨ (p ∧ q)))) → ¬(((s ∨ r) ∨ q)))
((((v → (s ∨ q)) → (q → (t ∨ p))) ∧ ¬((q → (t ∨ p)))) → ¬((v → (s ∨ q))))
(¬((((v ∧ q) ∧ u) → ((s ∨ p) ∨ r))) ↔ (((v ∧ q) ∧ u) ∧ ¬(((s ∨ p) ∨ r))))
(¬(((t ∧ (q ∨ u)) → (u → (t ∨ s)))) ↔ ((t ∧ (q ∨ u)) ∧ ¬((u → (t ∨ s)))))
((((s ∨ v) ∨ q) → ((s ∨ p) ∨ q)) → (¬(((s ∨ p) ∨ q)) → ¬(((s ∨ v) ∨ q))))
((((u ∨ v) ∨ p) → (u ∧ (v ∨ t))) → (¬((u ∧ (v ∨ t))) → ¬(((u ∨ v) ∨ p))))
((¬(((v ∧ q) ∧ r)) → ¬(((u ∧ r) ∧ t))) → (((u ∧ r) ∧ t) → ((v ∧ q) ∧ r)))
(((((p ∧ r) → u) → ((p ∧ s) → q)) ∧ ¬(((p ∧ s) → q))) → ¬(((p ∧ r) → u)))
(((((p ∨ r) ∨ u) → ((q ∧ r) ∧ s)) ∧ ¬(((q ∧ r) ∧ s))) → ¬(((p ∨ r) ∨ u)))
(¬((((r ∧ p) → q) → ((p ∨ s) ∨ u))) ↔ (((r ∧ p) → q) ∧ ¬(((p ∨ s) ∨ u))))
(((v ∨ (t ∧ s)) → ((u ∧ r) ∧ p)) → (¬(((u ∧ r) ∧ p)) → ¬((v ∨ (t ∧ s)))))
((((q → (p ∨ v)) → (t ∨ (u ∧ v))) ∧ ¬((t ∨ (u ∧ v)))) → ¬((q → (p ∨ v))))
(((((t ∧ r) ∧ p) → ((q ∨ v) ∨ t)) ∧ ¬(((q ∨ v) ∨ t))) → ¬(((t ∧ r) ∧ p)))
(((t → (u ∨ q)) → (r → (p ∨ s))) → (¬((r → (p ∨ s))) → ¬((t → (u ∨ q)))))
(¬(((r ∧ (q ∨ v)) → (p ∨ (v ∧ r)))) ↔ ((r ∧ (q ∨ v)) ∧ ¬((p ∨ (v ∧ r)))))
(¬((((u ∧ q) ∧ v) → (q ∧ (p ∨ v)))) ↔ (((u ∧ q) ∧ v) ∧ ¬((q ∧ (p ∨ v)))))
((¬((v ∧ (s ∨ u))) → ¬(((u ∧ r) → v))) → (((u ∧ r) → v) → (v ∧ (s ∨ u))))
(((((q ∧ u) → p) → ((s ∧ u) ∧ q)) ∧ ¬(((s ∧ u) ∧ q))) → ¬(((q ∧ u) → p)))
((¬(((u ∧ q) → r)) → ¬((u ∨ (s ∧ v)))) → ((u ∨ (s ∧ v)) → ((u ∧ q) → r)))
(¬((((t ∨ p) ∨ u) → (u → (v ∨ p)))) ↔ (((t ∨ p) ∨ u) ∧ ¬((u → (v ∨ p)))))
((((p ∧ q) → t) → ((u ∧ p) → v)) → (¬(((u ∧ p) → v)) → ¬(((p ∧ q) → t))))
((((u ∧ t) ∧ q) ↔ ((u ∨ q) ∨ s)) → (¬(((u ∧ t) ∧ q)) ↔ ¬(((u ∨ q) ∨ s))))
(¬((((r ∧ v) → u) → (s ∨ (p ∧ r)))) ↔ (((r ∧ v) → u) ∧ ¬((s ∨ (p ∧ r)))))
((((v ∧ s) → r) ↔ (q ∧ (u ∨ r))) → (¬(((v ∧ s) → r)) ↔ ¬((q ∧ (u ∨ r)))))
(((((v ∨ p) ∨ s) → ((v ∧ t) → u)) ∧ ¬(((v ∧ t) → u))) → ¬(((v ∨ p) ∨ s)))
(((t ∨ (v ∧ r)) ↔ ((r ∧ q) ∧ s)) → (¬((t ∨ (v ∧ r))) ↔ ¬(((r ∧ q) ∧ s))))
(¬((((s ∨ r) ∨ v) → (q → (v ∨ r)))) ↔ (((s ∨ r) ∨ v) ∧ ¬((q → (v ∨ r)))))
(((v ∧ (r ∨ u)) → (r ∧ (t ∨ s))) → (¬((r ∧ (t ∨ s))) → ¬((v ∧ (r ∨ u)))))
((¬((t → (r ∨ v))) → ¬((s → (q ∨ p)))) → ((s → (q ∨ p)) → (t → (r ∨ v))))
(((((s ∧ p) → v) → ((v ∧ u) ∧ r)) ∧ ¬(((v ∧ u) ∧ r))) → ¬(((s ∧ p) → v)))
((((u ∨ (t ∧ q)) → ((r ∨ v) ∨ u)) ∧ ¬(((r ∨ v) ∨ u))) → ¬((u ∨ (t ∧ q))))
((((u ∨ r) ∨ t) ↔ ((s ∧ q) ∧ t)) → (¬(((u ∨ r) ∨ t)) ↔ ¬(((s ∧ q) ∧ t))))
(((((v ∧ u) ∧ r) → ((q ∨ p) ∨ u)) ∧ ¬(((q ∨ p) ∨ u))) → ¬(((v ∧ u) ∧ r)))
(((v ∨ (t ∧ q)) → ((r ∧ t) ∧ v)) → (¬(((r ∧ t) ∧ v)) → ¬((v ∨ (t ∧ q)))))
((((r ∨ v) ∨ u) ↔ ((s ∧ v) ∧ u)) → (¬(((r ∨ v) ∨ u)) ↔ ¬(((s ∧ v) ∧ u))))
((¬((u → (t ∨ v))) → ¬((t ∨ (q ∧ s)))) → ((t ∨ (q ∧ s)) → (u → (t ∨ v))))
((((r ∧ u) ∧ t) → ((v ∧ r) ∧ q)) → (¬(((v ∧ r) ∧ q)) → ¬(((r ∧ u) ∧ t))))
((((q ∧ u) ∧ t) → (r → (u ∨ s))) → (¬((r → (u ∨ s))) → ¬(((q ∧ u) ∧ t))))
(((((u ∧ q) → t) → (r → (s ∨ q))) ∧ ¬((r → (s ∨ q)))) → ¬(((u ∧ q) → t)))
((((r ∧ p) ∧ t) ↔ (p ∧ (s ∨ t))) → (¬(((r ∧ p) ∧ t)) ↔ ¬((p ∧ (s ∨ t)))))
((((s ∧ u) → p) → ((r ∧ s) ∧ u)) → (¬(((r ∧ s) ∧ u)) → ¬(((s ∧ u) → p))))
(((((v ∧ s) → t) → (q → (r ∨ v))) ∧ ¬((q → (r ∨ v)))) → ¬(((v ∧ s) → t)))
(((((v ∨ q) ∨ s) → ((p ∧ q) → v)) ∧ ¬(((p ∧ q) → v))) → ¬(((v ∨ q) ∨ s)))
((((p ∧ s) ∧ q) ↔ (s ∨ (p ∧ t))) → (¬(((p ∧ s) ∧ q)) ↔ ¬((s ∨ (p ∧ t)))))
(((((s ∧ v) ∧ u) → ((p ∧ v) → t)) ∧ ¬(((p ∧ v) → t))) → ¬(((s ∧ v) ∧ u)))
(((((p ∧ t) ∧ s) → (q → (r ∨ p))) ∧ ¬((q → (r ∨ p)))) → ¬(((p ∧ t) ∧ s)))
(((p ∧ (v ∨ r)) ↔ ((s ∧ r) → t)) → (¬((p ∧ (v ∨ r))) ↔ ¬(((s ∧ r) → t))))
((((p ∨ (v ∧ s)) → (p ∨ (q ∧ s))) ∧ ¬((p ∨ (q ∧ s)))) → ¬((p ∨ (v ∧ s))))
(¬(((p → (s ∨ r)) ∧ ((s ∧ q) ∧ u))) ↔ (¬((p → (s ∨ r))) ∨ ¬(((s ∧ q) ∧ u))))
(¬(((r → (v ∨ u)) ∧ ((s ∧ p) → v))) ↔ (¬((r → (v ∨ u))) ∨ ¬(((s ∧ p) → v))))
(¬(((r → (q ∨ s)) ∨ (p ∧ (v ∨ t)))) ↔ (¬((r → (q ∨ s))) ∧ ¬((p ∧ (v ∨ t)))))
(¬((((t ∧ u) → v) ∨ (t → (u ∨ q)))) ↔ (¬(((t ∧ u) → v)) ∧ ¬((t → (u ∨ q)))))
(¬(((v ∨ (u ∧ s)) ∨ ((q ∧ u) ∧ s))) ↔ (¬((v ∨ (u ∧ s))) ∧ ¬(((q ∧ u) ∧ s))))
(¬(((s ∨ (t ∧ u)) ∧ ((s ∧ u) ∧ t))) ↔ (¬((s ∨ (t ∧ u))) ∨ ¬(((s ∧ u) ∧ t))))
(¬(((s ∧ (p ∨ q)) ∨ ((s ∧ u) ∧ v))) ↔ (¬((s ∧ (p ∨ q))) ∧ ¬(((s ∧ u) ∧ v))))
(¬((((p ∧ q) ∧ s) ∧ (p ∧ (s ∨ u)))) ↔ (¬(((p ∧ q) ∧ s)) ∨ ¬((p ∧ (s ∨ u)))))
(¬(((p ∧ (t ∨ r)) ∧ ((v ∨ r) ∨ u))) ↔ (¬((p ∧ (t ∨ r))) ∨ ¬(((v ∨ r) ∨ u))))
(¬((((q ∧ p) ∧ v) ∧ ((u ∧ s) → r))) ↔ (¬(((q ∧ p) ∧ v)) ∨ ¬(((u ∧ s) → r))))
(¬((((s ∧ u) ∧ v) ∨ (r → (s ∨ p)))) ↔ (¬(((s ∧ u) ∧ v)) ∧ ¬((r → (s ∨ p)))))
(¬(((q ∧ (r ∨ p)) ∧ (r ∨ (u ∧ p)))) ↔ (¬((q ∧ (r ∨ p))) ∨ ¬((r ∨ (u ∧ p)))))
(¬(((p → (u ∨ s)) ∧ (q ∧ (v ∨ u)))) ↔ (¬((p → (u ∨ s))) ∨ ¬((q ∧ (v ∨ u)))))
(¬(((s ∨ (q ∧ r)) ∨ (q → (r ∨ v)))) ↔ (¬((s ∨ (q ∧ r))) ∧ ¬((q → (r ∨ v)))))
(¬(((p ∧ (q ∨ s)) ∨ ((p ∨ q) ∨ v))) ↔ (¬((p ∧ (q ∨ s))) ∧ ¬(((p ∨ q) ∨ v))))
(¬(((s ∧ (r ∨ v)) ∧ ((v ∧ u) → s))) ↔ (¬((s ∧ (r ∨ v))) ∨ ¬(((v ∧ u) → s))))
(¬(((q → (p ∨ u)) ∨ (p ∧ (s ∨ v)))) ↔ (¬((q → (p ∨ u))) ∧ ¬((p ∧ (s ∨ v)))))
(¬(((v ∨ (r ∧ t)) ∨ ((q ∨ v) ∨ t))) ↔ (¬((v ∨ (r ∧ t))) ∧ ¬(((q ∨ v) ∨ t))))
(¬(((p → (u ∨ q)) ∨ (p ∧ (u ∨ t)))) ↔ (¬((p → (u ∨ q))) ∧ ¬((p ∧ (u ∨ t)))))
(¬((((v ∧ q) → p) ∧ ((u ∧ t) ∧ p))) ↔ (¬(((v ∧ q) → p)) ∨ ¬(((u ∧ t) ∧ p))))
(¬((((r ∨ t) ∨ u) ∧ (v ∧ (s ∨ q)))) ↔ (¬(((r ∨ t) ∨ u)) ∨ ¬((v ∧ (s ∨ q)))))
(¬(((p → (q ∨ s)) ∧ (v → (p ∨ q)))) ↔ (¬((p → (q ∨ s))) ∨ ¬((v → (p ∨ q)))))
(¬(((q → (r ∨ v)) ∨ ((t ∨ v) ∨ r))) ↔ (¬((q → (r ∨ v))) ∧ ¬(((t ∨ v) ∨ r))))
(¬((((p ∨ v) ∨ u) ∧ (u ∧ (p ∨ v)))) ↔ (¬(((p ∨ v) ∨ u)) ∨ ¬((u ∧ (p ∨ v)))))
(¬(((p → (q ∨ s)) ∧ (q ∨ (p ∧ s)))) ↔ (¬((p → (q ∨ s))) ∨ ¬((q ∨ (p ∧ s)))))
(((((u ∧ t) → r) ∧ v) → ((u ∨ r) ∨ p)) → (((u ∧ t) → r) → (v → ((u ∨ r) ∨ p))))
(((v → s) → ((v → (r ∨ q)) → (r ↔ t))) → (((v → s) ∧ (v → (r ∨ q))) → (r ↔ t)))
((((u ∨ r) ∧ ((q ∨ t) ∨ s)) → (v ∧ s)) → ((u ∨ r) → (((q ∨ t) ∨ s) → (v ∧ s))))
(((((s ∧ t) ∧ p) ∨ ((q ∨ r) ∨ p)) ∨ u) → (((s ∧ t) ∧ p) ∨ (((q ∨ r) ∨ p) ∨ u)))
((((s ∨ u) ∨ (t ↔ v)) ∨ (s → (v ∨ q))) → ((s ∨ u) ∨ ((t ↔ v) ∨ (s → (v ∨ q)))))
((((r ∨ u) → (r ↔ t)) ∧ ((r ↔ t) → (q → (p ∨ u)))) → ((r ∨ u) → (q → (p ∨ u))))
((((r ↔ q) → ((r ∧ p) ∧ q)) ∧ (((r ∧ p) ∧ q) → (t ↔ v))) → ((r ↔ q) → (t ↔ v)))
((((q ∧ s) ∧ v) → ((q ∨ u) → (r ∧ t))) → ((((q ∧ s) ∧ v) ∧ (q ∨ u)) → (r ∧ t)))
((((t ∧ q) → p) ∨ ((t → v) ∨ (u → t))) → ((((t ∧ q) → p) ∨ (t → v)) ∨ (u → t)))
((((u ∧ p) → (q ∧ r)) ∧ ((q ∧ r) → (u → (t ∨ q)))) → ((u ∧ p) → (u → (t ∨ q))))
(((((t ∧ s) ∧ p) ∧ (t ∧ v)) ∧ (¬u ∨ r)) → (((t ∧ s) ∧ p) ∧ ((t ∧ v) ∧ (¬u ∨ r))))
((((¬v ∨ q) ∧ (v ∧ t)) ∧ (p ∨ (t ∧ r))) → ((¬v ∨ q) ∧ ((v ∧ t) ∧ (p ∨ (t ∧ r)))))
(((((r ∨ t) ∨ s) ∧ ¬t) ∧ ((s ∨ v) ∨ r)) → (((r ∨ t) ∨ s) ∧ (¬t ∧ ((s ∨ v) ∨ r))))
(((((u ∨ ((s ∧ p) → v)) ∨ ((p ∨ s) ∨ v)) ∧ ¬u) ∧ ¬(((s ∧ p) → v))) → ((p ∨ s) ∨ v))
((((p ∧ ¬u) → (s ∧ (t ∨ v))) ∧ ((s ∧ (t ∨ v)) → (¬r ∨ v))) → ((p ∧ ¬u) → (¬r ∨ v)))
((((s → (p ∨ r)) → (q ∨ r)) ∧ ((q ∨ r) → (s → (p ∨ r)))) → ((s → (p ∨ r)) ↔ (q ∨ r)))
((((v → (t ∨ q)) → (u ∧ t)) ∧ ((u ∧ t) → (v → (t ∨ q)))) → ((v → (t ∨ q)) ↔ (u ∧ t)))
((((((v ∨ p) ∨ t) → u) ∧ ((s ∨ (v ∧ q)) → u)) ∧ (((v ∨ p) ∨ t) ∨ (s ∨ (v ∧ q)))) → u)
(((((t ∧ s) ∧ p) → (u → t)) ∧ ((u → t) → ((t ∧ s) ∧ p))) → (((t ∧ s) ∧ p) ↔ (u → t)))
((((v ∧ s) → (q ∨ (t ∧ v))) ∧ ((q ∨ (t ∧ v)) → (v ∧ s))) → ((v ∧ s) ↔ (q ∨ (t ∧ v))))
((((r ∧ u) → (v → (s ∨ p))) ∧ ((v → (s ∨ p)) → (r ∧ u))) → ((r ∧ u) ↔ (v → (s ∨ p))))
((((q ↔ u) → ((s ∧ v) ∧ t)) ∧ (((s ∧ v) ∧ t) → (q ↔ u))) → ((q ↔ u) ↔ ((s ∧ v) ∧ t)))
((((q ↔ t) → (v ∨ (u ∧ r))) ∧ ((v ∨ (u ∧ r)) → (q ↔ t))) → ((q ↔ t) ↔ (v ∨ (u ∧ r))))
((((s → (q ∨ v)) → (s ∧ v)) ∧ ((s ∧ v) → (s → (q ∨ v)))) → ((s → (q ∨ v)) ↔ (s ∧ v)))
((((s ∨ q) → ((u ∧ s) → t)) ∧ (((u ∧ s) → t) → (s ∨ q))) → ((s ∨ q) ↔ ((u ∧ s) → t)))
(((((p ∧ t) → q) → ((t ∧ v) → q)) ∧ (¬(((p ∧ t) → q)) → ((t ∧ v) → q))) → ((t ∧ v) → q))
(((((t ∧ s) → v) → ((t ∧ v) ∧ r)) ∧ (¬(((t ∧ s) → v)) → ((t ∧ v) ∧ r))) → ((t ∧ v) ∧ r))
(((((v ∨ s) ∨ t) → (r ∧ ¬t)) ∧ ((r ∧ ¬t) → ((v ∨ s) ∨ t))) → (((v ∨ s) ∨ t) ↔ (r ∧ ¬t)))
(((((v ∧ u) → p) → (r ∧ (q ∨ v))) ∧ (¬(((v ∧ u) → p)) → (r ∧ (q ∨ v)))) → (r ∧ (q ∨ v)))
(((((q ∧ v) ∧ p) → (t ∧ ¬p)) ∧ ((t ∧ ¬p) → ((q ∧ v) ∧ p))) → (((q ∧ v) ∧ p) ↔ (t ∧ ¬p)))
(((((s ∧ t) → v) → ((s ∧ t) → u)) ∧ (¬(((s ∧ t) → v)) → ((s ∧ t) → u))) → ((s ∧ t) → u))
((((q ∧ (r ∨ s)) → ((s ∧ q) → u)) ∧ (¬((q ∧ (r ∨ s))) → ((s ∧ q) → u))) → ((s ∧ q) → u))
((((u → (q ∨ v)) → ((s ∧ v) ∧ t)) ∧ (¬((u → (q ∨ v))) → ((s ∧ v) ∧ t))) → ((s ∧ v) ∧ t))
((((t ∧ ¬r) → (q ∨ (s ∧ v))) ∧ ((q ∨ (s ∧ v)) → (t ∧ ¬r))) → ((t ∧ ¬r) ↔ (q ∨ (s ∧ v))))
(((((s ∨ q) ∨ t) → ((r ∧ u) ∧ p)) ∧ (¬(((s ∨ q) ∨ t)) → ((r ∧ u) ∧ p))) → ((r ∧ u) ∧ p))
((((¬p ∨ t) → (r → (p ∨ u))) ∧ ((r → (p ∨ u)) → (¬p ∨ t))) → ((¬p ∨ t) ↔ (r → (p ∨ u))))
((((q ∨ (t ∧ r)) → (¬s ∨ r)) ∧ ((¬s ∨ r) → (q ∨ (t ∧ r)))) → ((q ∨ (t ∧ r)) ↔ (¬s ∨ r)))
((((((¬r ∨ u) ∨ ((v ∨ s) ∨ t)) ∨ (p ∧ ¬u)) ∧ ¬((¬r ∨ u))) ∧ ¬(((v ∨ s) ∨ t))) → (p ∧ ¬u))
((((v → (u ∨ p)) ∨ ((s ∧ t) ∧ u)) ∨ (u → r)) → ((v → (u ∨ p)) ∨ (((s ∧ t) ∧ u) ∨ (u → r))))
((((s ∨ v) ∨ p) ∧ ((q ∨ u) ∧ ((q ∧ v) ∧ u))) → ((((s ∨ v) ∨ p) ∧ (q ∨ u)) ∧ ((q ∧ v) ∧ u)))
(((s ∧ q) → (((t ∨ q) ∨ v) → ((r ∨ t) ∨ q))) → (((t ∨ q) ∨ v) → ((s ∧ q) → ((r ∨ t) ∨ q))))
(((s ∧ (r ∨ t)) ∨ ((q ∨ r) ∨ ((p ∧ r) ∧ v))) → (((s ∧ (r ∨ t)) ∨ (q ∨ r)) ∨ ((p ∧ r) ∧ v)))
(((s → (p ∨ r)) ∧ ((r → p) ∧ (t → (q ∨ r)))) → (((s → (p ∨ r)) ∧ (r → p)) ∧ (t → (q ∨ r))))
(((((r ∨ p) ∨ u) ∧ (t ∨ r)) → (r ∧ (s ∨ t))) → (((r ∨ p) ∨ u) → ((t ∨ r) → (r ∧ (s ∨ t)))))
(((v → s) ∨ ((q ∨ (t ∧ r)) ∨ (t ∨ (q ∧ s)))) → (((v → s) ∨ (q ∨ (t ∧ r))) ∨ (t ∨ (q ∧ s))))
((((q ↔ s) ∧ ((s ∨ u) ∨ t)) → ((t ∧ q) ∧ s)) → ((q ↔ s) → (((s ∨ u) ∨ t) → ((t ∧ q) ∧ s))))
(((v ∧ p) ∨ ((q ∧ (u ∨ s)) ∨ ((v ∧ p) ∧ u))) → (((v ∧ p) ∨ (q ∧ (u ∨ s))) ∨ ((v ∧ p) ∧ u)))
((((v ∧ t) → u) ∧ ((q ∨ s) ∧ (u ∧ (s ∨ v)))) → ((((v ∧ t) → u) ∧ (q ∨ s)) ∧ (u ∧ (s ∨ v))))
((((v ∧ (s ∨ p)) ∨ (q ∨ s)) ∨ ((p ∧ v) ∧ r)) → ((v ∧ (s ∨ p)) ∨ ((q ∨ s) ∨ ((p ∧ v) ∧ r))))
((((u ∧ q) → t) → ((r → s) → (r ∨ (p ∧ s)))) → ((((u ∧ q) → t) ∧ (r → s)) → (r ∨ (p ∧ s))))
((((v ∨ u) → (u ∨ (p ∧ v))) ∧ ((u ∨ (p ∧ v)) → (r → (u ∨ q)))) → ((v ∨ u) → (r → (u ∨ q))))
((((r ∧ q) ∧ v) ∧ ((v ∧ u) ∧ (s ∨ (t ∧ q)))) → ((((r ∧ q) ∧ v) ∧ (v ∧ u)) ∧ (s ∨ (t ∧ q))))
(((((v ∧ p) ∧ t) → (r ∧ u)) ∧ ((r ∧ u) → ((q ∧ r) ∧ s))) → (((v ∧ p) ∧ t) → ((q ∧ r) ∧ s)))
((((s → q) → ((v ∨ p) ∨ q)) ∧ (((v ∨ p) ∨ q) → (v ∧ (u ∨ t)))) → ((s → q) → (v ∧ (u ∨ t))))
((((u ∧ p) ∨ (q ∨ (r ∧ u))) ∨ ((q ∨ r) ∨ p)) → ((u ∧ p) ∨ ((q ∨ (r ∧ u)) ∨ ((q ∨ r) ∨ p))))
(((((t ∧ q) ∧ r) ∧ (t ∧ p)) ∧ (q ∧ (t ∨ p))) → (((t ∧ q) ∧ r) ∧ ((t ∧ p) ∧ (q ∧ (t ∨ p)))))
((((r ∧ u) ↔ ((t ∧ r) ∧ v)) ∧ (((t ∧ r) ∧ v) ↔ ((r ∨ v) ∨ u))) → ((r ∧ u) ↔ ((r ∨ v) ∨ u)))
((((t ∨ q) ∧ ((s ∧ p) → u)) ∧ ((r ∧ t) → s)) → ((t ∨ q) ∧ (((s ∧ p) → u) ∧ ((r ∧ t) → s))))
(((p ∧ u) → ((t → (s ∨ u)) → ((p ∧ t) ∧ s))) → (((p ∧ u) ∧ (t → (s ∨ u))) → ((p ∧ t) ∧ s)))
((((r ∨ (u ∧ v)) ∧ ((r ∧ s) ∧ u)) → (u ∧ s)) → ((r ∨ (u ∧ v)) → (((r ∧ s) ∧ u) → (u ∧ s))))
((((u ∨ (v ∧ s)) ∧ (u ∧ r)) → ((q ∧ p) → s)) → ((u ∨ (v ∧ s)) → ((u ∧ r) → ((q ∧ p) → s))))
(((((s ∧ q) ∧ p) → (q → (r ∨ v))) ∧ ((q → (r ∨ v)) → (p ∨ u))) → (((s ∧ q) ∧ p) → (p ∨ u)))
(((t ∧ (q ∨ r)) → ((r ↔ t) → (r ∧ (s ∨ q)))) → ((r ↔ t) → ((t ∧ (q ∨ r)) → (r ∧ (s ∨ q)))))
((((t ∧ (r ∨ u)) ∧ (v ∧ (t ∨ p))) ∧ (q → s)) → ((t ∧ (r ∨ u)) ∧ ((v ∧ (t ∨ p)) ∧ (q → s))))
((((u ∨ s) ∨ p) → (((u ∧ v) ∧ p) → (u ∨ r))) → ((((u ∨ s) ∨ p) ∧ ((u ∧ v) ∧ p)) → (u ∨ r)))
((((t ∧ v) ∨ ((p ∨ q) ∨ r)) ∨ (s ∨ (q ∧ v))) → ((t ∧ v) ∨ (((p ∨ q) ∨ r) ∨ (s ∨ (q ∧ v)))))
(((s ↔ v) ↔ ((p ∨ v) ∨ s)) → (((s ↔ v) ∨ (v ∧ (s ∨ r))) ↔ (((p ∨ v) ∨ s) ∨ (v ∧ (s ∨ r)))))
(((u ∧ (p ∨ t)) ∧ ((v ∨ (q ∧ p)) ∧ (r ∨ s))) → (((u ∧ (p ∨ t)) ∧ (v ∨ (q ∧ p))) ∧ (r ∨ s)))
(((((q ∨ t) ∨ r) → (t → (r ∨ s))) ∧ ((t → (r ∨ s)) → (s ∨ t))) → (((q ∨ t) ∨ r) → (s ∨ t)))
(((r ↔ s) ∨ ((p ∨ (u ∧ v)) ∨ ((v ∨ p) ∨ t))) → (((r ↔ s) ∨ (p ∨ (u ∧ v))) ∨ ((v ∨ p) ∨ t)))
(((((p ∧ s) → q) → (u ∧ p)) ∧ ((u ∧ p) → ((q ∨ p) ∨ v))) → (((p ∧ s) → q) → ((q ∨ p) ∨ v)))
((((t ↔ q) ∧ (q → (v ∨ s))) ∧ (r → (q ∨ p))) → ((t ↔ q) ∧ ((q → (v ∨ s)) ∧ (r → (q ∨ p)))))
(((s ↔ q) ∧ (((t ∨ u) ∨ s) ∧ (r → (t ∨ q)))) → (((s ↔ q) ∧ ((t ∨ u) ∨ s)) ∧ (r → (t ∨ q))))
((((v ∧ p) ∧ s) ∧ (((p ∨ t) ∨ q) ∧ (u ∨ r))) → ((((v ∧ p) ∧ s) ∧ ((p ∨ t) ∨ q)) ∧ (u ∨ r)))
(((q → (p ∨ r)) ∨ ((v ↔ t) ∨ (v → (s ∨ t)))) → (((q → (p ∨ r)) ∨ (v ↔ t)) ∨ (v → (s ∨ t))))
((((u → (t ∨ q)) → (t ∧ s)) ∧ ((t ∧ s) → ((s ∨ u) ∨ r))) → ((u → (t ∨ q)) → ((s ∨ u) ∨ r)))
((((u ∨ (q ∧ p)) → (u → (t ∨ v))) ∧ ((u → (t ∨ v)) → (u ∨ s))) → ((u ∨ (q ∧ p)) → (u ∨ s)))
((((v ∧ u) → t) ↔ (p → s)) → ((((v ∧ u) → t) ∧ (u ∨ (p ∧ t))) ↔ ((p → s) ∧ (u ∨ (p ∧ t)))))
((((p ↔ r) ∧ ((u ∨ v) ∨ s)) ∧ (p ∧ (q ∨ u))) → ((p ↔ r) ∧ (((u ∨ v) ∨ s) ∧ (p ∧ (q ∨ u)))))
((((t ∧ u) ∧ v) ↔ (q ∧ t)) → ((((t ∧ u) ∧ v) ∨ (v ∨ (t ∧ s))) ↔ ((q ∧ t) ∨ (v ∨ (t ∧ s)))))
((((q ∨ p) ∨ v) ∧ ((p ∧ v) ∧ (v ∧ (u ∨ r)))) → ((((q ∨ p) ∨ v) ∧ (p ∧ v)) ∧ (v ∧ (u ∨ r))))
(((s ↔ v) → ((v ∧ (s ∨ r)) → (t ∨ (r ∧ p)))) → ((v ∧ (s ∨ r)) → ((s ↔ v) → (t ∨ (r ∧ p)))))
(((t ∧ ¬s) → ((u ∧ (t ∨ p)) → ((r ∧ t) ∧ v))) → (((t ∧ ¬s) ∧ (u ∧ (t ∨ p))) → ((r ∧ t) ∧ v)))
((((s ∨ v) ∨ q) ∧ ((¬q ∨ s) ∧ ((t ∧ v) → r))) → ((((s ∨ v) ∨ q) ∧ (¬q ∨ s)) ∧ ((t ∧ v) → r)))
((((t ∧ v) → s) ∧ (((q ∧ p) → v) ∧ (t ∧ ¬r))) → ((((t ∧ v) → s) ∧ ((q ∧ p) → v)) ∧ (t ∧ ¬r)))
((((t ∧ v) ∧ u) ∧ ((¬r ∨ t) ∧ ((u ∧ t) → s))) → ((((t ∧ v) ∧ u) ∧ (¬r ∨ t)) ∧ ((u ∧ t) → s)))
((((r ∧ ¬q) ∨ ((u ∧ t) → s)) ∨ (s ∨ (r ∧ t))) → ((r ∧ ¬q) ∨ (((u ∧ t) → s) ∨ (s ∨ (r ∧ t)))))
((((v ↔ q) → ((s ∧ p) ∧ q)) ∧ ((v ↔ q) → (s ∧ ¬u))) → ((v ↔ q) → (((s ∧ p) ∧ q) ∧ (s ∧ ¬u))))
(((((t ∧ s) ∧ q) ∧ (v ∧ ¬u)) → (q ∨ (r ∧ p))) → (((t ∧ s) ∧ q) → ((v ∧ ¬u) → (q ∨ (r ∧ p)))))
((((s ∨ (r ∧ v)) → ((p ∧ s) → v)) ∧ (((p ∧ s) → v) → (¬t ∨ v))) → ((s ∨ (r ∧ v)) → (¬t ∨ v)))
((((p ∧ v) → q) → ((p → (u ∨ q)) → (p ∧ ¬q))) → ((p → (u ∨ q)) → (((p ∧ v) → q) → (p ∧ ¬q))))
((((t ∨ (q ∧ p)) → (t → (r ∨ v))) ∧ ((t → (r ∨ v)) → (s ∧ ¬q))) → ((t ∨ (q ∧ p)) → (s ∧ ¬q)))
((((¬s ∨ t) → (p ∨ (v ∧ s))) ∧ ((p ∨ (v ∧ s)) → (q ∧ (p ∨ r)))) → ((¬s ∨ t) → (q ∧ (p ∨ r))))
(((r ∧ ¬u) ∨ (((v ∧ t) → s) ∨ (q ∨ (r ∧ s)))) → (((r ∧ ¬u) ∨ ((v ∧ t) → s)) ∨ (q ∨ (r ∧ s))))
((((q → (u ∨ s)) ∧ (r → (v ∨ t))) ∧ (q ∧ ¬r)) → ((q → (u ∨ s)) ∧ ((r → (v ∨ t)) ∧ (q ∧ ¬r))))
(((((¬r ∨ p) → (v ∧ u)) ∧ ((q → (u ∨ s)) → (v ∧ u))) ∧ ((¬r ∨ p) ∨ (q → (u ∨ s)))) → (v ∧ u))
(((t ∨ (p ∧ v)) ↔ ((t ∧ p) → s)) → (((t ∨ (p ∧ v)) ∧ (¬r ∨ u)) ↔ (((t ∧ p) → s) ∧ (¬r ∨ u))))
((((s ∧ ¬q) ∧ (u ∧ (t ∨ r))) → (t → (s ∨ u))) → ((s ∧ ¬q) → ((u ∧ (t ∨ r)) → (t → (s ∨ u)))))
(((t ∧ ¬q) ↔ ((q ∧ v) ∧ r)) → (((t ∧ ¬q) ∧ ((u ∧ r) ∧ p)) ↔ (((q ∧ v) ∧ r) ∧ ((u ∧ r) ∧ p))))
((((¬t ∨ q) ↔ ((s ∨ u) ∨ v)) ∧ (((s ∨ u) ∨ v) ↔ ((t ∧ r) ∧ s))) → ((¬t ∨ q) ↔ ((t ∧ r) ∧ s)))
(((s ∧ (u ∨ v)) → ((r ∧ ¬t) → ((q ∧ p) → v))) → ((r ∧ ¬t) → ((s ∧ (u ∨ v)) → ((q ∧ p) → v))))
((((u ∨ (s ∧ t)) ∧ (q ∧ ¬r)) → ((v ∧ u) ∧ q)) → ((u ∨ (s ∧ t)) → ((q ∧ ¬r) → ((v ∧ u) ∧ q))))
(((r ∨ (s ∧ v)) ∨ ((s ∨ (p ∧ u)) ∨ (s ∧ ¬t))) → (((r ∨ (s ∧ v)) ∨ (s ∨ (p ∧ u))) ∨ (s ∧ ¬t)))
(((((s ∧ r) → v) ∧ (p → (u ∨ t))) → (t ∧ ¬q)) → (((s ∧ r) → v) → ((p → (u ∨ t)) → (t ∧ ¬q))))
(((v ∧ ¬p) ∨ (((q ∧ r) ∧ s) ∨ (u ∨ (r ∧ v)))) → (((v ∧ ¬p) ∨ ((q ∧ r) ∧ s)) ∨ (u ∨ (r ∧ v))))
(((u ∨ (s ∧ q)) ∧ ((¬v ∨ r) ∧ ((v ∧ p) ∧ r))) → (((u ∨ (s ∧ q)) ∧ (¬v ∨ r)) ∧ ((v ∧ p) ∧ r)))
(((¬p ∨ q) ↔ (q ∧ (p ∨ s))) → (((¬p ∨ q) ∧ ((v ∨ q) ∨ s)) ↔ ((q ∧ (p ∨ s)) ∧ ((v ∨ q) ∨ s))))
((((¬t ∨ v) → (v ∧ (s ∨ r))) ∧ ((v ∧ (s ∨ r)) → (p → (v ∨ q)))) → ((¬t ∨ v) → (p → (v ∨ q))))
(((¬v ∨ r) → (((t ∨ v) ∨ u) → ((v ∧ p) → u))) → (((¬v ∨ r) ∧ ((t ∨ v) ∨ u)) → ((v ∧ p) → u)))
(((((t → (r ∨ s)) → ¬v) ∧ ((¬r ∨ v) → (t → u))) ∧ ((t → (r ∨ s)) ∨ (¬r ∨ v))) → (¬v ∨ (t → u)))
((((((p ∨ t) ∨ u) → (¬q ∨ t)) ∧ ((¬s ∨ u) → (¬q ∨ t))) ∧ (((p ∨ t) ∨ u) ∨ (¬s ∨ u))) → (¬q ∨ t))
((((((v → r) ∨ (v ∧ (p ∨ t))) ∨ (t ∨ (s ∧ u))) ∧ ¬((v → r))) ∧ ¬((v ∧ (p ∨ t)))) → (t ∨ (s ∧ u)))
(((((((u ∧ v) → p) ∨ ((t ∨ r) ∨ v)) ∨ (u ∨ q)) ∧ ¬(((u ∧ v) → p))) ∧ ¬(((t ∨ r) ∨ v))) → (u ∨ q))
((((((q ∨ (s ∧ v)) ∨ (s ∧ q)) ∨ (s ∨ (t ∧ u))) ∧ ¬((q ∨ (s ∧ v)))) ∧ ¬((s ∧ q))) → (s ∨ (t ∧ u)))
((((((u ∨ s) ∨ (p → (r ∨ t))) ∨ ((t ∧ v) → u)) ∧ ¬((u ∨ s))) ∧ ¬((p → (r ∨ t)))) → ((t ∧ v) → u))
((((((r ∧ (v ∨ t)) ∨ (r ∧ q)) ∨ ((p ∨ q) ∨ t)) ∧ ¬((r ∧ (v ∨ t)))) ∧ ¬((r ∧ q))) → ((p ∨ q) ∨ t))
((((((q ∧ (s ∨ t)) ∨ ((u ∨ r) ∨ s)) ∨ (p → s)) ∧ ¬((q ∧ (s ∨ t)))) ∧ ¬(((u ∨ r) ∨ s))) → (p → s))
((((((t → (r ∨ q)) ∨ (v ∧ (s ∨ u))) ∨ (p ∨ q)) ∧ ¬((t → (r ∨ q)))) ∧ ¬((v ∧ (s ∨ u)))) → (p ∨ q))
((((v → (s ∨ (u ∧ r))) ∧ (¬v → (s ∨ (u ∧ r)))) ∧ ((s ∨ (u ∧ r)) → ((t ∨ s) ∨ q))) → ((t ∨ s) ∨ q))
(((((((s ∧ q) ∧ t) ∨ (v → (r ∨ t))) ∨ (t ∧ ¬s)) ∧ ¬(((s ∧ q) ∧ t))) ∧ ¬((v → (r ∨ t)))) → (t ∧ ¬s))
(((((((t ∧ r) ∧ s) ∨ (¬v ∨ s)) ∨ ((q ∧ t) ∧ u)) ∧ ¬(((t ∧ r) ∧ s))) ∧ ¬((¬v ∨ s))) → ((q ∧ t) ∧ u))
((((¬r → ((u ∧ v) → q)) ∧ ((q ∧ (v ∨ r)) → ((u ∧ v) → q))) ∧ (¬r ∨ (q ∧ (v ∨ r)))) → ((u ∧ v) → q))
(((((s ∧ ¬u) → ((r ∨ t) ∨ u)) ∧ (¬((s ∧ ¬u)) → ((r ∨ t) ∨ u))) ∧ (((r ∨ t) ∨ u) → (r ∧ v))) → (r ∧ v))
(((((r ∨ v) ∨ s) → (u ∨ (p ∧ r))) ∧ ((u ∨ (p ∧ r)) → ((r ∧ s) → p))) → (((r ∨ v) ∨ s) → ((r ∧ s) → p)))
((((((v ∧ t) ∧ r) → (s ∧ p)) ∧ (((u ∧ t) ∧ s) → (s ∧ p))) ∧ (((v ∧ t) ∧ r) ∨ ((u ∧ t) ∧ s))) → (s ∧ p))
((((t → (p ∨ v)) ∧ ((u ∧ t) ∧ p)) ∧ (v → (t ∨ q))) → ((t → (p ∨ v)) ∧ (((u ∧ t) ∧ p) ∧ (v → (t ∨ q)))))
((((s ∨ r) ∨ u) ∧ ((u ∧ (t ∨ r)) ∧ (s ∧ (q ∨ v)))) → ((((s ∨ r) ∨ u) ∧ (u ∧ (t ∨ r))) ∧ (s ∧ (q ∨ v))))
((((t ∧ r) ∧ s) ↔ ((r ∨ v) ∨ s)) → ((((t ∧ r) ∧ s) ∧ (t ∧ (s ∨ v))) ↔ (((r ∨ v) ∨ s) ∧ (t ∧ (s ∨ v)))))
((((p → (r ∨ q)) ∨ (u → (v ∨ t))) ∨ (q ∧ (v ∨ p))) → ((p → (r ∨ q)) ∨ ((u → (v ∨ t)) ∨ (q ∧ (v ∨ p)))))
(((((v ∧ u) ∧ r) → (v ∨ (u ∧ s))) ∧ ((v ∨ (u ∧ s)) → ((v ∧ t) → q))) → (((v ∧ u) ∧ r) → ((v ∧ t) → q)))
(((((t ∧ p) → v) ∧ ((r ∨ s) ∨ t)) → (v ∧ (r ∨ t))) → (((t ∧ p) → v) → (((r ∨ s) ∨ t) → (v ∧ (r ∨ t)))))
(((((u ∧ p) → r) → ((v ∧ s) ∧ q)) ∧ (((v ∧ s) ∧ q) → ((r ∧ q) → s))) → (((u ∧ p) → r) → ((r ∧ q) → s)))
(((s → (t ∨ p)) ∧ (((t ∧ v) ∧ r) ∧ ((u ∧ p) ∧ q))) → (((s → (t ∨ p)) ∧ ((t ∧ v) ∧ r)) ∧ ((u ∧ p) ∧ q)))
(((((t ∧ q) ∧ r) → ((u ∨ p) ∨ r)) ∧ (((u ∨ p) ∨ r) → (q → (t ∨ v)))) → (((t ∧ q) ∧ r) → (q → (t ∨ v))))
((((r → (v ∨ s)) → ((q ∧ p) → u)) ∧ (((q ∧ p) → u) → (r → (v ∨ s)))) → ((r → (v ∨ s)) ↔ ((q ∧ p) → u)))
((((p ∧ (s ∨ u)) ∧ ((s ∧ q) ∧ t)) ∧ ((r ∧ t) ∧ s)) → ((p ∧ (s ∨ u)) ∧ (((s ∧ q) ∧ t) ∧ ((r ∧ t) ∧ s))))
(((t ∨ (q ∧ r)) ∨ ((s ∨ (v ∧ p)) ∨ (q ∨ (p ∧ t)))) → (((t ∨ (q ∧ r)) ∨ (s ∨ (v ∧ p))) ∨ (q ∨ (p ∧ t))))
(((((q ∧ p) → t) → (s ∧ (q ∨ t))) ∧ ((s ∧ (q ∨ t)) → ((q ∧ p) → s))) → (((q ∧ p) → t) → ((q ∧ p) → s)))
((((v ∧ p) → s) → ((r → (q ∨ s)) → ((v ∨ u) ∨ q))) → ((((v ∧ p) → s) ∧ (r → (q ∨ s))) → ((v ∨ u) ∨ q)))
(((((t ∨ s) ∨ r) ∧ ((p ∧ u) → t)) → ((s ∨ p) ∨ r)) → (((t ∨ s) ∨ r) → (((p ∧ u) → t) → ((s ∨ p) ∨ r))))
((((q ∧ s) → v) → (((t ∨ r) ∨ s) → ((t ∧ u) ∧ v))) → (((t ∨ r) ∨ s) → (((q ∧ s) → v) → ((t ∧ u) ∧ v))))
((((t → (u ∨ r)) ∧ (v → (p ∨ r))) → (r ∧ (s ∨ q))) → ((t → (u ∨ r)) → ((v → (p ∨ r)) → (r ∧ (s ∨ q)))))
(((((r ∨ v) ∨ q) ∧ (r → (q ∨ v))) → (v → (p ∨ r))) → (((r ∨ v) ∨ q) → ((r → (q ∨ v)) → (v → (p ∨ r)))))
((((q ∧ v) ∧ t) → ((r ∨ (u ∧ p)) → ((t ∧ q) ∧ v))) → ((((q ∧ v) ∧ t) ∧ (r ∨ (u ∧ p))) → ((t ∧ q) ∧ v)))
(((((s ∨ q) ∨ p) ∧ ((p ∧ t) → u)) ∧ ((t ∧ s) ∧ r)) → (((s ∨ q) ∨ p) ∧ (((p ∧ t) → u) ∧ ((t ∧ s) ∧ r))))
(((u ∨ (v ∧ s)) → ((r ∨ (s ∧ q)) → ((p ∧ u) → t))) → (((u ∨ (v ∧ s)) ∧ (r ∨ (s ∧ q))) → ((p ∧ u) → t)))
(((((s ∧ q) → v) ↔ (v ∧ (p ∨ s))) ∧ ((v ∧ (p ∨ s)) ↔ (p ∧ (t ∨ r)))) → (((s ∧ q) → v) ↔ (p ∧ (t ∨ r))))
(((t ∨ (p ∧ s)) ↔ (t ∧ (s ∨ p))) → (((t ∨ (p ∧ s)) ∧ ((q ∧ p) ∧ v)) ↔ ((t ∧ (s ∨ p)) ∧ ((q ∧ p) ∧ v))))
((((u ∨ (t ∧ q)) ∧ ((s ∧ q) ∧ t)) → (u ∧ (v ∨ r))) → ((u ∨ (t ∧ q)) → (((s ∧ q) ∧ t) → (u ∧ (v ∨ r)))))
((((r ∨ s) ∨ p) ∧ (((v ∧ q) → r) ∧ ((s ∧ v) ∧ u))) → ((((r ∨ s) ∨ p) ∧ ((v ∧ q) → r)) ∧ ((s ∧ v) ∧ u)))
(((((p ∧ t) ∧ r) ↔ (t ∨ (v ∧ q))) ∧ ((t ∨ (v ∧ q)) ↔ ((q ∧ s) ∧ p))) → (((p ∧ t) ∧ r) ↔ ((q ∧ s) ∧ p)))
((((u → (q ∨ r)) → ((v ∨ r) ∨ s)) ∧ (((v ∨ r) ∨ s) → (u → (q ∨ r)))) → ((u → (q ∨ r)) ↔ ((v ∨ r) ∨ s)))
((((r ∧ t) → s) ∧ (((t ∧ u) → q) ∧ ((r ∧ p) ∧ s))) → ((((r ∧ t) → s) ∧ ((t ∧ u) → q)) ∧ ((r ∧ p) ∧ s)))
(((((v ∨ t) ∨ u) → ((s ∧ r) ∧ v)) ∧ (((s ∧ r) ∧ v) → ((s ∧ t) → u))) → (((v ∨ t) ∨ u) → ((s ∧ t) → u)))
((((t ∨ q) ∨ u) ∨ (((r ∧ v) ∧ u) ∨ (r ∧ (u ∨ v)))) → ((((t ∨ q) ∨ u) ∨ ((r ∧ v) ∧ u)) ∨ (r ∧ (u ∨ v))))
((((u ∧ (r ∨ s)) ∨ ((s ∧ v) ∧ q)) ∨ ((r ∧ t) ∧ u)) → ((u ∧ (r ∨ s)) ∨ (((s ∧ v) ∧ q) ∨ ((r ∧ t) ∧ u))))
(((((s ∧ v) → q) ∧ ((p ∧ r) ∧ u)) → (p → (v ∨ r))) → (((s ∧ v) → q) → (((p ∧ r) ∧ u) → (p → (v ∨ r)))))
((((t ∨ (v ∧ q)) → (q ∨ (p ∧ s))) ∧ ((q ∨ (p ∧ s)) → (r ∨ (p ∧ t)))) → ((t ∨ (v ∧ q)) → (r ∨ (p ∧ t))))
((((t ∨ (p ∧ q)) → (r → (q ∨ u))) ∧ ((r → (q ∨ u)) → (s ∧ (v ∨ t)))) → ((t ∨ (p ∧ q)) → (s ∧ (v ∨ t))))
((((u ∨ r) ∨ s) ∧ (((q ∨ r) ∨ p) ∧ ((q ∨ u) ∨ v))) → ((((u ∨ r) ∨ s) ∧ ((q ∨ r) ∨ p)) ∧ ((q ∨ u) ∨ v)))
((((q ∨ (t ∧ s)) → (u ∨ (s ∧ q))) ∧ ((u ∨ (s ∧ q)) → ((q ∨ p) ∨ v))) → ((q ∨ (t ∧ s)) → ((q ∨ p) ∨ v)))
((((p → (u ∨ s)) ∧ ((q ∨ v) ∨ r)) → ((p ∨ u) ∨ q)) → ((p → (u ∨ s)) → (((q ∨ v) ∨ r) → ((p ∨ u) ∨ q))))
(((p ∧ (u ∨ r)) ↔ (u ∨ (r ∧ v))) → (((p ∧ (u ∨ r)) ∨ ((s ∧ t) → u)) ↔ ((u ∨ (r ∧ v)) ∨ ((s ∧ t) → u))))
((((t ∧ (p ∨ s)) ∧ ((r ∧ p) ∧ s)) → (s → (r ∨ u))) → ((t ∧ (p ∨ s)) → (((r ∧ p) ∧ s) → (s → (r ∨ u)))))
((((v ∧ (q ∨ p)) ↔ (s ∨ (t ∧ q))) ∧ ((s ∨ (t ∧ q)) ↔ (t ∨ (q ∧ u)))) → ((v ∧ (q ∨ p)) ↔ (t ∨ (q ∧ u))))
(((((u ∧ s) ∧ v) → ((v ∨ p) ∨ t)) ∧ (((v ∨ p) ∨ t) → ((u ∧ s) ∧ v))) → (((u ∧ s) ∧ v) ↔ ((v ∨ p) ∨ t)))
((((s ∨ (u ∧ p)) → ((p ∧ q) ∧ v)) ∧ (((p ∧ q) ∧ v) → (s ∨ (u ∧ p)))) → ((s ∨ (u ∧ p)) ↔ ((p ∧ q) ∧ v)))
(((u ∨ (p ∧ r)) ∧ (((r ∧ u) ∧ p) ∧ (s → (p ∨ q)))) → (((u ∨ (p ∧ r)) ∧ ((r ∧ u) ∧ p)) ∧ (s → (p ∨ q))))
((((s → (p ∨ t)) ∧ ((t ∧ u) → r)) ∧ (s → (v ∨ r))) → ((s → (p ∨ t)) ∧ (((t ∧ u) → r) ∧ (s → (v ∨ r)))))
(((((p ∧ q) → t) ∧ (t → (s ∨ v))) ∧ (r ∧ (v ∨ u))) → (((p ∧ q) → t) ∧ ((t → (s ∨ v)) ∧ (r ∧ (v ∨ u)))))
(((r ∧ (v ∨ u)) → (((v ∧ t) → s) → ((r ∧ s) → q))) → (((v ∧ t) → s) → ((r ∧ (v ∨ u)) → ((r ∧ s) → q))))
(((((p ∨ u) ∨ v) ∨ (u → (q ∨ r))) ∨ (r → (q ∨ u))) → (((p ∨ u) ∨ v) ∨ ((u → (q ∨ r)) ∨ (r → (q ∨ u)))))
(((((s ∨ v) ∨ u) ∧ ((u ∨ p) ∨ v)) ∧ (v ∧ (s ∨ p))) → (((s ∨ v) ∨ u) ∧ (((u ∨ p) ∨ v) ∧ (v ∧ (s ∨ p)))))
((((v ∧ q) → r) ↔ (q → (s ∨ t))) → ((((v ∧ q) → r) ∨ ((u ∧ s) → v)) ↔ ((q → (s ∨ t)) ∨ ((u ∧ s) → v))))
(((((u ∨ p) ∨ v) → ((u ∧ p) ∧ v)) ∧ (((u ∧ p) ∧ v) → ((u ∨ p) ∨ v))) → (((u ∨ p) ∨ v) ↔ ((u ∧ p) ∧ v)))
((((s ∨ r) ∨ v) ↔ ((u ∨ t) ∨ s)) → ((((s ∨ r) ∨ v) ∧ (r ∨ (s ∧ t))) ↔ (((u ∨ t) ∨ s) ∧ (r ∨ (s ∧ t)))))
(((((u ∧ s) ∧ q) → (p ∧ (v ∨ s))) ∧ ((p ∧ (v ∨ s)) → ((t ∧ v) → p))) → (((u ∧ s) ∧ q) → ((t ∧ v) → p)))
((((v ∧ (p ∨ s)) → (p ∨ (v ∧ q))) ∧ ((p ∨ (v ∧ q)) → (v ∧ (p ∨ s)))) → ((v ∧ (p ∨ s)) ↔ (p ∨ (v ∧ q))))
((((v ∧ (p ∨ u)) → ((p ∧ q) ∧ t)) ∧ (((p ∧ q) ∧ t) → ((u ∧ s) ∧ r))) → ((v ∧ (p ∨ u)) → ((u ∧ s) ∧ r)))
(((((p ∧ s) → u) ∧ ((p ∧ u) → t)) ∧ (q ∨ (p ∧ t))) → (((p ∧ s) → u) ∧ (((p ∧ u) → t) ∧ (q ∨ (p ∧ t)))))
(((((r ∨ s) ∨ p) ∧ ((p ∧ q) → t)) ∧ ((r ∧ p) → u)) → (((r ∨ s) ∨ p) ∧ (((p ∧ q) → t) ∧ ((r ∧ p) → u))))
(((p → (q ∨ r)) ∨ (((r ∧ p) ∧ t) ∨ (p → (t ∨ u)))) → (((p → (q ∨ r)) ∨ ((r ∧ p) ∧ t)) ∨ (p → (t ∨ u))))
(((((s ∨ t) ∨ u) → ((p ∨ r) ∨ v)) ∧ (((p ∨ r) ∨ v) → ((s ∨ t) ∨ u))) → (((s ∨ t) ∨ u) ↔ ((p ∨ r) ∨ v)))
((((((u ∧ s) → q) → (p ∨ q)) ∧ ((v ∧ (t ∨ p)) → (p ∨ q))) ∧ (((u ∧ s) → q) ∨ (v ∧ (t ∨ p)))) → (p ∨ q))
((((q → (s ∨ u)) ∧ (p ∨ (v ∧ t))) → ((u ∧ t) → r)) → ((q → (s ∨ u)) → ((p ∨ (v ∧ t)) → ((u ∧ t) → r))))
(((((u ∨ r) ∨ t) ∨ (t ∨ (q ∧ p))) ∨ (t ∧ (s ∨ v))) → (((u ∨ r) ∨ t) ∨ ((t ∨ (q ∧ p)) ∨ (t ∧ (s ∨ v)))))
((((v ∨ (t ∧ q)) → (q ∨ (u ∧ s))) ∧ ((q ∨ (u ∧ s)) → (p ∧ (q ∨ v)))) → ((v ∨ (t ∧ q)) → (p ∧ (q ∨ v))))
(((t ∨ (q ∧ r)) ∨ ((v ∧ (p ∨ r)) ∨ (s ∧ (q ∨ p)))) → (((t ∨ (q ∧ r)) ∨ (v ∧ (p ∨ r))) ∨ (s ∧ (q ∨ p))))
(((((q ∧ p) → s) → (p ∨ (v ∧ r))) ∧ ((p ∨ (v ∧ r)) → ((r ∨ v) ∨ p))) → (((q ∧ p) → s) → ((r ∨ v) ∨ p)))
((((v → (p ∨ q)) ∧ ((v ∧ q) → r)) ∧ (p → (t ∨ v))) → ((v → (p ∨ q)) ∧ (((v ∧ q) → r) ∧ (p → (t ∨ v)))))
(((((t ∧ p) → v) → (r ∧ (v ∨ t))) ∧ ((r ∧ (v ∨ t)) → ((p ∧ r) ∧ t))) → (((t ∧ p) → v) → ((p ∧ r) ∧ t)))
(((((v ∨ p) ∨ r) ∨ (r → (u ∨ p))) ∨ ((u ∧ q) ∧ r)) → (((v ∨ p) ∨ r) ∨ ((r → (u ∨ p)) ∨ ((u ∧ q) ∧ r))))
(((((q ∧ t) → r) ↔ (u → (p ∨ q))) ∧ ((u → (p ∨ q)) ↔ (p ∧ (s ∨ r)))) → (((q ∧ t) → r) ↔ (p ∧ (s ∨ r))))
((((t → (s ∨ u)) ∨ (p ∨ (s ∧ u))) ∨ ((t ∧ r) → u)) → ((t → (s ∨ u)) ∨ ((p ∨ (s ∧ u)) ∨ ((t ∧ r) → u))))
(((r ∨ (s ∧ p)) ∧ ((t ∨ (u ∧ r)) ∧ ((s ∧ q) → t))) → (((r ∨ (s ∧ p)) ∧ (t ∨ (u ∧ r))) ∧ ((s ∧ q) → t)))
((((u ∧ s) ∧ t) ∧ ((p ∨ (t ∧ s)) ∧ (t ∨ (v ∧ q)))) → ((((u ∧ s) ∧ t) ∧ (p ∨ (t ∧ s))) ∧ (t ∨ (v ∧ q))))
(((p → (t ∨ r)) → ((r ∧ (q ∨ t)) → ((q ∧ s) → t))) → (((p → (t ∨ r)) ∧ (r ∧ (q ∨ t))) → ((q ∧ s) → t)))
((((v ∨ (s ∧ r)) ∧ (t ∧ (u ∨ p))) ∧ (t ∨ (v ∧ r))) → ((v ∨ (s ∧ r)) ∧ ((t ∧ (u ∨ p)) ∧ (t ∨ (v ∧ r)))))
(((u ∧ (s ∨ p)) ↔ ((r ∧ s) → v)) → (((u ∧ (s ∨ p)) ∧ ((v ∧ u) ∧ q)) ↔ (((r ∧ s) → v) ∧ ((v ∧ u) ∧ q))))
(((((q ∨ r) ∨ p) → ((s ∨ v) ∨ t)) ∧ (((s ∨ v) ∨ t) → ((q ∨ r) ∨ p))) → (((q ∨ r) ∨ p) ↔ ((s ∨ v) ∨ t)))
(((p ∨ (u ∧ q)) ↔ (p ∧ (v ∨ s))) → (((p ∨ (u ∧ q)) ∨ (t ∨ (r ∧ s))) ↔ ((p ∧ (v ∨ s)) ∨ (t ∨ (r ∧ s)))))
(((((t ∧ s) ∧ v) → ((s ∧ u) → r)) ∧ (((s ∧ u) → r) → ((t ∨ p) ∨ q))) → (((t ∧ s) ∧ v) → ((t ∨ p) ∨ q)))
(((((s ∧ r) → p) ∧ ((r ∧ t) → p)) → ((t ∨ q) ∨ r)) → (((s ∧ r) → p) → (((r ∧ t) → p) → ((t ∨ q) ∨ r))))
(((t ∨ (s ∧ v)) ∧ (((r ∧ u) ∧ s) ∧ ((r ∨ p) ∨ u))) → (((t ∨ (s ∧ v)) ∧ ((r ∧ u) ∧ s)) ∧ ((r ∨ p) ∨ u)))
((((t ∧ (p ∨ u)) → ((t ∧ v) ∧ s)) ∧ (((t ∧ v) ∧ s) → (t ∧ (p ∨ u)))) → ((t ∧ (p ∨ u)) ↔ ((t ∧ v) ∧ s)))
(((((r ∨ u) ∨ t) → (v → (u ∨ p))) ∧ ((v → (u ∨ p)) → ((r ∨ u) ∨ t))) → (((r ∨ u) ∨ t) ↔ (v → (u ∨ p))))
((((t ∨ (r ∧ v)) → (q ∧ (u ∨ s))) ∧ ((q ∧ (u ∨ s)) → ((r ∨ p) ∨ q))) → ((t ∨ (r ∧ v)) → ((r ∨ p) ∨ q)))
(((r → (u ∨ s)) ↔ (t → (q ∨ v))) → (((r → (u ∨ s)) ∧ ((t ∧ p) ∧ q)) ↔ ((t → (q ∨ v)) ∧ ((t ∧ p) ∧ q))))
((((r ∧ (p ∨ u)) ∧ ((q ∧ r) ∧ s)) ∧ ((p ∧ u) ∧ v)) → ((r ∧ (p ∨ u)) ∧ (((q ∧ r) ∧ s) ∧ ((p ∧ u) ∧ v))))
((((p → (t ∨ u)) ↔ (s → (t ∨ u))) ∧ ((s → (t ∨ u)) ↔ (r ∧ (q ∨ v)))) → ((p → (t ∨ u)) ↔ (r ∧ (q ∨ v))))
(((q ∨ (s ∧ v)) ∨ ((p → (q ∨ u)) ∨ ((r ∧ u) ∧ t))) → (((q ∨ (s ∧ v)) ∨ (p → (q ∨ u))) ∨ ((r ∧ u) ∧ t)))
((((r ∧ s) → q) → (((s ∧ q) → v) → ((u ∧ s) ∧ t))) → ((((r ∧ s) → q) ∧ ((s ∧ q) → v)) → ((u ∧ s) ∧ t)))
((((p → (u ∨ q)) ∨ ((s ∧ q) ∧ r)) ∨ (s ∧ (t ∨ v))) → ((p → (u ∨ q)) ∨ (((s ∧ q) ∧ r) ∨ (s ∧ (t ∨ v)))))
((((v ∧ (t ∨ q)) ↔ ((t ∧ s) ∧ q)) ∧ (((t ∧ s) ∧ q) ↔ (q ∧ (r ∨ u)))) → ((v ∧ (t ∨ q)) ↔ (q ∧ (r ∨ u))))
((((q ∧ p) → s) → (((u ∧ r) ∧ v) → (p ∧ (u ∨ t)))) → ((((q ∧ p) → s) ∧ ((u ∧ r) ∧ v)) → (p ∧ (u ∨ t))))
((((u ∨ (t ∧ s)) → ((r ∨ u) ∨ q)) ∧ (((r ∨ u) ∨ q) → ((q ∨ r) ∨ t))) → ((u ∨ (t ∧ s)) → ((q ∨ r) ∨ t)))
((((q → (s ∨ v)) → ((t ∨ u) ∨ s)) ∧ (((t ∨ u) ∨ s) → (r ∧ (u ∨ q)))) → ((q → (s ∨ v)) → (r ∧ (u ∨ q))))
((((u ∧ (t ∨ r)) → ((t ∧ r) ∧ p)) ∧ (((t ∧ r) ∧ p) → ((p ∨ s) ∨ r))) → ((u ∧ (t ∨ r)) → ((p ∨ s) ∨ r)))
(((v ∨ (p ∧ q)) → ((r → (u ∨ p)) → (v ∧ (s ∨ r)))) → (((v ∨ (p ∧ q)) ∧ (r → (u ∨ p))) → (v ∧ (s ∨ r))))
(((((s ∧ v) ∧ r) ∧ ((t ∧ s) ∧ r)) → ((r ∧ t) → v)) → (((s ∧ v) ∧ r) → (((t ∧ s) ∧ r) → ((r ∧ t) → v))))
(((((p ∨ u) ∨ s) ↔ (t ∧ (v ∨ s))) ∧ ((t ∧ (v ∨ s)) ↔ ((p ∨ r) ∨ v))) → (((p ∨ u) ∨ s) ↔ ((p ∨ r) ∨ v)))
(((u ∨ (s ∧ q)) ∧ (((p ∧ r) ∧ v) ∧ ((t ∨ s) ∨ u))) → (((u ∨ (s ∧ q)) ∧ ((p ∧ r) ∧ v)) ∧ ((t ∨ s) ∨ u)))
((((q ∧ t) ∧ u) → ((p ∧ (s ∨ r)) → ((u ∨ v) ∨ s))) → ((p ∧ (s ∨ r)) → (((q ∧ t) ∧ u) → ((u ∨ v) ∨ s))))
(((((u ∧ q) ∧ v) → (p ∧ (v ∨ u))) ∧ ((p ∧ (v ∨ u)) → ((u ∧ v) ∧ p))) → (((u ∧ q) ∧ v) → ((u ∧ v) ∧ p)))
((((u ∨ q) ∨ t) ∨ ((v → (u ∨ s)) ∨ ((s ∨ r) ∨ u))) → ((((u ∨ q) ∨ t) ∨ (v → (u ∨ s))) ∨ ((s ∨ r) ∨ u)))
(((((u ∨ r) ∨ p) ∧ (v ∨ (r ∧ t))) ∧ (q → (u ∨ s))) → (((u ∨ r) ∨ p) ∧ ((v ∨ (r ∧ t)) ∧ (q → (u ∨ s)))))
(((((q ∨ r) ∨ v) ↔ ((s ∧ v) → q)) ∧ (((s ∧ v) → q) ↔ ((r ∧ u) ∧ t))) → (((q ∨ r) ∨ v) ↔ ((r ∧ u) ∧ t)))
(((((t ∨ r) ∨ s) → ((t ∨ p) ∨ v)) ∧ (((t ∨ p) ∨ v) → ((q ∧ v) ∧ s))) → (((t ∨ r) ∨ s) → ((q ∧ v) ∧ s)))
((((t ∧ (r ∨ q)) ∧ ((q ∨ u) ∨ t)) → (t ∨ (p ∧ s))) → ((t ∧ (r ∨ q)) → (((q ∨ u) ∨ t) → (t ∨ (p ∧ s)))))
((((p ∨ v) ∨ q) → ((t ∧ (p ∨ v)) → ((p ∧ t) ∧ u))) → ((((p ∨ v) ∨ q) ∧ (t ∧ (p ∨ v))) → ((p ∧ t) ∧ u)))
((((q ∧ (s ∨ v)) → (r → (v ∨ s))) ∧ ((r → (v ∨ s)) → ((r ∨ p) ∨ t))) → ((q ∧ (s ∨ v)) → ((r ∨ p) ∨ t)))
((((q ∨ s) ∨ u) ∧ ((s ∧ (p ∨ r)) ∧ (t → (q ∨ v)))) → ((((q ∨ s) ∨ u) ∧ (s ∧ (p ∨ r))) ∧ (t → (q ∨ v))))
((((q ∧ p) → u) → (((t ∧ p) → q) → ((r ∧ s) ∧ q))) → ((((q ∧ p) → u) ∧ ((t ∧ p) → q)) → ((r ∧ s) ∧ q)))
(((t ∨ (q ∧ p)) ∧ (((q ∧ u) ∧ p) ∧ (q → (p ∨ t)))) → (((t ∨ (q ∧ p)) ∧ ((q ∧ u) ∧ p)) ∧ (q → (p ∨ t))))
((((q ∨ p) ∨ t) → ((t ∨ (s ∧ p)) → ((u ∨ q) ∨ t))) → ((((q ∨ p) ∨ t) ∧ (t ∨ (s ∧ p))) → ((u ∨ q) ∨ t)))
(((p ∨ (t ∧ s)) ↔ (q ∨ (p ∧ v))) → (((p ∨ (t ∧ s)) ∧ (q ∧ (p ∨ v))) ↔ ((q ∨ (p ∧ v)) ∧ (q ∧ (p ∨ v)))))
((((v ∧ (r ∨ t)) → ((s ∧ v) ∧ u)) ∧ (((s ∧ v) ∧ u) → (v ∧ (r ∨ t)))) → ((v ∧ (r ∨ t)) ↔ ((s ∧ v) ∧ u)))
((((v ∨ (t ∧ q)) → (u ∨ (t ∧ r))) ∧ ((u ∨ (t ∧ r)) → ((r ∧ q) → t))) → ((v ∨ (t ∧ q)) → ((r ∧ q) → t)))
(((p → (q ∨ r)) ∨ ((t ∧ (v ∨ r)) ∨ ((v ∧ r) ∧ s))) → (((p → (q ∨ r)) ∨ (t ∧ (v ∨ r))) ∨ ((v ∧ r) ∧ s)))
((((u ∨ r) ∨ t) ∧ ((p ∧ (t ∨ v)) ∧ ((t ∨ s) ∨ r))) → ((((u ∨ r) ∨ t) ∧ (p ∧ (t ∨ v))) ∧ ((t ∨ s) ∨ r)))
((((p ∧ q) ∧ t) → ((p ∨ (v ∧ r)) → (v ∨ (s ∧ r)))) → ((((p ∧ q) ∧ t) ∧ (p ∨ (v ∧ r))) → (v ∨ (s ∧ r))))
(((u ∧ (r ∨ p)) ↔ (t ∧ (r ∨ s))) → (((u ∧ (r ∨ p)) ∨ (u → (s ∨ p))) ↔ ((t ∧ (r ∨ s)) ∨ (u → (s ∨ p)))))
(((((p ∨ t) ∨ s) ∧ (u → (q ∨ s))) ∧ (q ∨ (s ∧ t))) → (((p ∨ t) ∨ s) ∧ ((u → (q ∨ s)) ∧ (q ∨ (s ∧ t)))))
((((v → (p ∨ r)) ∧ ((p ∨ s) ∨ q)) ∧ ((u ∧ r) → s)) → ((v → (p ∨ r)) ∧ (((p ∨ s) ∨ q) ∧ ((u ∧ r) → s))))
((((r ∧ q) ∧ t) → (((q ∨ r) ∨ p) → ((q ∨ r) ∨ v))) → ((((r ∧ q) ∧ t) ∧ ((q ∨ r) ∨ p)) → ((q ∨ r) ∨ v)))
(((p ∧ (s ∨ u)) ∧ (((q ∧ p) → t) ∧ ((s ∧ t) ∧ u))) → (((p ∧ (s ∨ u)) ∧ ((q ∧ p) → t)) ∧ ((s ∧ t) ∧ u)))
((((p → (q ∨ v)) → ((t ∧ u) → q)) ∧ (((t ∧ u) → q) → (p → (q ∨ v)))) → ((p → (q ∨ v)) ↔ ((t ∧ u) → q)))
((((s ∨ (v ∧ r)) → (p → (q ∨ r))) ∧ ((p → (q ∨ r)) → (s ∨ (v ∧ r)))) → ((s ∨ (v ∧ r)) ↔ (p → (q ∨ r))))
(((((v ∨ (p ∧ r)) → (t ∨ (u ∧ s))) ∧ ((¬t ∨ u) → r)) ∧ ((v ∨ (p ∧ r)) ∨ (¬t ∨ u))) → ((t ∨ (u ∧ s)) ∨ r))
((((q ∧ ¬r) → (r → (u ∨ s))) ∧ ((q ∧ ¬r) → ((q ∧ v) ∧ r))) → ((q ∧ ¬r) → ((r → (u ∨ s)) ∧ ((q ∧ v) ∧ r))))
((((¬s ∨ t) → ((p ∨ t) ∨ u)) ∧ ((¬s ∨ t) → ((s ∧ u) → v))) → ((¬s ∨ t) → (((p ∨ t) ∨ u) ∧ ((s ∧ u) → v))))
(((((s → (t ∨ q)) → ((q ∧ p) ∧ t)) ∧ (¬((s → (t ∨ q))) → p)) ∧ ((((q ∧ p) ∧ t) ∨ p) → (q ∨ v))) → (q ∨ v))
(((((t ∧ v) → (¬u ∨ r)) ∧ ((p ∧ ¬q) → ((u ∧ v) → p))) ∧ ((t ∧ v) ∨ (p ∧ ¬q))) → ((¬u ∨ r) ∨ ((u ∧ v) → p)))
((((((t → (p ∨ r)) ∨ ((r ∨ s) ∨ q)) ∨ ((s ∧ p) ∧ q)) ∧ ¬((t → (p ∨ r)))) ∧ ¬(((r ∨ s) ∨ q))) → ((s ∧ p) ∧ q))
((((((s ∨ (q ∧ v)) ∨ ((r ∧ p) → u)) ∨ (r ∧ (t ∨ u))) ∧ ¬((s ∨ (q ∧ v)))) ∧ ¬(((r ∧ p) → u))) → (r ∧ (t ∨ u)))
((((((r ∧ (t ∨ q)) ∨ (t ∧ (u ∨ v))) ∨ ((u ∧ s) → p)) ∧ ¬((r ∧ (t ∨ q)))) ∧ ¬((t ∧ (u ∨ v)))) → ((u ∧ s) → p))
((((((t ∧ (u ∨ q)) ∨ (q → (t ∨ p))) ∨ (s ∨ (q ∧ v))) ∧ ¬((t ∧ (u ∨ q)))) ∧ ¬((q → (t ∨ p)))) → (s ∨ (q ∧ v)))
(((((((q ∨ p) ∨ s) ∨ (q ∧ (v ∨ r))) ∨ (s ∨ (u ∧ t))) ∧ ¬(((q ∨ p) ∨ s))) ∧ ¬((q ∧ (v ∨ r)))) → (s ∨ (u ∧ t)))
(((((((r ∧ s) → v) ∨ ((t ∧ v) ∧ u)) ∨ (r → (p ∨ s))) ∧ ¬(((r ∧ s) → v))) ∧ ¬(((t ∧ v) ∧ u))) → (r → (p ∨ s)))
(((((((r ∧ u) ∧ s) ∨ (v → (p ∨ u))) ∨ ((u ∨ q) ∨ s)) ∧ ¬(((r ∧ u) ∧ s))) ∧ ¬((v → (p ∨ u)))) → ((u ∨ q) ∨ s))
(((((((q ∧ u) → p) ∨ (u ∨ (s ∧ p))) ∨ ((v ∨ r) ∨ s)) ∧ ¬(((q ∧ u) → p))) ∧ ¬((u ∨ (s ∧ p)))) → ((v ∨ r) ∨ s))
(((((v → r) → (u → (t ∨ p))) ∧ ((p → (s ∨ t)) → (u → (t ∨ p)))) ∧ ((v → r) ∨ (p → (s ∨ t)))) → (u → (t ∨ p)))
(((((q ↔ p) → (r ∧ (t ∨ v))) ∧ (((p ∨ r) ∨ t) → (r ∧ (t ∨ v)))) ∧ ((q ↔ p) ∨ ((p ∨ r) ∨ t))) → (r ∧ (t ∨ v)))
(((((r ∧ t) → p) → ((r ∨ u) ∨ s)) ∧ (((r ∧ t) → p) → (v ∧ t))) → (((r ∧ t) → p) → (((r ∨ u) ∨ s) ∧ (v ∧ t))))
(((((q ↔ v) → ((u ∧ s) ∧ r)) ∧ (((u ∨ s) ∨ r) → ((u ∧ s) ∧ r))) ∧ ((q ↔ v) ∨ ((u ∨ s) ∨ r))) → ((u ∧ s) ∧ r))
((((t ∧ (u ∨ s)) → (q ∧ v)) ∧ ((t ∧ (u ∨ s)) → ((q ∧ v) → t))) → ((t ∧ (u ∨ s)) → ((q ∧ v) ∧ ((q ∧ v) → t))))
(((((p ∨ (s ∧ q)) → ((p ∨ t) ∨ r)) ∧ ((r → q) → ((p ∨ t) ∨ r))) ∧ ((p ∨ (s ∧ q)) ∨ (r → q))) → ((p ∨ t) ∨ r))
((((v → (u ∨ t)) → ((q ∧ r) ∧ p)) ∧ ((v → (u ∨ t)) → (u ↔ v))) → ((v → (u ∨ t)) → (((q ∧ r) ∧ p) ∧ (u ↔ v))))
(((((q ∧ t) ∧ r) → (q ↔ t)) ∧ (((q ∧ t) ∧ r) → (s → (v ∨ t)))) → (((q ∧ t) ∧ r) → ((q ↔ t) ∧ (s → (v ∨ t)))))
((((u ∨ (t ∧ p)) → (u → v)) ∧ ((u ∨ (t ∧ p)) → ((u ∨ p) ∨ v))) → ((u ∨ (t ∧ p)) → ((u → v) ∧ ((u ∨ p) ∨ v))))
((((v ∨ (t ∧ r)) → (p → (r ∨ v))) ∧ ((v ∨ (t ∧ r)) → (p ↔ v))) → ((v ∨ (t ∧ r)) → ((p → (r ∨ v)) ∧ (p ↔ v))))
(((((v ∨ (p ∧ t)) → ((u ∧ p) ∧ r)) ∧ (¬((v ∨ (p ∧ t))) → ((u ∧ p) ∧ r))) ∧ (((u ∧ p) ∧ r) → (s ↔ q))) → (s ↔ q))
(((((r ∨ (u ∧ p)) → (s ∧ v)) ∧ (((p ∧ v) → u) → (t ∨ u))) ∧ ((r ∨ (u ∧ p)) ∨ ((p ∧ v) → u))) → ((s ∧ v) ∨ (t ∨ u)))
(((((v ↔ u) → (t ∨ (r ∧ s))) ∧ ((p ∧ r) → ((u ∧ r) → p))) ∧ ((v ↔ u) ∧ (p ∧ r))) → ((t ∨ (r ∧ s)) ∧ ((u ∧ r) → p)))
((((((u ∨ q) ∨ v) → (v ∧ (u ∨ q))) ∧ ((v ∧ (u ∨ q)) → (r ↔ q))) ∧ ((r ↔ q) → (v ∨ q))) → (((u ∨ q) ∨ v) → (v ∨ q)))
(((((p → v) → (t ∨ u)) ∧ (((s ∧ t) ∧ q) → (p ∨ (q ∧ r)))) ∧ ((p → v) ∨ ((s ∧ t) ∧ q))) → ((t ∨ u) ∨ (p ∨ (q ∧ r))))
(((((p ∧ ¬v) → (v ∨ s)) ∧ ((v ∨ s) → ((t ∨ v) ∨ u))) ∧ (((t ∨ v) ∨ u) → (s ∧ (p ∨ q)))) → ((p ∧ ¬v) → (s ∧ (p ∨ q))))
((((((t ∨ q) ∨ s) → (q ↔ v)) ∧ ((¬p ∨ s) → (u ∨ (r ∧ q)))) ∧ (((t ∨ q) ∨ s) ∨ (¬p ∨ s))) → ((q ↔ v) ∨ (u ∨ (r ∧ q))))
((((¬r → (s ∧ (v ∨ r))) ∧ ((s ∧ (v ∨ r)) → ((u ∧ s) ∧ r))) ∧ (((u ∧ s) ∧ r) → ((r ∧ q) → s))) → (¬r → ((r ∧ q) → s)))
(((((v → (q ∨ u)) → (¬u ∨ p)) ∧ ((q ∨ s) → (t ∨ (p ∧ q)))) ∧ ((v → (q ∨ u)) ∨ (q ∨ s))) → ((¬u ∨ p) ∨ (t ∨ (p ∧ q))))
(((((¬q ∨ r) → (¬q ∨ v)) ∧ (((q ∧ r) ∧ v) → (v ∧ (u ∨ p)))) ∧ ((¬q ∨ r) ∧ ((q ∧ r) ∧ v))) → ((¬q ∨ v) ∧ (v ∧ (u ∨ p))))
((((v ∨ (p ∧ q)) → (q ∧ (t ∨ p))) ∧ ((v ∨ (p ∧ q)) → ((p ∧ s) ∧ u))) → ((v ∨ (p ∧ q)) → ((q ∧ (t ∨ p)) ∧ ((p ∧ s) ∧ u))))
(((((r → (q ∨ s)) → (t ∧ (r ∨ s))) ∧ (((t ∧ r) → q) → (t ∧ (r ∨ s)))) ∧ ((r → (q ∨ s)) ∨ ((t ∧ r) → q))) → (t ∧ (r ∨ s)))
((((((q ∧ r) ∧ u) → (p ∧ (v ∨ q))) ∧ ((r → (q ∨ p)) → (p ∧ (v ∨ q)))) ∧ (((q ∧ r) ∧ u) ∨ (r → (q ∨ p)))) → (p ∧ (v ∨ q)))
((((((r ∧ t) → s) → (p ∨ (r ∧ u))) ∧ ((t ∧ (p ∨ v)) → (p ∨ (r ∧ u)))) ∧ (((r ∧ t) → s) ∨ (t ∧ (p ∨ v)))) → (p ∨ (r ∧ u)))
((((((v ∧ p) ∧ r) → (s ∧ (r ∨ v))) ∧ ((r ∧ (v ∨ u)) → (s ∧ (r ∨ v)))) ∧ (((v ∧ p) ∧ r) ∨ (r ∧ (v ∨ u)))) → (s ∧ (r ∨ v)))
(((((r ∧ (t ∨ q)) → (q ∨ (u ∧ v))) ∧ (((r ∧ t) → v) → (q ∨ (u ∧ v)))) ∧ ((r ∧ (t ∨ q)) ∨ ((r ∧ t) → v))) → (q ∨ (u ∧ v)))
((((((u ∧ q) → v) → (v ∨ (p ∧ s))) ∧ (((u ∧ r) ∧ p) → (v ∨ (p ∧ s)))) ∧ (((u ∧ q) → v) ∨ ((u ∧ r) ∧ p))) → (v ∨ (p ∧ s)))
((((((u ∨ v) ∨ s) → (p ∧ (t ∨ u))) ∧ ((t → (p ∨ r)) → (p ∧ (t ∨ u)))) ∧ (((u ∨ v) ∨ s) ∨ (t → (p ∨ r)))) → (p ∧ (t ∨ u)))
((((t → (r ∨ q)) → (s ∨ (q ∧ v))) ∧ ((t → (r ∨ q)) → (s ∧ (p ∨ t)))) → ((t → (r ∨ q)) → ((s ∨ (q ∧ v)) ∧ (s ∧ (p ∨ t)))))
(((((p ∨ t) ∨ s) → (v ∨ (p ∧ u))) ∧ (((p ∨ t) ∨ s) → ((u ∧ v) ∧ s))) → (((p ∨ t) ∨ s) → ((v ∨ (p ∧ u)) ∧ ((u ∧ v) ∧ s))))
(((((t ∨ (s ∧ v)) → ((t ∧ q) ∧ s)) ∧ ((s → (v ∨ u)) → ((t ∧ q) ∧ s))) ∧ ((t ∨ (s ∧ v)) ∨ (s → (v ∨ u)))) → ((t ∧ q) ∧ s))
((((r → (u ∨ q)) → (t → (q ∨ v))) ∧ ((r → (u ∨ q)) → (u ∧ (q ∨ p)))) → ((r → (u ∨ q)) → ((t → (q ∨ v)) ∧ (u ∧ (q ∨ p)))))
(((((r ∨ (v ∧ q)) → ((r ∨ u) ∨ v)) ∧ ((p → (u ∨ q)) → ((r ∨ u) ∨ v))) ∧ ((r ∨ (v ∧ q)) ∨ (p → (u ∨ q)))) → ((r ∨ u) ∨ v))
((((((v ∨ u) ∨ s) → (s ∧ (v ∨ u))) ∧ (((u ∨ p) ∨ t) → (s ∧ (v ∨ u)))) ∧ (((v ∨ u) ∨ s) ∨ ((u ∨ p) ∨ t))) → (s ∧ (v ∨ u)))
(((((u ∧ (v ∨ s)) → ((t ∨ r) ∨ q)) ∧ (((s ∨ p) ∨ q) → ((t ∨ r) ∨ q))) ∧ ((u ∧ (v ∨ s)) ∨ ((s ∨ p) ∨ q))) → ((t ∨ r) ∨ q))
((((((v ∧ r) → p) → (u ∨ (r ∧ v))) ∧ ((s → (u ∨ r)) → (u ∨ (r ∧ v)))) ∧ (((v ∧ r) → p) ∨ (s → (u ∨ r)))) → (u ∨ (r ∧ v)))
(((((r → (t ∨ s)) → ((p ∨ q) ∨ v)) ∧ ((v → (q ∨ p)) → ((p ∨ q) ∨ v))) ∧ ((r → (t ∨ s)) ∨ (v → (q ∨ p)))) → ((p ∨ q) ∨ v))
(((((p ∨ (u ∧ r)) → ((u ∧ r) ∧ t)) ∧ (((u ∧ s) → p) → ((u ∧ r) ∧ t))) ∧ ((p ∨ (u ∧ r)) ∨ ((u ∧ s) → p))) → ((u ∧ r) ∧ t))
(((((r → (t ∨ s)) → (q → (s ∨ t))) ∧ (((r ∨ u) ∨ p) → (q → (s ∨ t)))) ∧ ((r → (t ∨ s)) ∨ ((r ∨ u) ∨ p))) → (q → (s ∨ t)))
(((((p ∧ (q ∨ r)) → (p ∨ (s ∧ v))) ∧ (((v ∨ p) ∨ u) → (p ∨ (s ∧ v)))) ∧ ((p ∧ (q ∨ r)) ∨ ((v ∨ p) ∨ u))) → (p ∨ (s ∧ v)))
((((((q ∧ t) → v) → ((v ∧ p) → q)) ∧ (((r ∧ v) ∧ p) → ((v ∧ p) → q))) ∧ (((q ∧ t) → v) ∨ ((r ∧ v) ∧ p))) → ((v ∧ p) → q))
((((v ∧ (s ∨ p)) → ((t ∧ s) ∧ q)) ∧ ((v ∧ (s ∨ p)) → ((t ∧ u) → s))) → ((v ∧ (s ∨ p)) → (((t ∧ s) ∧ q) ∧ ((t ∧ u) → s))))
(((((u → (v ∨ r)) → ((v ∧ s) ∧ p)) ∧ ((p ∧ (q ∨ r)) → ((v ∧ s) ∧ p))) ∧ ((u → (v ∨ r)) ∨ (p ∧ (q ∨ r)))) → ((v ∧ s) ∧ p))
(((((v ∨ r) ∨ t) → ((v ∨ t) ∨ r)) ∧ (((v ∨ r) ∨ t) → (v ∨ (u ∧ p)))) → (((v ∨ r) ∨ t) → (((v ∨ t) ∨ r) ∧ (v ∨ (u ∧ p)))))
(((((u ∨ (v ∧ q)) → ((t ∧ r) ∧ p)) ∧ (¬((u ∨ (v ∧ q))) → ((t ∧ r) ∧ p))) ∧ (((t ∧ r) ∧ p) → ((s ∨ r) ∨ u))) → ((s ∨ r) ∨ u))
(((((u → (t ∨ p)) → ((r ∧ u) → p)) ∧ (¬((u → (t ∨ p))) → ((r ∧ u) → p))) ∧ (((r ∧ u) → p) → (v → (r ∨ s)))) → (v → (r ∨ s)))
(((((r ∧ (v ∨ p)) → ((t ∨ u) ∨ v)) ∧ (¬((r ∧ (v ∨ p))) → ((t ∨ u) ∨ v))) ∧ (((t ∨ u) ∨ v) → (p → (q ∨ u)))) → (p → (q ∨ u)))
(((((t → (v ∨ r)) → (r ∧ (q ∨ v))) ∧ (((r ∨ s) ∨ q) → (r → t))) ∧ ((t → (v ∨ r)) ∨ ((r ∨ s) ∨ q))) → ((r ∧ (q ∨ v)) ∨ (r → t)))
(((((p → (q ∨ t)) → ((r ∨ s) ∨ t)) ∧ (((t ∧ q) → r) → (u → s))) ∧ ((p → (q ∨ t)) ∧ ((t ∧ q) → r))) → (((r ∨ s) ∨ t) ∧ (u → s)))
(((((r ∨ p) → (q → (u ∨ t))) ∧ ((q → (u ∨ t)) → (p ∨ (q ∧ u)))) ∧ ((p ∨ (q ∧ u)) → (s ∧ (v ∨ t)))) → ((r ∨ p) → (s ∧ (v ∨ t))))
(((((q → (p ∨ s)) → (s ∧ q)) ∧ (((s ∨ t) ∨ u) → (u ∧ (p ∨ t)))) ∧ ((q → (p ∨ s)) ∧ ((s ∨ t) ∨ u))) → ((s ∧ q) ∧ (u ∧ (p ∨ t))))
(((((s ∨ q) → ((r ∧ u) → q)) ∧ ((s → (u ∨ v)) → (v → (r ∨ s)))) ∧ ((s ∨ q) ∧ (s → (u ∨ v)))) → (((r ∧ u) → q) ∧ (v → (r ∨ s))))
((((((v ∧ u) → t) → ((s ∨ v) ∨ u)) ∧ ((u ∧ (s ∨ r)) → (q → v))) ∧ (((v ∧ u) → t) ∨ (u ∧ (s ∨ r)))) → (((s ∨ v) ∨ u) ∨ (q → v)))
((((((u ∧ s) → p) → (v ∧ u)) ∧ ((v ∧ u) → (q ∧ (t ∨ p)))) ∧ ((q ∧ (t ∨ p)) → (q ∧ (s ∨ p)))) → (((u ∧ s) → p) → (q ∧ (s ∨ p))))
(((((v → (t ∨ p)) → (v → (u ∨ q))) ∧ ((p ∨ r) → (t ∨ (u ∧ s)))) ∧ ((v → (t ∨ p)) ∨ (p ∨ r))) → ((v → (u ∨ q)) ∨ (t ∨ (u ∧ s))))
(((((q → (s ∨ v)) → (s ∨ (r ∧ v))) ∧ (((v ∨ p) ∨ s) → (t ↔ q))) ∧ ((q → (s ∨ v)) ∧ ((v ∨ p) ∨ s))) → ((s ∨ (r ∧ v)) ∧ (t ↔ q)))
(((((q ∧ (v ∨ p)) → (t ∧ (p ∨ v))) ∧ ((s ∧ t) → (q ∨ (t ∧ v)))) ∧ ((q ∧ (v ∨ p)) ∨ (s ∧ t))) → ((t ∧ (p ∨ v)) ∨ (q ∨ (t ∧ v))))
((((((p ∧ r) → v) → (v ∨ r)) ∧ ((q → (r ∨ v)) → (r ∧ (s ∨ q)))) ∧ (((p ∧ r) → v) ∧ (q → (r ∨ v)))) → ((v ∨ r) ∧ (r ∧ (s ∨ q))))
((((((r ∧ s) → p) → (v → (t ∨ p))) ∧ ((r ↔ p) → (s ∨ (r ∧ t)))) ∧ (((r ∧ s) → p) ∧ (r ↔ p))) → ((v → (t ∨ p)) ∧ (s ∨ (r ∧ t))))
(((((q → (p ∨ t)) → (u ∧ p)) ∧ ((q → (u ∨ r)) → ((s ∧ t) → r))) ∧ ((q → (p ∨ t)) ∧ (q → (u ∨ r)))) → ((u ∧ p) ∧ ((s ∧ t) → r)))
((((((t ∧ v) → s) → (r ∨ (p ∧ u))) ∧ ((¬p ∨ r) → (s → (p ∨ r)))) ∧ (((t ∧ v) → s) ∨ (¬p ∨ r))) → ((r ∨ (p ∧ u)) ∨ (s → (p ∨ r))))
(((((q ∧ (u ∨ r)) → (p ∨ (u ∧ s))) ∧ (((t ∧ r) → u) → (s ∧ ¬r))) ∧ ((q ∧ (u ∨ r)) ∧ ((t ∧ r) → u))) → ((p ∨ (u ∧ s)) ∧ (s ∧ ¬r)))
(((((p ∧ (u ∨ q)) → ((r ∧ v) ∧ t)) ∧ ((¬s ∨ v) → (t ∨ (q ∧ p)))) ∧ ((p ∧ (u ∨ q)) ∧ (¬s ∨ v))) → (((r ∧ v) ∧ t) ∧ (t ∨ (q ∧ p))))
(((((t → (r ∨ v)) → (¬r ∨ s)) ∧ ((u → (r ∨ s)) → ((u ∨ v) ∨ t))) ∧ ((t → (r ∨ v)) ∧ (u → (r ∨ s)))) → ((¬r ∨ s) ∧ ((u ∨ v) ∨ t)))
(((((s ∧ ¬q) → (t ∧ (s ∨ v))) ∧ (((r ∧ p) ∧ s) → (u ∧ (v ∨ r)))) ∧ ((s ∧ ¬q) ∧ ((r ∧ p) ∧ s))) → ((t ∧ (s ∨ v)) ∧ (u ∧ (v ∨ r))))
(((((v ∨ (u ∧ p)) → ((u ∧ s) → p)) ∧ ((¬t ∨ s) → ((r ∧ t) → p))) ∧ ((v ∨ (u ∧ p)) ∧ (¬t ∨ s))) → (((u ∧ s) → p) ∧ ((r ∧ t) → p)))
(((((s ∨ (t ∧ r)) → (p ∧ ¬q)) ∧ ((p ∧ ¬q) → (s ∨ (v ∧ t)))) ∧ ((s ∨ (v ∧ t)) → ((u ∧ v) ∧ r))) → ((s ∨ (t ∧ r)) → ((u ∧ v) ∧ r)))
(((((r → (q ∨ v)) → (v ∨ (s ∧ p))) ∧ (((q ∧ r) → v) → (p → (s ∨ r)))) ∧ ((r → (q ∨ v)) ∧ ((q ∧ r) → v))) → ((v ∨ (s ∧ p)) ∧ (p → (s ∨ r))))
((((((v ∧ q) → s) → ((p ∧ q) ∧ v)) ∧ (((p ∧ q) ∧ v) → ((r ∧ u) ∧ s))) ∧ (((r ∧ u) ∧ s) → ((v ∨ p) ∨ t))) → (((v ∧ q) → s) → ((v ∨ p) ∨ t)))
(((((v → (t ∨ s)) → (r → (u ∨ q))) ∧ (((q ∧ p) → t) → (u ∨ (p ∧ q)))) ∧ ((v → (t ∨ s)) ∨ ((q ∧ p) → t))) → ((r → (u ∨ q)) ∨ (u ∨ (p ∧ q))))
(((((t ∨ (s ∧ v)) → (p ∨ (q ∧ s))) ∧ ((t ∧ (s ∨ u)) → ((p ∨ q) ∨ s))) ∧ ((t ∨ (s ∧ v)) ∧ (t ∧ (s ∨ u)))) → ((p ∨ (q ∧ s)) ∧ ((p ∨ q) ∨ s)))
((((((p ∨ q) ∨ u) → ((r ∨ q) ∨ s)) ∧ (((r ∨ u) ∨ q) → (q ∧ (p ∨ s)))) ∧ (((p ∨ q) ∨ u) ∨ ((r ∨ u) ∨ q))) → (((r ∨ q) ∨ s) ∨ (q ∧ (p ∨ s))))
(((((p ∨ (s ∧ t)) → (v ∧ (u ∨ r))) ∧ (((t ∨ s) ∨ q) → ((p ∨ u) ∨ r))) ∧ ((p ∨ (s ∧ t)) ∨ ((t ∨ s) ∨ q))) → ((v ∧ (u ∨ r)) ∨ ((p ∨ u) ∨ r)))
(((((r ∨ (u ∧ q)) → (r ∨ (u ∧ s))) ∧ (((u ∧ s) → v) → (p ∧ (q ∨ r)))) ∧ ((r ∨ (u ∧ q)) ∧ ((u ∧ s) → v))) → ((r ∨ (u ∧ s)) ∧ (p ∧ (q ∨ r))))
((((((q ∧ t) ∧ r) → ((s ∧ q) → v)) ∧ ((p ∧ (s ∨ u)) → ((r ∧ v) ∧ t))) ∧ (((q ∧ t) ∧ r) ∨ (p ∧ (s ∨ u)))) → (((s ∧ q) → v) ∨ ((r ∧ v) ∧ t)))
((((((v ∨ r) ∨ s) → (v → (q ∨ p))) ∧ ((t → (v ∨ r)) → (s ∨ (v ∧ t)))) ∧ (((v ∨ r) ∨ s) ∧ (t → (v ∨ r)))) → ((v → (q ∨ p)) ∧ (s ∨ (v ∧ t))))
(((((p ∨ (s ∧ u)) → ((q ∨ p) ∨ v)) ∧ (((t ∨ q) ∨ p) → ((v ∨ u) ∨ t))) ∧ ((p ∨ (s ∧ u)) ∨ ((t ∨ q) ∨ p))) → (((q ∨ p) ∨ v) ∨ ((v ∨ u) ∨ t)))
(((((q ∧ (v ∨ s)) → ((q ∧ t) → r)) ∧ ((q ∨ (r ∧ s)) → ((p ∧ r) → t))) ∧ ((q ∧ (v ∨ s)) ∧ (q ∨ (r ∧ s)))) → (((q ∧ t) → r) ∧ ((p ∧ r) → t)))
((((((v ∧ s) → p) → ((s ∧ r) → u)) ∧ ((v ∨ (r ∧ p)) → (u ∨ (v ∧ s)))) ∧ (((v ∧ s) → p) ∨ (v ∨ (r ∧ p)))) → (((s ∧ r) → u) ∨ (u ∨ (v ∧ s))))
((((((s ∧ q) ∧ u) → (q ∨ (s ∧ v))) ∧ ((v → (r ∨ s)) → (v ∧ (p ∨ r)))) ∧ (((s ∧ q) ∧ u) ∧ (v → (r ∨ s)))) → ((q ∨ (s ∧ v)) ∧ (v ∧ (p ∨ r))))
(((((u → (s ∨ v)) → (t ∧ (q ∨ p))) ∧ ((q ∧ (v ∨ p)) → ((u ∧ t) → s))) ∧ ((u → (s ∨ v)) ∨ (q ∧ (v ∨ p)))) → ((t ∧ (q ∨ p)) ∨ ((u ∧ t) → s)))
((((((p ∧ q) ∧ t) → ((v ∨ r) ∨ q)) ∧ (((p ∨ s) ∨ r) → ((v ∧ u) ∧ q))) ∧ (((p ∧ q) ∧ t) ∧ ((p ∨ s) ∨ r))) → (((v ∨ r) ∨ q) ∧ ((v ∧ u) ∧ q)))
(((((q → (p ∨ v)) → ((t ∧ v) → p)) ∧ (((p ∧ q) → u) → ((q ∧ s) ∧ p))) ∧ ((q → (p ∨ v)) ∨ ((p ∧ q) → u))) → (((t ∧ v) → p) ∨ ((q ∧ s) ∧ p)))
((((((u ∧ q) ∧ t) → (u ∨ (s ∧ q))) ∧ ((r ∨ (p ∧ s)) → ((t ∧ s) ∧ r))) ∧ (((u ∧ q) ∧ t) ∨ (r ∨ (p ∧ s)))) → ((u ∨ (s ∧ q)) ∨ ((t ∧ s) ∧ r)))
((((((t ∧ s) ∧ r) → (v ∨ (s ∧ q))) ∧ ((q → (u ∨ r)) → ((v ∨ p) ∨ t))) ∧ (((t ∧ s) ∧ r) ∨ (q → (u ∨ r)))) → ((v ∨ (s ∧ q)) ∨ ((v ∨ p) ∨ t)))
((((((v ∧ q) → s) → (p ∨ (s ∧ u))) ∧ ((p ∨ (s ∧ u)) → (t → (r ∨ p)))) ∧ ((t → (r ∨ p)) → (v ∨ (q ∧ u)))) → (((v ∧ q) → s) → (v ∨ (q ∧ u))))
(((((u → (t ∨ v)) → ((t ∨ s) ∨ q)) ∧ (((v ∧ u) → t) → ((p ∧ u) → v))) ∧ ((u → (t ∨ v)) ∨ ((v ∧ u) → t))) → (((t ∨ s) ∨ q) ∨ ((p ∧ u) → v)))
(((((r ∨ (s ∧ t)) → ((u ∨ p) ∨ r)) ∧ ((v ∨ (s ∧ p)) → ((s ∧ r) → q))) ∧ ((r ∨ (s ∧ t)) ∧ (v ∨ (s ∧ p)))) → (((u ∨ p) ∨ r) ∧ ((s ∧ r) → q)))
((((((p ∨ u) ∨ r) → ((p ∧ s) ∧ v)) ∧ ((r → (s ∨ t)) → (v → (p ∨ s)))) ∧ (((p ∨ u) ∨ r) ∧ (r → (s ∨ t)))) → (((p ∧ s) ∧ v) ∧ (v → (p ∨ s))))
((((((q ∧ t) → u) → ((v ∧ t) → r)) ∧ ((r ∧ (u ∨ t)) → (r ∨ (t ∧ s)))) ∧ (((q ∧ t) → u) ∧ (r ∧ (u ∨ t)))) → (((v ∧ t) → r) ∧ (r ∨ (t ∧ s))))
(((((q → (s ∨ t)) → ((t ∧ v) → p)) ∧ ((t ∧ (u ∨ q)) → ((u ∧ t) → p))) ∧ ((q → (s ∨ t)) ∨ (t ∧ (u ∨ q)))) → (((t ∧ v) → p) ∨ ((u ∧ t) → p)))
((((((p ∧ u) ∧ v) → ((r ∨ v) ∨ p)) ∧ (((s ∨ u) ∨ r) → (t → (p ∨ r)))) ∧ (((p ∧ u) ∧ v) ∧ ((s ∨ u) ∨ r))) → (((r ∨ v) ∨ p) ∧ (t → (p ∨ r))))
((((((q ∧ s) → p) → (p ∧ (s ∨ u))) ∧ (((s ∨ v) ∨ t) → ((r ∨ s) ∨ q))) ∧ (((q ∧ s) → p) ∨ ((s ∨ v) ∨ t))) → ((p ∧ (s ∨ u)) ∨ ((r ∨ s) ∨ q)))
((((((v ∨ s) ∨ u) → (t ∨ (r ∧ u))) ∧ (((u ∨ r) ∨ v) → ((u ∨ v) ∨ s))) ∧ (((v ∨ s) ∨ u) ∧ ((u ∨ r) ∨ v))) → ((t ∨ (r ∧ u)) ∧ ((u ∨ v) ∨ s)))
(((((t → (p ∨ r)) → ((t ∧ r) → u)) ∧ (¬((t → (p ∨ r))) → ((v ∨ p) ∨ t))) ∧ ((((t ∧ r) → u) ∨ ((v ∨ p) ∨ t)) → ((s ∨ q) ∨ u))) → ((s ∨ q) ∨ u))
((((((u ∨ r) ∨ p) → (q ∨ (u ∧ v))) ∧ (¬(((u ∨ r) ∨ p)) → (v → (s ∨ q)))) ∧ (((q ∨ (u ∧ v)) ∨ (v → (s ∨ q))) → ((u ∧ p) ∧ t))) → ((u ∧ p) ∧ t))
((((((s ∧ r) → v) → (v ∨ (r ∧ u))) ∧ (¬(((s ∧ r) → v)) → (q ∧ (v ∨ p)))) ∧ (((v ∨ (r ∧ u)) ∨ (q ∧ (v ∨ p))) → (p ∧ (t ∨ v)))) → (p ∧ (t ∨ v)))
((((((u ∧ p) ∧ t) → ((u ∧ r) ∧ q)) ∧ (¬(((u ∧ p) ∧ t)) → ((v ∧ s) ∧ r))) ∧ ((((u ∧ r) ∧ q) ∨ ((v ∧ s) ∧ r)) → ((p ∧ q) ∧ v))) → ((p ∧ q) ∧ v))
(((((t → (q ∨ p)) → (u → (t ∨ q))) ∧ (¬((t → (q ∨ p))) → (u ∧ (v ∨ p)))) ∧ (((u → (t ∨ q)) ∨ (u ∧ (v ∨ p))) → (u ∧ (p ∨ s)))) → (u ∧ (p ∨ s)))
(((((p → (v ∨ q)) → ((r ∧ u) → s)) ∧ (¬((p → (v ∨ q))) → ((v ∧ p) ∧ u))) ∧ ((((r ∧ u) → s) ∨ ((v ∧ p) ∧ u)) → (v ∧ (t ∨ r)))) → (v ∧ (t ∨ r)))
((((((q ∧ p) ∧ t) → ((u ∨ p) ∨ s)) ∧ (¬(((q ∧ p) ∧ t)) → ((s ∨ v) ∨ p))) ∧ ((((u ∨ p) ∨ s) ∨ ((s ∨ v) ∨ p)) → ((r ∧ s) → p))) → ((r ∧ s) → p))
((((((t ∧ s) ∧ p) → (r ∨ (q ∧ s))) ∧ (¬(((t ∧ s) ∧ p)) → ((t ∧ u) ∧ q))) ∧ (((r ∨ (q ∧ s)) ∨ ((t ∧ u) ∧ q)) → (r → (p ∨ v)))) → (r → (p ∨ v)))
((((((u ∨ p) ∨ t) → ((v ∧ u) ∧ r)) ∧ (¬(((u ∨ p) ∨ t)) → (t ∨ (p ∧ v)))) ∧ ((((v ∧ u) ∧ r) ∨ (t ∨ (p ∧ v))) → ((q ∨ p) ∨ r))) → ((q ∨ p) ∨ r))
((((((v ∧ q) → (q ∨ (r ∧ t))) ∧ ((t ∧ (r ∨ q)) → (r ∧ (p ∨ t)))) ∧ (((q ∨ (r ∧ t)) ∧ (r ∧ (p ∨ t))) → (p → s))) ∧ ((v ∧ q) ∧ (t ∧ (r ∨ q)))) → (p → s))
((((((q ∧ t) → ((u ∧ r) → q)) ∧ (((q ∧ u) → v) → (r ∧ (t ∨ p)))) ∧ ((((u ∧ r) → q) ∧ (r ∧ (t ∨ p))) → (r → (p ∨ t)))) ∧ ((q ∧ t) ∧ ((q ∧ u) → v))) → (r → (p ∨ t)))
(((((((p ∨ u) ∨ t) → ((s ∧ r) → q)) ∧ ((p ∧ (v ∨ t)) → ((t ∧ q) → p))) ∧ ((((s ∧ r) → q) ∧ ((t ∧ q) → p)) → (r ∧ q))) ∧ (((p ∨ u) ∨ t) ∧ (p ∧ (v ∨ t)))) → (r ∧ q))
(((((((t ∧ u) → s) → (u → (q ∨ s))) ∧ ((t ∧ (u ∨ s)) → ((v ∨ u) ∨ p))) ∧ (((u → (q ∨ s)) ∧ ((v ∨ u) ∨ p)) → (p ∨ u))) ∧ (((t ∧ u) → s) ∧ (t ∧ (u ∨ s)))) → (p ∨ u))
(((((((u ∧ s) ∧ v) → ((t ∨ r) ∨ v)) ∧ (((t ∧ q) → p) → (r ∧ (s ∨ p)))) ∧ ((((t ∨ r) ∨ v) ∧ (r ∧ (s ∨ p))) → (r ∨ (p ∧ u)))) ∧ (((u ∧ s) ∧ v) ∧ ((t ∧ q) → p))) → (r ∨ (p ∧ u)))
(((((((p ∨ u) ∨ r) → ((u ∧ s) → v)) ∧ (((q ∧ v) ∧ s) → (q ∧ (u ∨ r)))) ∧ ((((u ∧ s) → v) ∧ (q ∧ (u ∨ r))) → (s ∨ (v ∧ q)))) ∧ (((p ∨ u) ∨ r) ∧ ((q ∧ v) ∧ s))) → (s ∨ (v ∧ q)))
(((((((q ∨ s) ∨ t) → (q ∨ (r ∧ u))) ∧ (((p ∧ u) → q) → ((q ∧ r) ∧ v))) ∧ (((q ∨ (r ∧ u)) ∧ ((q ∧ r) ∧ v)) → (s → (t ∨ q)))) ∧ (((q ∨ s) ∨ t) ∧ ((p ∧ u) → q))) → (s → (t ∨ q)))
(((((((q ∧ s) → p) → ((s ∧ t) ∧ r)) ∧ ((s → (p ∨ q)) → ((q ∧ r) ∧ p))) ∧ ((((s ∧ t) ∧ r) ∧ ((q ∧ r) ∧ p)) → ((v ∧ r) → u))) ∧ (((q ∧ s) → p) ∧ (s → (p ∨ q)))) → ((v ∧ r) → u))
(((((((u ∧ p) ∧ q) → ((q ∧ p) → t)) ∧ ((r ∧ (q ∨ s)) → (v ∨ (r ∧ p)))) ∧ ((((q ∧ p) → t) ∧ (v ∨ (r ∧ p))) → ((t ∨ p) ∨ u))) ∧ (((u ∧ p) ∧ q) ∧ (r ∧ (q ∨ s)))) → ((t ∨ p) ∨ u))
(((((((t ∨ q) ∨ u) → (q → (u ∨ p))) ∧ (((t ∧ v) ∧ r) → ((t ∨ s) ∨ u))) ∧ (((q → (u ∨ p)) ∧ ((t ∨ s) ∨ u)) → ((v ∧ p) → u))) ∧ (((t ∨ q) ∨ u) ∧ ((t ∧ v) ∧ r))) → ((v ∧ p) → u))'''.splitlines()


tests = '''¬((((u ∨ v) ∨ q) ∧ ¬(((u ∨ v) ∨ q))))
(((v ∨ (p ∧ t)) ∧ ((v ∨ (p ∧ t)) ∨ (v ∧ (u ∨ q)))) ↔ (v ∨ (p ∧ t)))
((t ∨ (r ∧ u)) → (((q ∧ r) ∧ s) ∨ (t ∨ (r ∧ u))))
((((r ∧ u) → q) ∧ ((p ∧ t) → q)) → ((p ∧ t) → q))
((((u ∧ r) → s) ∧ (((u ∧ r) → s) ∨ ((p ∨ t) ∨ u))) ↔ ((u ∧ r) → s))
((((t ∧ v) → u) ∧ ((t ∨ u) ∨ s)) → ((t ∨ u) ∨ s))
(((v ∧ q) ∧ r) → (((s ∧ v) ∧ p) → ((v ∧ q) ∧ r)))
(¬((((r ∧ v) → u) → (s ∨ (p ∧ r)))) ↔ (((r ∧ v) → u) ∧ ¬((s ∨ (p ∧ r)))))
(((t ∨ (q ∧ u)) ∧ ((p ∨ s) ∨ u)) → (((p ∨ s) ∨ u) ∧ (t ∨ (q ∧ u))))
(((((p ∧ v) ∧ u) → (t ∨ (q ∧ p))) ∧ ((p ∧ v) ∧ u)) → (t ∨ (q ∧ p)))
((u ∧ (r ∨ p)) → ((u ∧ (r ∨ p)) ∨ (r ∧ (s ∨ u))))
(¬((((u ∧ q) ∧ v) → (q ∧ (p ∨ v)))) ↔ (((u ∧ q) ∧ v) ∧ ¬((q ∧ (p ∨ v)))))
((r ∨ (p ∧ v)) → ((¬t ∨ r) → ((r ∨ (p ∧ v)) ∧ (¬t ∨ r))))
(((v ∨ (t ∧ p)) ∧ ((v ∨ (t ∧ p)) ∨ (t → (s ∨ v)))) ↔ (v ∨ (t ∧ p)))
((((v ∨ p) ∨ t) ∧ ((p ∨ v) ∨ q)) → ((v ∨ p) ∨ t))
((¬(((u ∨ v) ∨ p)) → ((u ∨ v) ∨ p)) → ((u ∨ v) ∨ p))
((s ∧ (r ∨ t)) → ((s ∧ (r ∨ t)) ∨ ((q ∧ r) → s)))
((((q ∧ s) → p) ∨ (((q ∧ s) → p) ∧ ((v ∧ r) → q))) ↔ ((q ∧ s) → p))
(((((t ∨ p) ∨ q) ∨ ((t ∧ p) ∧ u)) ∧ ¬(((t ∨ p) ∨ q))) → ((t ∧ p) ∧ u))
(((p ∧ u) → r) → ((q ↔ t) → (((p ∧ u) → r) ∧ (q ↔ t))))
((((p ∨ (s ∧ r)) ∨ ((p ∨ u) ∨ s)) ∧ ¬((p ∨ (s ∧ r)))) → ((p ∨ u) ∨ s))
((s → (t ∨ v)) → ((s → (t ∨ v)) ∨ (u ∧ (q ∨ p))))
(((¬p ∨ t) ∧ (t → (q ∨ p))) → (t → (q ∨ p)))
(((u ∨ (v ∧ r)) ∨ ((u ∨ (v ∧ r)) ∧ (v → t))) ↔ (u ∨ (v ∧ r)))
(((v → (u ∨ t)) ∧ (t → p)) → ((t → p) ∧ (v → (u ∨ t))))
((u → (r ∨ t)) → (((u ∧ t) ∧ s) → ((u → (r ∨ t)) ∧ ((u ∧ t) ∧ s))))
((¬(((q ∨ v) ∨ t)) → ((q ∨ v) ∨ t)) → ((q ∨ v) ∨ t))
(((((p ∧ q) ∧ v) ∨ (r → (u ∨ q))) ∧ ¬(((p ∧ q) ∧ v))) → (r → (u ∨ q)))
((((u → (v ∨ r)) ∨ ((u ∧ p) ∧ r)) ∧ ¬(((u ∧ p) ∧ r))) → (u → (v ∨ r)))
(((v ∨ (p ∧ r)) ∨ ((v ∨ (p ∧ r)) ∧ (s → u))) ↔ (v ∨ (p ∧ r)))
(((((s ∧ v) → t) ∨ ((v ∧ s) ∧ r)) ∧ ¬(((s ∧ v) → t))) → ((v ∧ s) ∧ r))
((((s ∧ v) ∧ r) ∨ (t ∧ r)) → ((t ∧ r) ∨ ((s ∧ v) ∧ r)))
((u ∨ (r ∧ t)) → ((u ∨ (r ∧ t)) ∨ ((t ∧ q) ∧ s)))
(((v ↔ s) ∨ ((v ↔ s) ∧ (v ∧ ¬t))) ↔ (v ↔ s))
(((t → (u ∨ q)) ∨ (r ↔ s)) → ((r ↔ s) ∨ (t → (u ∨ q))))
((((s ∨ u) ∨ r) ∨ ((s ∨ u) ∨ r)) ↔ ((s ∨ u) ∨ r))
(((v ∧ ¬r) ∧ (u ∧ (p ∨ r))) → (v ∧ ¬r))
(((s ∧ (p ∨ v)) ∧ (t ∨ (s ∧ r))) → ((t ∨ (s ∧ r)) ∧ (s ∧ (p ∨ v))))
((p ∧ (v ∨ u)) → (((u ∨ p) ∨ s) → (p ∧ (v ∨ u))))
(((r ∧ (q ∨ s)) ∨ ((v ∨ s) ∨ p)) → (((v ∨ s) ∨ p) ∨ (r ∧ (q ∨ s))))
((((t ∧ u) → q) ∧ ((t ∧ p) ∧ q)) → (((t ∧ p) ∧ q) ∧ ((t ∧ u) → q)))
(¬((((v ∨ s) ∨ t) → (u ↔ q))) ↔ (((v ∨ s) ∨ t) ∧ ¬((u ↔ q))))
((((u → (p ∨ r)) ∨ (¬u ∨ r)) ∧ ¬((u → (p ∨ r)))) → (¬u ∨ r))
((v ∧ (q ∨ s)) → ((v ∧ (q ∨ s)) ∨ (v → (s ∨ r))))
(((¬t ∨ s) ↔ (¬t ∨ q)) → ((¬t ∨ q) → (¬t ∨ s)))
((r → (s ∨ q)) → ((r → (s ∨ t)) ∨ (r → (s ∨ q))))
(((s ∨ t) ∨ u) → (((r ∧ s) ∧ t) → (((s ∨ t) ∨ u) ∧ ((r ∧ s) ∧ t))))
((((s ∧ (u ∨ r)) ∨ ((v ∨ s) ∨ u)) ∧ ¬((s ∧ (u ∨ r)))) → ((v ∨ s) ∨ u))
¬((((v ∧ s) ∧ q) ∧ ¬(((v ∧ s) ∧ q))))
(¬((((q ∧ v) ∧ t) ∨ (t ∧ v))) ↔ (¬(((q ∧ v) ∧ t)) ∧ ¬((t ∧ v))))
((¬(((u ∨ r) ∨ v)) → ¬(((t ∧ u) ∧ q))) → (((t ∧ u) ∧ q) → ((u ∨ r) ∨ v)))
(((u ∧ (t ∨ q)) ∨ ((q ∨ t) ∨ v)) → (((q ∨ t) ∨ v) ∨ (u ∧ (t ∨ q))))
(((r ∧ q) → s) → ((r → (v ∨ u)) → ((r ∧ q) → s)))
((((t ∧ (p ∨ v)) → (r ∧ (p ∨ s))) ∧ (t ∧ (p ∨ v))) → (r ∧ (p ∨ s)))
((((u → (v ∨ t)) → (r → (q ∨ p))) ∧ ¬((r → (q ∨ p)))) → ¬((u → (v ∨ t))))
((((u ∨ v) ∨ s) → ((s ∧ r) → v)) → (¬(((s ∧ r) → v)) → ¬(((u ∨ v) ∨ s))))
((¬((v ∧ (s ∨ u))) → ¬(((u ∧ r) → v))) → (((u ∧ r) → v) → (v ∧ (s ∨ u))))
(¬(((q ∧ ¬t) → ((p ∨ r) ∨ u))) ↔ ((q ∧ ¬t) ∧ ¬(((p ∨ r) ∨ u))))
((((r ∨ u) ∨ s) ∨ (r → (t ∨ v))) → ((r → (t ∨ v)) ∨ ((r ∨ u) ∨ s)))
((((s ∨ q) ∨ p) ∨ (t ∨ v)) → ((t ∨ v) ∨ ((s ∨ q) ∨ p)))
((((r ∨ s) ∨ p) ∨ (((r ∨ s) ∨ p) ∧ (p ∨ (v ∧ q)))) ↔ ((r ∨ s) ∨ p))
((((t ∨ q) ∨ s) ∧ (((t ∨ q) ∨ s) ∨ (s ∨ u))) ↔ ((t ∨ q) ∨ s))
(((((r ∧ q) ∧ s) ∨ (u ∨ (t ∧ s))) ∧ ¬((u ∨ (t ∧ s)))) → ((r ∧ q) ∧ s))
((((s ∨ q) ∨ ((v ∧ s) → p)) ∧ ¬(((v ∧ s) → p))) → (s ∨ q))
((((r → (v ∨ q)) ∨ (v ∨ (t ∧ u))) ∧ ¬((v ∨ (t ∧ u)))) → (r → (v ∨ q)))
((((r → (v ∨ t)) ∨ ((r ∧ u) → q)) ∧ ¬((r → (v ∨ t)))) → ((r ∧ u) → q))
((((v ∨ p) ∨ t) ↔ (s → (t ∨ v))) → ((s → (t ∨ v)) → ((v ∨ p) ∨ t)))
((¬((p ∨ (q ∧ u))) → (p ∨ (q ∧ u))) → (p ∨ (q ∧ u)))
((((t ∨ u) ∨ v) ∧ ((r ∨ s) ∨ t)) → ((t ∨ u) ∨ v))
((((r ∨ (p ∧ s)) → ((r ∧ q) ∧ p)) ∧ (r ∨ (p ∧ s))) → ((r ∧ q) ∧ p))
((((v ∧ p) ∧ r) ∧ ((t ∧ p) ∧ s)) → ((t ∧ p) ∧ s))
((((u ∧ p) ∧ v) ∧ (r ∨ (v ∧ s))) → ((u ∧ p) ∧ v))
(((((u ∧ q) ∧ r) ∨ (r → (v ∨ s))) ∧ ¬((r → (v ∨ s)))) → ((u ∧ q) ∧ r))
(((((t ∨ s) ∨ v) ∨ (t ∨ (s ∧ v))) ∧ ¬((t ∨ (s ∧ v)))) → ((t ∨ s) ∨ v))
(((q ∨ (v ∧ t)) ∧ ((p ∨ q) ∨ v)) → (q ∨ (v ∧ t)))
((((t ∧ u) → p) → (p ∧ (v ∨ u))) ↔ (¬(((t ∧ u) → p)) ∨ (p ∧ (v ∨ u))))
¬(((¬u ∨ q) ∧ ¬((¬u ∨ q))))
((((r → (p ∨ q)) ∨ ((t ∨ r) ∨ v)) ∧ ¬((r → (p ∨ q)))) → ((t ∨ r) ∨ v))
((s ∧ ¬u) → (((s ∧ p) → u) → ((s ∧ ¬u) ∧ ((s ∧ p) → u))))
(((s ∧ u) → q) → (((s ∧ u) → q) ∨ (p → (u ∨ r))))
¬(((t ∧ (s ∨ v)) ∧ ¬((t ∧ (s ∨ v)))))
((((q → (v ∨ s)) → (u → t)) ∧ (q → (v ∨ s))) → (u → t))
((((¬s ∨ p) → (s ∨ (q ∧ t))) ∧ (¬s ∨ p)) → (s ∨ (q ∧ t)))
((((q ∨ t) ∨ r) ∨ (u → (p ∨ r))) → ((u → (p ∨ r)) ∨ ((q ∨ t) ∨ r)))
((((r ∨ t) ∨ u) ∨ (p ∧ (q ∨ r))) → ((p ∧ (q ∨ r)) ∨ ((r ∨ t) ∨ u)))
((((u ∨ (r ∧ s)) ∨ (r → (q ∨ p))) ∧ ¬((r → (q ∨ p)))) → (u ∨ (r ∧ s)))
((((u ∧ v) → p) ∧ (v ∧ (t ∨ q))) → ((u ∧ v) → p))
(((u ∧ p) → r) → (((u ∧ p) → r) ∨ (p ∧ (v ∨ q))))
(((t ∨ (p ∧ u)) ∧ ((r ∧ u) ∧ s)) → (t ∨ (p ∧ u)))
((((r ∨ v) ∨ u) ↔ ((s ∧ v) ∧ u)) → (¬(((r ∨ v) ∨ u)) ↔ ¬(((s ∧ v) ∧ u))))
¬(((t ∨ v) ∧ ¬((t ∨ v))))
((¬(((s ∨ q) ∨ t)) → ((s ∨ q) ∨ t)) → ((s ∨ q) ∨ t))
(((u ↔ (q → (t ∨ s))) ∧ ((q → (t ∨ s)) ↔ (v ↔ q))) → (u ↔ (v ↔ q)))
((v ∧ (p ∨ u)) → (((u ∧ r) → q) → ((v ∧ (p ∨ u)) ∧ ((u ∧ r) → q))))
((((s ∧ u) ∧ p) ∨ (((s ∧ u) ∧ p) ∧ (u ∨ q))) ↔ ((s ∧ u) ∧ p))
(((s ∧ (p ∨ q)) ∧ ((v ∧ q) ∧ t)) → ((v ∧ q) ∧ t))
(((¬s ∨ p) → ((v ∧ u) ∧ s)) → (¬(((v ∧ u) ∧ s)) → ¬((¬s ∨ p))))
(((((s ∧ t) ∧ u) ∨ ((r ∧ s) ∧ p)) ∧ ¬(((s ∧ t) ∧ u))) → ((r ∧ s) ∧ p))
¬(((p → (v ∨ q)) ∧ ¬((p → (v ∨ q)))))
(((r ∧ v) ↔ ((s ∧ p) ∧ t)) → ((r ∧ v) → ((s ∧ p) ∧ t)))
((((¬u ∨ p) ∨ ((u ∧ s) ∧ p)) ∧ ¬(((u ∧ s) ∧ p))) → (¬u ∨ p))
((((r ∧ u) ∧ t) → ((v ∧ r) ∧ q)) → (¬(((v ∧ r) ∧ q)) → ¬(((r ∧ u) ∧ t))))
((((p ∨ (q ∧ v)) → (s ∧ (r ∨ p))) → (p ∨ (q ∧ v))) → (p ∨ (q ∧ v)))
((((s ∧ u) → v) ∨ (s ∨ (v ∧ u))) → ((s ∨ (v ∧ u)) ∨ ((s ∧ u) → v)))
((((q ∨ u) ∨ t) ∨ ((q ∧ r) ∧ p)) → (((q ∧ r) ∧ p) ∨ ((q ∨ u) ∨ t)))
((((p ∧ q) ∧ s) ∧ (((p ∧ q) ∧ s) ∨ (s ∨ v))) ↔ ((p ∧ q) ∧ s))
((((v ∧ u) → t) ∨ (((v ∧ u) → t) ∧ ((t ∧ q) ∧ s))) ↔ ((v ∧ u) → t))
(((s ∧ (t ∨ r)) ∧ ((s ∧ (t ∨ r)) ∨ ((s ∨ u) ∨ t))) ↔ (s ∧ (t ∨ r)))
((((p → (s ∨ t)) ∨ ((p ∧ q) → r)) ∧ ¬((p → (s ∨ t)))) → ((p ∧ q) → r))
(((q ∧ ¬v) → (r ∨ (t ∧ u))) ↔ (¬((q ∧ ¬v)) ∨ (r ∨ (t ∧ u))))
(((((q ∧ t) ∧ s) ∨ (s → (r ∨ v))) ∧ ¬((s → (r ∨ v)))) → ((q ∧ t) ∧ s))
((t → (u ∨ v)) → (((t ∧ u) ∧ r) ∨ (t → (u ∨ v))))
(((q → (u ∨ v)) ∧ (r ∧ u)) → (r ∧ u))
((((s ∨ v) ∨ t) → (s ∧ v)) → (¬((s ∧ v)) → ¬(((s ∨ v) ∨ t))))
((((u → (r ∨ p)) → (u ∨ (t ∧ q))) ∧ (u → (r ∨ p))) → (u ∨ (t ∧ q)))
(((t ∧ q) ∧ u) → ¬¬(((t ∧ q) ∧ u)))
(((s ∨ (q ∧ t)) ↔ (v ∨ (u ∧ r))) → ((s ∨ (q ∧ t)) → (v ∨ (u ∧ r))))
(((q ∧ p) → r) → (((q ∧ p) → r) ∨ ((s ∨ u) ∨ q)))
(((((s ∨ r) ∨ q) → (v ∨ (p ∧ q))) ∧ ¬((v ∨ (p ∧ q)))) → ¬(((s ∨ r) ∨ q)))
(((v ∧ (p ∨ u)) ∨ (v ∧ (p ∨ u))) ↔ (v ∧ (p ∨ u)))
(((((s ∧ v) ∧ u) → (s ↔ r)) ∧ ((s ∧ v) ∧ u)) → (s ↔ r))
¬(((p ∧ r) ∧ ¬((p ∧ r))))
((r → (q ∨ p)) → ((¬r ∨ q) → (r → (q ∨ p))))
(¬(((s ∧ (r ∨ u)) ∨ (r ∨ u))) ↔ (¬((s ∧ (r ∨ u))) ∧ ¬((r ∨ u))))
(¬((((p ∧ s) ∧ q) → ((p ∧ u) → r))) ↔ (((p ∧ s) ∧ q) ∧ ¬(((p ∧ u) → r))))
(((u ∧ (r ∨ v)) ∧ (r → (q ∨ p))) → (u ∧ (r ∨ v)))
(((u → v) → (v ∧ (p ∨ t))) → (¬((v ∧ (p ∨ t))) → ¬((u → v))))
((((r ∧ s) ∧ p) ∧ (((r ∧ s) ∧ p) ∨ ((t ∨ u) ∨ v))) ↔ ((r ∧ s) ∧ p))
((¬(((q ∧ p) → t)) → ¬((s → r))) → ((s → r) → ((q ∧ p) → t)))
((p ↔ t) → (((p ∨ u) ∨ r) → (p ↔ t)))
(((u ∨ p) ↔ ((p ∨ q) ∨ r)) → (((p ∨ q) ∨ r) → (u ∨ p)))
(((u ∧ (r ∨ p)) ↔ (t ∨ (s ∧ r))) → ((u ∧ (r ∨ p)) → (t ∨ (s ∧ r))))
(((r ∨ (v ∧ p)) ∧ ((u ∨ v) ∨ r)) → ((u ∨ v) ∨ r))
((((t ∧ u) → s) ∧ (((t ∧ u) → s) ∨ ((r ∨ t) ∨ v))) ↔ ((t ∧ u) → s))
(((q → (r ∨ t)) ∧ ((q → (r ∨ t)) ∨ ((r ∧ q) ∧ t))) ↔ (q → (r ∨ t)))
(((u ∧ t) → p) → ¬¬(((u ∧ t) → p)))
((((r ∧ q) ∧ s) ↔ (s → v)) → (((r ∧ q) ∧ s) → (s → v)))
(((((u ∨ s) ∨ v) → (r ∨ v)) ∧ (¬(((u ∨ s) ∨ v)) → (r ∨ v))) → (r ∨ v))
(((p ∨ (v ∧ r)) ∨ (p ∨ (v ∧ r))) ↔ (p ∨ (v ∧ r)))
((u ∧ (p ∨ q)) → (((p ∧ q) ∧ v) ∨ (u ∧ (p ∨ q))))
(((((q ∨ v) ∨ u) → (s ∧ ¬q)) ∧ (¬(((q ∨ v) ∨ u)) → (s ∧ ¬q))) → (s ∧ ¬q))
(((s ∧ p) → t) → ((u ∧ (p ∨ q)) → ((s ∧ p) → t)))
(((v ∧ s) ∧ u) → (((v ∧ s) ∧ u) ∨ (u ∨ (q ∧ s))))
((r ∧ (q ∨ p)) → (((v ∨ p) ∨ u) → ((r ∧ (q ∨ p)) ∧ ((v ∨ p) ∨ u))))
((((t ∨ (v ∧ u)) ∨ (u ∨ v)) ∧ ¬((u ∨ v))) → (t ∨ (v ∧ u)))
((q → (r ∨ v)) → ((v ↔ q) ∨ (q → (r ∨ v))))
¬((((p ∧ t) ∧ u) ∧ ¬(((p ∧ t) ∧ u))))
(((((v ∨ p) ∨ s) → ((v ∧ t) → u)) ∧ ¬(((v ∧ t) → u))) → ¬(((v ∨ p) ∨ s)))
((((r ∨ v) ∨ u) ∨ ((r ∨ v) ∨ u)) ↔ ((r ∨ v) ∨ u))
(((p ∨ (s ∧ q)) → ((q ∨ r) ∨ v)) ↔ (¬((p ∨ (s ∧ q))) ∨ ((q ∨ r) ∨ v)))
(((q ∧ p) → s) → ((p → u) → ((q ∧ p) → s)))
((((u ∨ r) ∨ v) ↔ (q ∧ (v ∨ r))) → ((q ∧ (v ∨ r)) → ((u ∨ r) ∨ v)))
(¬(((t ∧ (q ∨ u)) → (u → (t ∨ s)))) ↔ ((t ∧ (q ∨ u)) ∧ ¬((u → (t ∨ s)))))
(((q ∨ t) ∨ s) → (((s ∧ q) → t) ∨ ((q ∨ t) ∨ s)))
(((((p ∧ u) → r) ∨ ((p ∧ t) → s)) ∧ ¬(((p ∧ t) → s))) → ((p ∧ u) → r))
(¬((((q ∧ u) ∧ v) ∨ (¬r ∨ s))) ↔ (¬(((q ∧ u) ∧ v)) ∧ ¬((¬r ∨ s))))
((((u ∨ t) ∨ s) → (p ↔ s)) → (¬((p ↔ s)) → ¬(((u ∨ t) ∨ s))))
(((u → (r ∨ v)) ∧ (u ∧ (q ∨ p))) → (u → (r ∨ v)))
((q → (r ∨ t)) → (t → ((q → (r ∨ t)) ∧ t)))
((((u ∧ v) → q) ∨ ((s ∧ t) ∧ r)) → (((s ∧ t) ∧ r) ∨ ((u ∧ v) → q)))
((v ∧ (q ∨ t)) → (((r ∧ p) → v) → (v ∧ (q ∨ t))))
((((s ∧ p) ∧ v) ∧ (q → (t ∨ r))) → ((s ∧ p) ∧ v))
((u ∧ (v ∨ p)) → ((v ∨ (p ∧ q)) → (u ∧ (v ∨ p))))
((((r ∧ (t ∨ u)) ∨ ((v ∧ q) ∧ p)) ∧ ¬(((v ∧ q) ∧ p))) → (r ∧ (t ∨ u)))
(((t ∧ p) ∧ (t ∧ p)) ↔ (t ∧ p))
((¬((u → (t ∨ v))) → ¬((t ∨ (q ∧ s)))) → ((t ∨ (q ∧ s)) → (u → (t ∨ v))))
((¬(((v ∧ q) ∧ r)) → ¬(((u ∧ r) ∧ t))) → (((u ∧ r) ∧ t) → ((v ∧ q) ∧ r)))
(((s ∨ (v ∧ r)) ∧ (r ∧ (v ∨ u))) → (s ∨ (v ∧ r)))
¬(((s ∨ (v ∧ q)) ∧ ¬((s ∨ (v ∧ q)))))
(((t → u) ↔ (p → (q ∨ s))) → ((t → u) → (p → (q ∨ s))))
(¬((((r ∧ p) → q) → ((p ∨ s) ∨ u))) ↔ (((r ∧ p) → q) ∧ ¬(((p ∨ s) ∨ u))))
((((v ∧ r) → t) ∧ (t → (p ∨ v))) → (t → (p ∨ v)))
(((s ∧ r) → (p ∨ (r ∧ u))) → (¬((p ∨ (r ∧ u))) → ¬((s ∧ r))))
((p ∨ (q ∧ v)) → ((p ∨ (q ∧ v)) ∨ ((q ∧ s) → t)))
((((v → (t ∨ q)) → ((u ∨ v) ∨ p)) ∧ (v → (t ∨ q))) → ((u ∨ v) ∨ p))
(((u → (s ∨ v)) ∨ ((t ∧ u) ∧ s)) → (((t ∧ u) ∧ s) ∨ (u → (s ∨ v))))
((((p ∧ (v ∨ q)) ∨ (v ∧ (u ∨ q))) ∧ ¬((p ∧ (v ∨ q)))) → (v ∧ (u ∨ q)))
(((q ∨ p) ∨ s) → (((v ∨ s) ∨ u) → (((q ∨ p) ∨ s) ∧ ((v ∨ s) ∨ u))))
((((t ∧ (q ∨ s)) → ((q ∧ t) → r)) ∧ (t ∧ (q ∨ s))) → ((q ∧ t) → r))
((((s ∧ p) ∧ q) ∧ (((s ∧ p) ∧ q) ∨ ((s ∧ u) ∧ t))) ↔ ((s ∧ p) ∧ q))
(((r ∨ p) ∨ q) → (((r ∨ p) ∨ q) ∨ ((q ∨ u) ∨ s)))
((¬(((r ∨ u) ∨ v)) → ¬((s ∧ (u ∨ t)))) → ((s ∧ (u ∨ t)) → ((r ∨ u) ∨ v)))
((((p ∧ ¬r) → ((s ∨ r) ∨ q)) ∧ (p ∧ ¬r)) → ((s ∨ r) ∨ q))
((((s ∧ v) ∧ r) ∧ (q → (p ∨ t))) → ((q → (p ∨ t)) ∧ ((s ∧ v) ∧ r)))
(((q ∧ p) ∧ u) → (((q ∨ v) ∨ s) → ((q ∧ p) ∧ u)))
((((q ∧ (v ∨ s)) ∨ (u ∧ (q ∨ r))) ∧ ¬((q ∧ (v ∨ s)))) → (u ∧ (q ∨ r)))
(((v ∨ (t ∧ s)) → ((u ∧ r) ∧ p)) → (¬(((u ∧ r) ∧ p)) → ¬((v ∨ (t ∧ s)))))
(¬(((s ↔ q) ∨ (t ∧ (u ∨ p)))) ↔ (¬((s ↔ q)) ∧ ¬((t ∧ (u ∨ p)))))
((((r ∧ t) → u) ∧ (r → (q ∨ u))) → ((r ∧ t) → u))
(((((u ∨ s) ∨ v) ∨ (u ∧ (v ∨ r))) ∧ ¬((u ∧ (v ∨ r)))) → ((u ∨ s) ∨ v))
(((u ∨ r) ∨ t) → (((r ∧ q) ∧ s) → ((u ∨ r) ∨ t)))
(((t ∧ v) ∧ q) → ((r ∨ q) → ((t ∧ v) ∧ q)))
((((v ∨ (u ∧ p)) ∨ ((s ∨ v) ∨ q)) ∧ ¬(((s ∨ v) ∨ q))) → (v ∨ (u ∧ p)))
((((t ∧ s) ∧ q) ∧ (((t ∧ s) ∧ q) ∨ (s ∧ ¬r))) ↔ ((t ∧ s) ∧ q))
((((q → (p ∨ v)) → (t ∨ (u ∧ v))) ∧ ¬((t ∨ (u ∧ v)))) → ¬((q → (p ∨ v))))
(((v ∧ (u ∨ t)) ∨ ((v ∧ (u ∨ t)) ∧ ((p ∨ s) ∨ u))) ↔ (v ∧ (u ∨ t)))
(((((v ∧ u) ∧ r) → ((q ∨ p) ∨ u)) ∧ ¬(((q ∨ p) ∨ u))) → ¬(((v ∧ u) ∧ r)))
(((q ∧ ¬u) ∧ (r ∧ (v ∨ p))) → (r ∧ (v ∨ p)))
(((t ∨ (v ∧ r)) ↔ ((r ∧ q) ∧ s)) → (¬((t ∨ (v ∧ r))) ↔ ¬(((r ∧ q) ∧ s))))
(((((s ∨ r) ∨ p) → (u ∧ (t ∨ q))) ∧ ((s ∨ r) ∨ p)) → (u ∧ (t ∨ q)))'''.splitlines()

answers = dict()
for i in tests:
    answers[i] = None

bundle_proving = load_nanogpt_bundle("out-NEW_CORPUS_PROVING")
bundle_smashing = load_nanogpt_bundle("out-NEW_CORPUS_SMASH")

if __name__ == "__main__":
    for counter, i in enumerate(tqdm(tests), start=1):
        if answers[i] is not None:
            continue

        result, err = run_one(i)

        if err is not None:
            print(f"{i}: {err}")
            answers[i] = False
        else:
            answers[i] = result

        if counter % SAVE_EVERY == 0:
            save_answers()

    save_answers()
